# Spec-derived file. Regenerated by scripts/generate from spec/openapi.yaml — see CONTRIBUTING.md.

__title__ = "anchorbrowser"
__version__ = "1.0.0"  # bumped by the release workflow (.github/workflows/release.yml)
