# Generated by scripts/generate from spec/openapi.yaml — do not edit.
# pyright: reportInvalidTypeForm=false
# mypy: disable-error-code=valid-type

from __future__ import annotations

from uuid import UUID
from typing import Any, Literal

from pydantic import Field, AnyUrl, RootModel, ConfigDict, AwareDatetime, constr

from anchorbrowser._models import BaseModel


class Data(BaseModel):
    status: str | None = None


class SuccessResponse(BaseModel):
    data: Data | None = None


class Error(BaseModel):
    code: int | None = None
    message: str | None = None


class ErrorResponse(BaseModel):
    error: Error | None = None


class CustomProxy(BaseModel):
    type: Literal["custom"]
    server: str = Field(
        ...,
        description="Proxy address in **PROTOCOL://HOST:PORT** format (e.g., https://proxy.example.com:443). See [Bring Your Own Proxy](/advanced/bring-your-own-proxy).",
    )
    username: str = Field(..., description="Proxy username")
    password: str = Field(..., description="Proxy password")
    active: bool


class AnchorProxyCountryCode(
    RootModel[
        Literal[
            "af",
            "al",
            "dz",
            "ad",
            "ao",
            "as",
            "ag",
            "ar",
            "am",
            "aw",
            "au",
            "at",
            "az",
            "bs",
            "bh",
            "bb",
            "by",
            "be",
            "bz",
            "bj",
            "bm",
            "bo",
            "ba",
            "br",
            "bg",
            "bf",
            "cm",
            "ca",
            "cv",
            "td",
            "cl",
            "co",
            "cg",
            "cr",
            "ci",
            "hr",
            "cu",
            "cy",
            "cz",
            "dk",
            "dm",
            "do",
            "ec",
            "eg",
            "sv",
            "ee",
            "et",
            "fo",
            "fi",
            "fr",
            "gf",
            "pf",
            "ga",
            "gm",
            "ge",
            "de",
            "gh",
            "gi",
            "gr",
            "gd",
            "gp",
            "gt",
            "gg",
            "gn",
            "gw",
            "gy",
            "ht",
            "hn",
            "hu",
            "is",
            "in",
            "ir",
            "iq",
            "ie",
            "il",
            "it",
            "jm",
            "jp",
            "jo",
            "kz",
            "kw",
            "kg",
            "lv",
            "lb",
            "ly",
            "li",
            "lt",
            "lu",
            "mk",
            "ml",
            "mt",
            "mq",
            "mr",
            "mx",
            "md",
            "mc",
            "me",
            "ma",
            "nl",
            "nz",
            "ni",
            "ng",
            False,
            "pk",
            "pa",
            "py",
            "pe",
            "ph",
            "pl",
            "pt",
            "pr",
            "qa",
            "ro",
            "lc",
            "sm",
            "sa",
            "sn",
            "rs",
            "sc",
            "sl",
            "sk",
            "si",
            "so",
            "za",
            "kr",
            "es",
            "sr",
            "se",
            "ch",
            "sy",
            "st",
            "tw",
            "tj",
            "tg",
            "tt",
            "tn",
            "tr",
            "tc",
            "ua",
            "ae",
            "us",
            "uy",
            "uz",
            "ve",
            "ye",
        ]
    ]
):
    root: Literal[
        "af",
        "al",
        "dz",
        "ad",
        "ao",
        "as",
        "ag",
        "ar",
        "am",
        "aw",
        "au",
        "at",
        "az",
        "bs",
        "bh",
        "bb",
        "by",
        "be",
        "bz",
        "bj",
        "bm",
        "bo",
        "ba",
        "br",
        "bg",
        "bf",
        "cm",
        "ca",
        "cv",
        "td",
        "cl",
        "co",
        "cg",
        "cr",
        "ci",
        "hr",
        "cu",
        "cy",
        "cz",
        "dk",
        "dm",
        "do",
        "ec",
        "eg",
        "sv",
        "ee",
        "et",
        "fo",
        "fi",
        "fr",
        "gf",
        "pf",
        "ga",
        "gm",
        "ge",
        "de",
        "gh",
        "gi",
        "gr",
        "gd",
        "gp",
        "gt",
        "gg",
        "gn",
        "gw",
        "gy",
        "ht",
        "hn",
        "hu",
        "is",
        "in",
        "ir",
        "iq",
        "ie",
        "il",
        "it",
        "jm",
        "jp",
        "jo",
        "kz",
        "kw",
        "kg",
        "lv",
        "lb",
        "ly",
        "li",
        "lt",
        "lu",
        "mk",
        "ml",
        "mt",
        "mq",
        "mr",
        "mx",
        "md",
        "mc",
        "me",
        "ma",
        "nl",
        "nz",
        "ni",
        "ng",
        False,
        "pk",
        "pa",
        "py",
        "pe",
        "ph",
        "pl",
        "pt",
        "pr",
        "qa",
        "ro",
        "lc",
        "sm",
        "sa",
        "sn",
        "rs",
        "sc",
        "sl",
        "sk",
        "si",
        "so",
        "za",
        "kr",
        "es",
        "sr",
        "se",
        "ch",
        "sy",
        "st",
        "tw",
        "tj",
        "tg",
        "tt",
        "tn",
        "tr",
        "tc",
        "ua",
        "ae",
        "us",
        "uy",
        "uz",
        "ve",
        "ye",
    ] = Field("us", title="anchor_proxy")


class ProfileRequestSchema(BaseModel):
    name: str = Field(..., description="The name of the profile.")
    description: str | None = Field(None, description="A description of the profile.")
    source: Literal["session"] | None = Field(
        None, description="The source of the profile data. currently only `session` is supported."
    )
    session_id: UUID | None = Field(
        None,
        description="The browser session ID is required if the source is set to `session`. The browser session must be running, and the profile will be stored once the browser session terminates.",
    )
    dedicated_sticky_ip: bool | None = Field(
        None, description="Whether to use a dedicated sticky IP for this profile. Defaults to false."
    )


class ProfileResponseSchema(BaseModel):
    name: str | None = Field(None, description="The name of the profile.")
    description: str | None = Field(None, description="A description of the profile.")
    source: Literal["session"] | None = Field(None, description="The source of the profile data.")
    session_id: UUID | None = Field(
        None, description="The browser session ID used to create this profile, if applicable."
    )
    status: str | None = Field(None, description="The current status of the profile.")
    created_at: AwareDatetime | None = Field(None, description="The timestamp when the profile was created.")


class Data1(BaseModel):
    count: int | None = Field(None, description="Total number of profiles")
    items: list[ProfileResponseSchema] | None = None


class ProfileListResponse(BaseModel):
    data: Data1 | None = None


class ProfileResponse(BaseModel):
    data: ProfileResponseSchema | None = None


class Recording(BaseModel):
    active: bool | None = Field(
        None, description="Enable or disable video recording of the browser session. Defaults to `true`."
    )


class Timeout(BaseModel):
    max_duration: int | None = Field(
        None,
        description="Maximum time (in minutes) the session can run before automatically terminating. Defaults to `20`. Set to `-1` to disable this limit.",
    )
    idle_timeout: int | None = Field(
        None,
        description="Time (in minutes) the session waits for new connections after all others are closed before stopping. Defaults to `5`. Set to `-1` to disable this limit.",
    )


class LiveView(BaseModel):
    read_only: bool | None = Field(
        None, description="Enable or disable read-only mode for live viewing. Defaults to `false`."
    )
    one_time_url: bool | None = Field(
        None,
        description="Generate a single-use live view URL. After the first viewer connects, the link becomes invalid. Requires a headful browser. Defaults to `false`.",
    )


class Profile(BaseModel):
    name: str | None = Field(None, description="The name of the profile to be used during the browser session.")
    persist: bool | None = Field(
        None,
        description="Indicates whether the browser session profile data should be saved when the browser session ends. Defaults to `false`.",
    )


class Adblock(BaseModel):
    active: bool | None = Field(None, description="Enable or disable ad-blocking. Defaults to `true`.")


class PopupBlocker(BaseModel):
    active: bool | None = Field(
        None,
        description="Blocks popups, including ads and CAPTCHA consent banners. Requires adblock to be active. Defaults to `true`.",
    )


class CaptchaSolver(BaseModel):
    active: bool | None = Field(
        None, description="Enable or disable captcha-solving. Requires proxy to be active. Defaults to `false`."
    )


class Headless(BaseModel):
    active: bool | None = Field(None, description="Whether browser should be headless or headful. Defaults to `false`.")


class Viewport(BaseModel):
    width: int | None = Field(None, description="Width of the viewport in pixels. Defaults to `1440`.")
    height: int | None = Field(None, description="Height of the viewport in pixels. Defaults to `900`.")


class Fullscreen(BaseModel):
    active: bool | None = Field(
        None,
        description="Enable or disable fullscreen mode. When enabled, the browser will start in fullscreen mode. Defaults to `false`.",
    )


class PdfViewer(BaseModel):
    active: bool | None = Field(
        None,
        description="Enable or disable PDF viewer mode. When disabled, the browser will download PDFs instead of viewing them. Defaults to `true`.",
    )


class P2pDownload(BaseModel):
    active: bool | None = Field(
        None,
        description="Enable or disable P2P downloads. When enabled, the browser will capture downloads for direct data extraction, instead of uploading them on Anchor's storage. Defaults to `false`.",
    )


class DisableWebSecurity(BaseModel):
    active: bool | None = Field(
        None,
        description="Whether to disable web security features (CORS, same-origin policy, etc.). Allows accessing iframes and resources from different origins. Defaults to `false`.",
    )


class ExtraStealth(BaseModel):
    active: bool | None = Field(None, description="Enable or disable extra stealth mode.")


class ForcePopupsAsTabs(BaseModel):
    active: bool | None = Field(None, description="Enable or disable forcing popups as tabs. Defaults to `false`.")


class WebBotAuth(BaseModel):
    active: bool | None = Field(None, description="Enable or disable web bot auth. Defaults to `false`.")


class DisableDialogs(BaseModel):
    active: bool | None = Field(
        None, description="Enable or disable suppression of native browser dialogs. Defaults to `false`."
    )


class Tracing(BaseModel):
    active: bool | None = Field(None, description="Enable or disable tracing. Defaults to `true`.")
    snapshots: bool | None = Field(
        None, description="Enable or disable snapshot capture in traces. Defaults to `false`."
    )
    sources: bool | None = Field(
        None, description="Enable or disable source code capture in traces. Defaults to `true`."
    )


class CustomPattern(BaseModel):
    regex: str | None = Field(None, description="Regular expression pattern to match sensitive data.")
    mask: str | None = Field(None, description="Replacement string for matched text. Defaults to `****`.")


class SensitiveDataMask(BaseModel):
    active: bool | None = Field(None, description="Enable or disable sensitive data masking. Defaults to `false`.")
    custom_selectors: list[str] | None = Field(
        None,
        description="Additional CSS selectors to mask globally across all sites. Matched elements will be blurred.",
    )
    site_selectors: dict[str, list[str]] | None = Field(
        None,
        description="Per-site CSS selectors. Keys are hostnames (supports wildcard prefix like `*.bank.com`), values are arrays of CSS selectors. Matched elements will be blurred.",
    )
    custom_patterns: list[CustomPattern] | None = Field(
        None, description="Custom regex patterns to detect and mask additional sensitive data types."
    )


class BrowserConfig(BaseModel):
    profile: Profile | None = Field(None, description="Options for managing and persisting browser session profiles.")
    adblock: Adblock | None = Field(None, description="Configuration for ad-blocking.")
    popup_blocker: PopupBlocker | None = Field(None, description="Configuration for popup blocking.")
    captcha_solver: CaptchaSolver | None = Field(None, description="Configuration for captcha-solving.")
    headless: Headless | None = Field(None, description="Configuration for headless mode.")
    viewport: Viewport | None = Field(None, description="Configuration for the browser's viewport size.")
    fullscreen: Fullscreen | None = Field(None, description="Configuration for fullscreen mode.")
    pdf_viewer: PdfViewer | None = Field(None, description="Configuration for PDF viewer mode.")
    p2p_download: P2pDownload | None = Field(
        None, description="Configuration for peer-to-peer download capture functionality."
    )
    extensions: list[UUID] | None = Field(
        None,
        description="Array of extension IDs to load in the browser session. Extensions must be previously uploaded using the Extensions API.",
    )
    disable_web_security: DisableWebSecurity | None = Field(
        None, description="Configuration for disabling web security features."
    )
    extra_stealth: ExtraStealth | None = Field(
        None,
        description="Enables our dedicated patched Chromium build, designed to avoid bot detection and blocking. Works with Anchor Proxy enabled only.",
    )
    force_popups_as_tabs: ForcePopupsAsTabs | None = Field(
        None, description="Configuration for forcing popups to open as tabs instead of popup windows."
    )
    web_bot_auth: WebBotAuth | None = Field(
        None,
        description="Configuration for Cloudflare Web Bot Auth HTTP message signing. Enables authentication with websites that require Cloudflare's web bot authentication.",
    )
    disable_dialogs: DisableDialogs | None = Field(
        None,
        description="Suppresses native browser dialogs (window.alert, window.confirm, window.prompt). Useful for automated workflows where dialogs would block execution.",
    )
    tracing: Tracing | None = Field(None, description="Configuration for browser tracing and debugging capabilities.")
    sensitive_data_mask: SensitiveDataMask | None = Field(
        None,
        description="Automatically detects and masks sensitive data (passwords, emails, phone numbers, credit card fields, tokens) in web pages. Supports custom CSS selectors globally or per site, and custom regex patterns.",
    )


class Identity(BaseModel):
    id: str | None = Field(None, description="The identity ID to use for the browser session.")


class Data2(BaseModel):
    id: str | None = Field(None, description="Unique identifier for the browser session")
    cdp_url: str | None = Field(None, description="The CDP websocket connection string")
    live_view_url: str | None = Field(None, description="The browser session live view url")


class SessionCreateResponseSchema(BaseModel):
    data: Data2 | None = None


class Data3(BaseModel):
    request_id: UUID = Field(
        ...,
        description="Identifier of the async request. Use it to poll\n`GET /v1/sessions/async/{request_id}/status` for the resolved\n`session_id`, `cdp_url` and `live_view_url` once the pod\ncomes up.\n",
    )
    status: Literal["pending"] = Field(..., description="Always `pending` immediately after creation.")
    session_id: None = Field(
        ..., description="Always `null` immediately after creation; resolved via the polling endpoint."
    )


class AsyncSessionCreateResponseSchema(BaseModel):
    data: Data3 | None = None


class Progress(BaseModel):
    current_phase: Literal["queued", "provisioning", "configuring", "ready"] = Field(
        ..., description="The session's current pod-provisioning phase."
    )


class SessionStatus(BaseModel):
    session_id: str = Field(..., description="Unique identifier for the browser session")
    status: str = Field(..., description="Current status of the browser session")
    tags: list[str] | None = Field(None, description="Custom labels assigned to this browser session")
    created_at: AwareDatetime = Field(..., description="Timestamp when the browser session was created")


class Data5(BaseModel):
    count: int | None = Field(None, description="Total number of browser sessions")
    items: list[SessionStatus] | None = None


class SessionListResponse(BaseModel):
    data: Data5 | None = None


class UsedCredits(RootModel[str]):
    root: str = Field(
        ...,
        description="Credits consumed by the session (number or decimal string), or `N/A` while still running.",
        pattern="^-?\\d+(\\.\\d+)?$",
    )


class SessionHistoryPageItem(BaseModel):
    id: str = Field(..., description="Unique session identifier.")
    status: str = Field(..., description="Current session status.")
    tags: list[str] | None = Field(None, description="Tags associated with the session.")
    headless: bool = Field(..., description="Whether the session ran in headless mode.")
    recording: bool = Field(..., description="Whether recording was enabled for the session.")
    used_credits: float | UsedCredits | Literal["N/A"] = Field(
        ..., description="Credits consumed by the session (number or decimal string), or `N/A` while still running."
    )
    proxy_bytes: float | None = Field(None, description="Proxy bandwidth used in bytes.")
    proxy_type: str | None = Field(None, description="Proxy type configured for the session.")
    steps: float | None = Field(None, description="Number of AI/browser steps recorded.")
    duration: float | None = Field(None, description="Session duration in seconds.")
    created_at: AwareDatetime = Field(..., description="Session creation timestamp in UTC ISO 8601 format.")
    user_configuration: dict[str, Any] = Field(
        ..., description="Full user configuration payload saved for the session."
    )
    task_initiated: bool = Field(..., description="Whether the session was initiated by a task execution.")
    task_executions_count: float = Field(
        ..., description="Number of non-internal task executions associated with this session."
    )
    api_key_name: str = Field(..., description="Display name of the API key that created the session.")
    browser_ip: str = Field(..., description="Browser/proxy IP observed for the session.")
    domains: list[str] | None = Field(None, description="Domains observed during session execution.")


class Data6(BaseModel):
    sessions: list[SessionHistoryPageItem] = Field(..., description="Session records in the current page.")
    total: float = Field(..., description="Total number of matching sessions.")
    page: float = Field(..., description="Current page number.")
    total_pages: float = Field(..., description="Total number of pages.")


class SessionHistoryPageResponse(BaseModel):
    data: Data6 | None = None


class SessionHistoryDataPoint(BaseModel):
    date: str | None = Field(None, description="Date/time period for this data point.")
    session_count: float | None = Field(None, description="Number of sessions created in this period.")
    proxy_bytes: float | None = Field(None, description="Total proxy bytes used in this period.")
    ai_steps: float | None = Field(None, description="Total AI steps taken in this period.")
    session_hours: float | None = Field(None, description="Total session hours in this period (duration/3600).")
    credits_used: float | None = Field(None, description="Total credits used in this period.")
    screenshots: float | None = Field(None, description="Total screenshots taken in this period.")
    network_bytes_total: float | None = Field(None, description="Total network bytes sent and received in this period.")


class SessionHistorySummary(BaseModel):
    total_sessions: float | None = Field(None, description="Total number of sessions in the time range.")
    total_proxy_bytes: float | None = Field(None, description="Total proxy bytes used in the time range.")
    total_ai_steps: float | None = Field(None, description="Total AI steps taken in the time range.")
    total_session_hours: float | None = Field(None, description="Total session hours in the time range.")
    total_credits_used: float | None = Field(None, description="Total credits used in the time range.")
    total_screenshots: float | None = Field(None, description="Total screenshots taken in the time range.")
    total_network_bytes_total: float | None = Field(
        None, description="Total network bytes sent and received in the time range."
    )


class SessionHistoryPagination(BaseModel):
    current_page: int | None = None
    total_pages: int | None = None
    total_records: int | None = None
    has_next: bool | None = None
    has_prev: bool | None = None


class SessionHistoryResponse(BaseModel):
    data: list[SessionHistoryDataPoint] | None = Field(None, description="Historical data points.")
    summary: SessionHistorySummary | None = None
    pagination: SessionHistoryPagination | None = None


class Data7(BaseModel):
    credits: float = Field(..., description="Available credit balance for the authenticated project.")
    credits_used: float = Field(..., description="Credits used in the current billing period.")
    included_credits: float = Field(..., description="Credits included in the current tier before overage.")
    billing_period: str = Field(..., description="Current billing period in YYYY-MM format.")
    tier: str = Field(..., description="Billing tier for the project.")
    gifts_balance: float | None = Field(
        None, description="Available gift or prepaid credit balance before applicable overage."
    )
    max_concurrent_browsers: float | None = Field(
        None, description="Maximum concurrent browser sessions allowed for the project. `-1` means unlimited."
    )
    cost_limit: float | None = Field(None, description="Optional configured credit spend limit for the project.")


class BillingInfoResponse(BaseModel):
    data: Data7 | None = None


class RecordingItem(BaseModel):
    id: str | None = Field(None, description="Unique identifier for the recording")
    is_primary: bool | None = Field(None, description="Indicates if this is the primary recording")
    file_link: str | None = Field(None, description="URL to access the recording file")
    suggested_file_name: str | None = Field(None, description="Suggested filename for the recording")
    duration: str | None = Field(None, description="Duration of the recording")
    size: float | None = Field(None, description="Size of the recording file in bytes")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the recording was created")


class Data8(BaseModel):
    count: int | None = Field(None, description="Total number of video recordings")
    items: list[RecordingItem] | None = None


class RecordingListResponse(BaseModel):
    data: Data8 | None = None


class DownloadItem(BaseModel):
    id: str | None = Field(None, description="The unique ID of the download record.")
    file_link: AnyUrl | None = Field(
        None, description="The URL to download the file from anchorbrowser servers. Requires api key authentication."
    )
    original_download_url: AnyUrl | None = Field(None, description="The URL used to download the file.")
    origin_url: AnyUrl | None = Field(None, description="The original URL where the file was found.")
    suggested_file_name: str | None = Field(None, description="The suggested file name for saving the file.")
    original_file_name: str | None = Field(None, description="The original file name before any modification.")
    duration: int | None = Field(None, description="The time it took to process or download the file, in milliseconds.")
    size: int | None = Field(None, description="The size of the file in bytes.")
    created_at: AwareDatetime | None = Field(None, description="The timestamp when the file record was created.")


class Data9(BaseModel):
    count: int | None = Field(None, description="Total number of downloads")
    items: list[DownloadItem] | None = None


class DownloadListResponse(BaseModel):
    data: Data9 | None = None


class FetchWebpageRequestSchema(BaseModel):
    url: str | None = Field(
        None,
        description="The URL of the webpage or PDF to fetch content from. When left empty, the current webpage is used.",
    )
    format: Literal["html", "markdown"] | None = Field(None, description="The output format of the content.")
    wait: int | None = Field(None, description="The time to wait for **dynamic** content to load in **milliseconds**.")
    new_page: bool | None = Field(None, description="Whether to create a new page for the content.")
    page_index: int | None = Field(
        None, description="The index of the page to fetch content from. **Overides new_page**."
    )
    return_partial_on_timeout: bool | None = Field(
        None, description="Whether to return partial content if the content is not loaded within the 20 seconds."
    )


class WebUnlockerRequestSchema(BaseModel):
    url: str = Field(
        ..., description="The fully-qualified URL to fetch (e.g. `https://www.linkedin.com/company/openai`)."
    )


class ExecuteCodeRequestSchema(BaseModel):
    code: str = Field(
        ...,
        description="TypeScript snippet (async function body) with injected page, browser, context, sessionId, anchorClient.",
    )


class ExecuteCodeToolResponseSchema(BaseModel):
    success: bool
    message: str
    output: str | None = Field(None, description="JSON string of the return value when execution succeeds.")
    error: str | None = None
    execution_result_id: UUID | None = Field(None, alias="executionResultId")


class PerformWebTaskRequestSchema(BaseModel):
    url: str | None = Field(
        None, description="The URL of the webpage. If not provided, the tool will use the current page in the session."
    )
    prompt: str = Field(..., description="The task to be autonomously completed.")
    agent: Literal["browser-use", "openai-cua", "gemini-computer-use", "anthropic-cua", "yutori"] | None = Field(
        None, description="The AI agent to use for task completion. Defaults to browser-use."
    )
    provider: Literal["openai", "gemini", "groq", "azure", "xai"] | None = Field(
        None, description="The AI provider to use for task completion."
    )
    model: str | None = Field(
        None,
        description="The specific model to use for task completion. see our [models](/agentic-browser-control/ai-task-completion#available-models) page for more information.",
    )
    detect_elements: bool | None = Field(
        None,
        description="Enable element detection for better interaction accuracy. Improves the agent's ability to identify and interact with UI elements.",
    )
    human_intervention: bool | None = Field(
        None,
        description="Allow human intervention during task execution. When enabled, the agent can request human input for ambiguous situations.",
    )
    max_steps: int | None = Field(
        None, description="Maximum number of steps the agent can take to complete the task. Defaults to 200."
    )
    secret_values: dict[str, str] | None = Field(
        None,
        description="Secret values to pass to the agent for secure credential handling. Keys and values are passed as environment variables to the agent.",
    )
    highlight_elements: bool | None = Field(
        None, description="Whether to highlight elements during task execution for better visibility."
    )
    output_schema: dict[str, Any] | None = Field(
        None, description="JSON Schema defining the expected structure of the output data."
    )
    async_: bool | None = Field(
        False,
        alias="async",
        description="Whether to run the task asynchronously. If true, the task will be run asynchronously and the response will include a workflow ID.",
    )


class PerformWebTaskSyncResponseData(BaseModel):
    result: dict[str, Any] = Field(..., description="The outcome or answer produced by the autonomous task.")


class PerformWebTaskAsyncResponseData(BaseModel):
    status: Literal["running"] = Field(..., description="The status of the asynchronous task execution.")
    workflow_id: str = Field(..., description="The workflow ID for tracking the asynchronous task execution.")


class PerformWebTaskResponseSchema(BaseModel):
    data: PerformWebTaskSyncResponseData | PerformWebTaskAsyncResponseData | None = None


class PerformWebTaskStatusSuccessResponseData(BaseModel):
    status: Literal["COMPLETED"] = Field(..., description="The workflow has completed successfully.")
    result: dict[str, Any] = Field(..., description="The outcome or answer produced by the autonomous task.")


class PerformWebTaskStatusRunningResponseData(BaseModel):
    status: Literal["RUNNING"] = Field(..., description="The workflow is currently running.")


class PerformWebTaskStatusFailedResponseData(BaseModel):
    status: Literal["FAILED"] = Field(..., description="The workflow has failed.")
    error: str = Field(..., description="Error message describing why the workflow failed.")


class PerformWebTaskStatusResponseSchema(BaseModel):
    data: (
        PerformWebTaskStatusSuccessResponseData
        | PerformWebTaskStatusRunningResponseData
        | PerformWebTaskStatusFailedResponseData
    )


class HumanInterventionField(BaseModel):
    name: str = Field(..., description="Field identifier used in the response payload.")
    label: str = Field(..., description="Human-readable label displayed in the UI.")
    description: str | None = Field(None, description="Optional helper text for the field.")
    required: bool | None = Field(None, description="Whether the field must be filled before submitting a response.")
    type: Literal["text", "number", "url", "email", "password"] | None = Field(
        None, description="Input type for the field."
    )
    placeholder: str | None = Field(None, description="Placeholder text shown in the input.")
    default_value: str | None = Field(
        None, alias="defaultValue", description="Default value for the field (camelCase alias)."
    )


class HumanInterventionRequest(BaseModel):
    request_id: str = Field(
        ..., alias="requestId", description="Unique identifier for the intervention request. Use this when responding."
    )
    message: str = Field(..., description="The agent's prompt or question for the human operator.")
    input_type: Literal["text", "confirm", "fields"] | None = Field(
        None, alias="inputType", description="Expected response format (camelCase alias)."
    )
    fields: list[HumanInterventionField] | None = Field(
        None, description="Form fields to collect when `inputType` is `fields`."
    )


class PendingInterventionItem(HumanInterventionRequest):
    session_id: str = Field(
        ..., alias="sessionId", description="The browser session that raised the intervention request."
    )
    tags: list[str] = Field(..., description="Tags associated with the session.")


class Data10(BaseModel):
    count: int = Field(..., description="Total number of pending intervention requests across active sessions.")
    items: list[PendingInterventionItem]


class PendingInterventionsResponse(BaseModel):
    data: Data10


class Data11(BaseModel):
    status: str = Field(..., description="Operation status (e.g. `success`).")
    message: str | None = Field(None, description="Human-readable status message from the browser agent.")
    requests: list[HumanInterventionRequest] = Field(..., description="Pending intervention requests for this session.")


class HumanInterventionRequestsResponse(BaseModel):
    data: Data11


class HumanInterventionResponseRequest(BaseModel):
    request_id: str | None = Field(
        None,
        alias="requestId",
        description="ID of the intervention request to respond to. If omitted, the most recent\npending request for the session is used.\n",
    )
    response: str | bool | dict[str, Any] = Field(
        ...,
        description="Response payload. For `text` input type, pass a string. For `confirm`, pass\na boolean or confirmation string. For `fields`, pass an object keyed by field name.\n",
    )


class Data12(BaseModel):
    status: str = Field(..., description="Operation status (e.g. `success`).")
    message: str | None = Field(None, description="Human-readable confirmation from the browser agent.")


class HumanInterventionResponseResponse(BaseModel):
    data: Data12


class ScreenshotRequestSchema(BaseModel):
    url: str | None = Field(None, description="The URL of the webpage to capture.")
    width: int | None = Field(None, description="The width of the browser viewport in pixels.")
    height: int | None = Field(None, description="The height of the browser viewport in pixels.")
    image_quality: int | None = Field(
        None, description="Quality of the output image, on the range 1-100. 100 will not perform any compression."
    )
    wait: int | None = Field(
        None,
        description="Duration in milliseconds to wait after page has loaded, mainly used for sites with JS animations.",
    )
    scroll_all_content: bool | None = Field(
        None, description="If true, scrolls the page and captures all visible content."
    )
    capture_full_height: bool | None = Field(
        None, description="If true, captures the entire height of the page, ignoring the viewport height."
    )
    s3_target_address: str | None = Field(None, description="Presigned S3 url target to upload the image to.")


class CoordinatesRequestSchema(BaseModel):
    x: int = Field(..., description="X coordinate")
    y: int = Field(..., description="Y coordinate")


class MouseClickRequestSchema(CoordinatesRequestSchema):
    button: Literal["left", "middle", "right"] | None = Field(None, description="Mouse button to use")


class MouseSingleClickRequestSchema(BaseModel):
    x: float | None = Field(None, description="X coordinate")
    y: float | None = Field(None, description="Y coordinate")
    button: Literal["left", "middle", "right"] | None = Field(None, description="Mouse button to use")
    selector: str | None = Field(None, description="A valid CSS selector for the requested element")
    timeout: float | None = Field(
        None,
        description="If a selector was passed, timeout in ms for waiting for the DOM element to be selected. Defaults to 5000 (5 seconds).",
    )
    index: float | None = Field(
        None,
        description="If a selector was passed and multiple elements match the selector, the index of the element in the list (0-based). Defaults to 0.",
    )


class DragDropRequestSchema(BaseModel):
    start_x: int = Field(..., alias="startX", description="Starting X coordinate")
    start_y: int = Field(..., alias="startY", description="Starting Y coordinate")
    end_x: int = Field(..., alias="endX", description="Ending X coordinate")
    end_y: int = Field(..., alias="endY", description="Ending Y coordinate")
    button: Literal["left", "middle", "right"] | None = Field(None, description="Mouse button to use")


class ScrollRequestSchema(CoordinatesRequestSchema):
    delta_x: int | None = Field(
        None, alias="deltaX", description="Horizontal scroll amount (positive is right, negative is left)"
    )
    delta_y: int = Field(..., alias="deltaY", description="Vertical scroll amount (positive is down, negative is up)")
    steps: int | None = Field(None, description="Number of steps to break the scroll into for smoother scrolling")
    use_os: bool | None = Field(
        None, alias="useOs", description="Whether to use the OS scroll or the Playwright scroll"
    )


class TypeTextRequestSchema(BaseModel):
    text: str = Field(..., description="Text to type")
    delay: int | None = Field(None, description="Delay between keystrokes in milliseconds")


class KeyboardShortcutRequestSchema(BaseModel):
    keys: list[str] = Field(..., description="Array of keys to press simultaneously")
    hold_time: int | None = Field(None, alias="holdTime", description="Time to hold the keys down in milliseconds")


class Data13(BaseModel):
    text: str | None = Field(None, description="Text content of the clipboard")


class ClipboardResponseSchema(BaseModel):
    data: Data13 | None = None


class ClipboardRequestSchema(BaseModel):
    text: str = Field(..., description="Text to set in the clipboard")


class CopyResponseSchema(BaseModel):
    text: str | None = Field(None, description="The text that was copied")


class PasteRequestSchema(BaseModel):
    text: str = Field(..., description="Text to paste")


class NavigateRequestSchema(BaseModel):
    url: str = Field(..., description="The URL to navigate to")


class WaitForEventRequestSchema(BaseModel):
    timeout_ms: int | None = Field(
        None,
        alias="timeoutMs",
        description="Timeout in milliseconds to wait for the event. Defaults to 60000ms (1 minute).",
    )


class SignalEventRequestSchema(BaseModel):
    data: dict[str, Any] = Field(
        ...,
        description="Event data to be passed to waiting clients",
        examples=[{"message": "Task completed", "result": "success", "timestamp": "2024-01-01T12:00:00Z"}],
    )


class EventResponseSchema(BaseModel):
    data: dict[str, Any] | None = Field(
        None,
        description="The event data that was signaled",
        examples=[{"message": "Task completed", "result": "success", "timestamp": "2024-01-01T12:00:00Z"}],
    )


class ExtensionManifest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None
    version: str | None = None
    manifest_version: int | None = None
    description: str | None = None
    permissions: list[str] | None = None


class ExtensionResponseSchema(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the extension")
    name: str | None = Field(None, description="Extension name")
    manifest: ExtensionManifest | None = None
    created_at: AwareDatetime | None = Field(
        None, alias="createdAt", description="Timestamp when the extension was created"
    )
    updated_at: AwareDatetime | None = Field(
        None, alias="updatedAt", description="Timestamp when the extension was last updated"
    )


class ExtensionListResponse(BaseModel):
    data: list[ExtensionResponseSchema] | None = None


class ExtensionResponse(BaseModel):
    data: ExtensionResponseSchema | None = None


class CertificateResponseSchema(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the certificate")
    name: str | None = Field(None, description="Certificate name (used to reference in sessions)")
    description: str | None = Field(None, description="Optional description of the certificate")
    created_at: AwareDatetime | None = Field(
        None, alias="createdAt", description="Timestamp when the certificate was uploaded"
    )


class CertificateListResponse(BaseModel):
    data: list[CertificateResponseSchema] | None = None


class CertificateResponse(BaseModel):
    data: CertificateResponseSchema | None = None


class BatchSessionResponseSchema(BaseModel):
    batch_id: UUID | None = Field(None, description="Unique identifier for the batch")
    status: Literal["pending", "processing", "completed", "failed", "cancelled"] | None = Field(
        None, description="Current status of the batch"
    )
    total_requests: int | None = Field(None, description="Total number of sessions requested in the batch")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the batch was created")


class BatchSessionItemSchema(BaseModel):
    item_index: int | None = Field(None, description="Index of this session within the batch (0-based)")
    session_id: UUID | None = Field(
        None, description="Unique identifier for the browser session (if created successfully)"
    )
    status: Literal["pending", "processing", "completed", "failed", "cancelled"] | None = Field(
        None, description="Current status of this individual session"
    )
    cdp_url: str | None = Field(None, description="CDP websocket connection URL (if session is ready)")
    live_view_url: str | None = Field(None, description="Live view URL for the session (if session is ready)")
    error: str | None = Field(None, description="Error message if session creation failed")
    retry_count: int | None = Field(None, description="Number of times this session creation has been retried")
    started_at: AwareDatetime | None = Field(None, description="Timestamp when session creation started")
    completed_at: AwareDatetime | None = Field(None, description="Timestamp when session creation completed")
    metadata: dict[str, Any] | None = Field(None, description="Session-specific metadata")


class Progress1(BaseModel):
    percentage: float | None = Field(None, description="Completion percentage (0-100)", ge=0.0, le=100.0)
    current_phase: Literal["queued", "provisioning", "configuring", "ready"] | None = Field(
        None, description="Current processing phase"
    )


class BatchSessionStatusResponseSchema(BaseModel):
    batch_id: UUID | None = Field(None, description="Unique identifier for the batch")
    status: Literal["pending", "processing", "completed", "failed", "cancelled"] | None = Field(
        None, description="Current status of the batch"
    )
    total_requests: int | None = Field(None, description="Total number of sessions requested")
    completed_requests: int | None = Field(None, description="Number of sessions successfully created")
    failed_requests: int | None = Field(None, description="Number of sessions that failed to create")
    processing_requests: int | None = Field(None, description="Number of sessions currently being processed")
    pending_requests: int | None = Field(None, description="Number of sessions waiting to be processed")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the batch was created")
    actual_completion_time: AwareDatetime | None = Field(
        None, description="Timestamp when the batch completed (if completed)"
    )
    error: str | None = Field(None, description="Error message if batch failed")
    sessions: list[BatchSessionItemSchema] | None = Field(None, description="Array of individual session details")
    progress: Progress1 | None = None


class BatchSessionListItemSchema(BaseModel):
    batch_id: UUID | None = Field(None, description="Unique identifier for the batch")
    status: Literal["pending", "processing", "completed", "failed", "cancelled"] | None = Field(
        None, description="Current status of the batch"
    )
    total_requests: int | None = Field(None, description="Total number of sessions requested")
    completed_requests: int | None = Field(None, description="Number of sessions successfully completed")
    failed_requests: int | None = Field(None, description="Number of sessions that failed")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the batch was created")
    actual_completion_time: AwareDatetime | None = Field(
        None, description="Timestamp when the batch completed (if completed)"
    )


class Pagination(BaseModel):
    current_page: int | None = Field(None, description="Current page number")
    total_pages: int | None = Field(None, description="Total number of pages")
    total_records: int | None = Field(None, description="Total number of batch records")
    has_next: bool | None = Field(None, description="Whether there is a next page")
    has_prev: bool | None = Field(None, description="Whether there is a previous page")


class BatchSessionListResponseSchema(BaseModel):
    batches: list[BatchSessionListItemSchema] | None = Field(None, description="Array of batch session summaries")
    pagination: Pagination | None = None


class Error1(BaseModel):
    session_id: str | None = Field(None, description="ID of the session that failed to delete")
    error: str | None = Field(None, description="Error message")


class BatchSessionDeleteResponseSchema(BaseModel):
    batch_id: UUID | None = Field(None, description="Unique identifier for the batch")
    deleted_sessions: int | None = Field(None, description="Number of sessions successfully deleted")
    failed_deletions: int | None = Field(None, description="Number of sessions that failed to delete")
    errors: list[Error1] | None = Field(
        None, description="Details of deletion failures (only present if there were failures)"
    )
    message: str | None = Field(None, description="Summary message of the deletion operation")


class BatchSessionUpdateRequestSchema(BaseModel):
    status: Literal["cancelled"] = Field(..., description="Target status for the batch")


class BatchSessionUpdateResponseSchema(BaseModel):
    batch_id: UUID | None = Field(None, description="Unique identifier for the batch")
    status: Literal["cancelled"] | None = Field(None, description="New status of the batch")
    cancelled_sessions: int | None = Field(None, description="Number of running sessions that were terminated")
    message: str | None = Field(None, description="Summary message")


class BatchSessionRetryRequestSchema(BaseModel):
    retry_failed_only: bool | None = Field(True, description="Whether to only retry failed sessions")
    max_retries: int | None = Field(
        1,
        description="Maximum number of attempts per failed session. Each session is retried up to this many times, stopping on first success.",
        ge=1,
        le=3,
    )


class BatchSessionRetryResponseSchema(BaseModel):
    batch_id: UUID | None = Field(None, description="Unique identifier for the batch")
    status: Literal["pending", "processing", "completed", "failed", "cancelled"] | None = Field(
        None, description="Current status of the batch after retry"
    )
    retried_sessions: int | None = Field(None, description="Number of sessions that were retried")
    message: str | None = Field(None, description="Summary message")


class IntegrationType(RootModel[Literal["1PASSWORD"]]):
    root: Literal["1PASSWORD"] = Field(..., description="The type of integration")


class OnePasswordAllSecretsConfig(BaseModel):
    load_mode: Literal["all"] = Field(..., description="Load all secrets from 1Password")


class OnePasswordSpecificSecretsConfig(BaseModel):
    load_mode: Literal["specific"] = Field(..., description="Load specific secrets from 1Password")
    secrets: list[str] = Field(
        ..., description="Array of secret references to load", examples=[["op://vault/item/field"]], min_length=1
    )


class OnePasswordConfig(RootModel[OnePasswordAllSecretsConfig | OnePasswordSpecificSecretsConfig]):
    root: OnePasswordAllSecretsConfig | OnePasswordSpecificSecretsConfig


class OnePasswordIntegration(BaseModel):
    id: UUID = Field(..., description="Unique integration ID", examples=["550e8400-e29b-41d4-a716-446655440000"])
    type: Literal["1PASSWORD"] = Field(..., description="Integration type")
    configuration: OnePasswordConfig


class Integration(RootModel[OnePasswordIntegration]):
    root: OnePasswordIntegration = Field(..., discriminator="type")


class Data14(BaseModel):
    service_account: str = Field(
        ..., alias="serviceAccount", description="Service account token", examples=["ops_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
    )


class ServiceAccountCredentials(BaseModel):
    type: Literal["serviceAccount"] = Field(..., description="Credential type")
    data: Data14


class CreateIntegrationRequest(BaseModel):
    name: str = Field(..., description="Name for the integration", examples=["My 1Password Integration"], min_length=1)
    type: IntegrationType
    credentials: ServiceAccountCredentials


class IntegrationItem(BaseModel):
    id: UUID | None = Field(
        None, description="Unique integration ID", examples=["550e8400-e29b-41d4-a716-446655440000"]
    )
    name: str | None = Field(None, description="Integration name", examples=["My 1Password Integration"])
    type: IntegrationType | None = None
    path: str | None = Field(
        None,
        description="Storage path for the integration",
        examples=["integrations/team-id/550e8400-e29b-41d4-a716-446655440000"],
    )
    created_at: AwareDatetime | None = Field(
        None,
        alias="createdAt",
        description="Timestamp when the integration was created",
        examples=["2024-01-01T00:00:00.000Z"],
    )


class Data15(BaseModel):
    integrations: list[IntegrationItem] | None = None


class IntegrationListResponse(BaseModel):
    data: Data15 | None = None


class Data16(BaseModel):
    integration: IntegrationItem | None = None


class IntegrationResponse(BaseModel):
    data: Data16 | None = None


class TaskMetadata(BaseModel):
    id: UUID = Field(..., description="Unique identifier for the task")
    name: str = Field(..., description="Task name", max_length=255, min_length=1, pattern="^[a-zA-Z0-9_-]+$")
    team_id: UUID = Field(..., alias="teamId", description="Team identifier that owns this task")
    description: str | None = Field(None, description="Optional description of the task", max_length=1000)
    latest: str = Field(..., description="Latest version identifier")
    deleted: bool = Field(..., description="Whether the task is soft deleted")
    created_at: AwareDatetime = Field(..., alias="createdAt", description="Task creation timestamp")
    updated_at: AwareDatetime = Field(..., alias="updatedAt", description="Task last update timestamp")


class TaskExecutionResult(BaseModel):
    id: UUID = Field(..., description="Unique identifier for the execution result")
    task_version_id: UUID = Field(..., alias="taskVersionId", description="Task version identifier")
    version: str = Field(..., description="Version that was executed")
    status: Literal["success", "failure", "timeout", "cancelled", "queued", "running"] = Field(
        ..., description="Execution status"
    )
    output: str | None = Field(None, description="Task execution output")
    error_message: str | None = Field(None, alias="errorMessage", description="Error message if execution failed")
    start_time: AwareDatetime = Field(..., alias="startTime", description="Execution start time")
    execution_time: float | None = Field(None, alias="executionTime", description="Execution duration in milliseconds")


class UpdateTaskMetadataRequest(BaseModel):
    name: str | None = Field(
        None,
        description="Task name (letters, numbers, hyphens, and underscores only)",
        max_length=255,
        min_length=1,
        pattern="^[a-zA-Z0-9_-]+$",
    )
    description: str | None = Field(None, description="Optional description of the task", max_length=1000)


class RunTaskV2Request(BaseModel):
    input_params: dict[str, str] = Field(..., description="Key-value pairs of input parameters for the task")
    identity_id: str | None = Field(None, description="Optional identity ID to use for the task")
    session_id: str | None = Field(None, description="Optional session ID to run the task in")
    cleanup_sessions: bool | None = Field(
        True, description="Whether to clean up sessions after execution (default: true)"
    )


class TaskRunStatusV2Response(BaseModel):
    run_id: str = Field(..., description="The ID of the task run")
    status: Literal["queued", "running", "success", "failure", "timeout", "cancelled"] = Field(
        ..., description="Current task run status"
    )
    result: dict[str, Any] | None = Field(None, description="Task output when available")
    error: str | None = Field(None, description="Error message when the run fails")
    session_id: str | None = Field(None, description="Session ID used for this task run")


class TaskParameterV2(BaseModel):
    name: str = Field(..., description="The field name/key")
    type: Literal["string", "number", "boolean", "secret", "file"] = Field(
        ..., description="Data type of the parameter"
    )
    required: bool | None = Field(True, description="Whether the parameter is required")
    description: str | None = Field(None, description="Description of the parameter")
    default_value: Any | None = Field(
        None, alias="defaultValue", description="Default value of the parameter, used when not provided"
    )
    options: list[str] | None = Field(None, description="Allowed values for the parameter, if constrained")


class GenerateTaskV2Request(BaseModel):
    task_name: str = Field(..., alias="taskName", description="Name of the task")
    task_prompt: str = Field(
        ...,
        alias="taskPrompt",
        description="Natural-language description of what the task should do, used for AI generation. Make it as detailed as possible with all the logic and steps needed to complete the task.",
    )
    async_: bool | None = Field(True, alias="async", description="Whether to generate the task asynchronously")
    description: str | None = Field(None, description="Description of the task")
    application_id: UUID | None = Field(
        None, description="Optional application (connection) ID to associate with the task"
    )
    identity_id: str | None = Field(None, description="Optional identity ID to use during task generation")
    input_schema: list[TaskParameterV2] | None = Field(
        [], description="Input parameters the task accepts", validate_default=True
    )
    output_schema: list[TaskParameterV2] | None = Field(
        [], description="Output fields the task produces", validate_default=True
    )
    output_file_only: bool | None = Field(
        False, description="Whether task runs should return only the bundled session downloads file"
    )
    human_intervention: bool | None = Field(False, description="Allow human intervention during task execution")
    browser_session_id: str | None = Field(
        None, description="Existing finished browser session id to generate the workflow from"
    )
    task_browser_default_configuration: dict[str, Any] | None = Field(
        None, description="Optional default browser/session configuration when running this task"
    )


class GenerateTaskV2Response(BaseModel):
    id: str = Field(..., description="The ID of the created task (use with generation-status and run endpoints)")
    status: Literal["generating"] = Field(
        ..., description="Whether the task is still generating, ready to run, or failed"
    )
    task_id: str | None = Field(None, alias="taskId", description="The ID of the task being generated")
    task_version_id: str | None = Field(
        None, alias="taskVersionId", description="The ID of the task version being generated"
    )
    project_id: str | None = Field(None, alias="projectId", description="The ID of the underlying generation project")


class TaskGenerationStatusV2Response(BaseModel):
    id: str = Field(..., description="Identifier of the generation request")
    status: Literal["generating", "ready", "failed", "waiting-for-session"] = Field(
        ..., description="Current task generation status"
    )
    project_state: str | None = Field(None, description="Internal state of the generation project")
    error: str | None = Field(None, description="Error message when generation failed")


class TaskMetadataResponse(BaseModel):
    data: TaskMetadata | None = None


class Version(BaseModel):
    version: str = Field(..., description="Version identifier")
    description: str | None = Field(None, description="Version description")
    created_at: AwareDatetime = Field(..., alias="createdAt", description="Version creation timestamp")
    updated_at: AwareDatetime = Field(..., alias="updatedAt", description="Version last update timestamp")


class Data18(BaseModel):
    task_id: UUID = Field(..., alias="taskId", description="Task identifier")
    versions: list[Version]


class TaskVersionsListResponse(BaseModel):
    data: Data18 | None = None


class Pagination1(BaseModel):
    page: int = Field(..., description="Current page number", ge=1)
    limit: int = Field(..., description="Number of results per page", ge=1)
    total: int = Field(..., description="Total number of results", ge=0)
    total_pages: int = Field(..., alias="totalPages", description="Total number of pages", ge=0)


class Data19(BaseModel):
    results: list[TaskExecutionResult]
    pagination: Pagination1


class TaskExecutionResultsListResponse(BaseModel):
    data: Data19 | None = None


class TaskExecutionResultResponse(BaseModel):
    data: TaskExecutionResult | None = None


class Data20(BaseModel):
    success: bool = Field(..., description="Whether the task executed successfully")
    async_: bool = Field(..., alias="async", description="Whether the task was executed asynchronously")
    message: str = Field(..., description="Execution result message")
    task_id: UUID = Field(..., alias="taskId", description="Task identifier")
    execution_time: float | None = Field(
        None, alias="executionTime", description="Execution duration in milliseconds (only present in sync mode)"
    )
    output: str | None = Field(None, description="Task execution output (only present in sync mode)")
    error: str | None = Field(None, description="Error message if execution failed (only present in sync mode)")
    execution_result_id: UUID | None = Field(
        None,
        alias="executionResultId",
        description="Execution result identifier for tracking and polling (present in async mode)",
    )


class RunTaskResponse(BaseModel):
    data: Data20 | None = None


class Data21(BaseModel):
    success: bool = Field(..., description="Whether the deletion was successful")
    message: str = Field(..., description="Deletion result message")


class DeleteTaskResponse(BaseModel):
    data: Data21 | None = None


class ApplicationItem(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the application")
    name: str | None = Field(None, description="Name of the application")
    url: str | None = Field(None, description="URL of the application")
    description: str | None = Field(None, description="Description of the application")
    identity_count: int | None = Field(None, description="Number of identities associated with this application")
    auth_methods: list[str] | None = Field(None, description="Authentication methods available for this application")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the application was created")
    updated_at: AwareDatetime | None = Field(None, description="Timestamp when the application was last updated")


class CreateApplicationRequest(BaseModel):
    source: AnyUrl = Field(..., description="The source URL of the application")
    name: str | None = Field(None, description="Name of the application")
    description: str | None = Field(None, description="Description of the application")


class CreateApplicationResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the application")
    name: str | None = Field(None, description="Name of the application")
    url: str | None = Field(None, description="URL of the application")
    description: str | None = Field(None, description="Description of the application")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the application was created")


class ListApplicationsResponse(BaseModel):
    applications: list[ApplicationItem] | None = None


class GetApplicationResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the application")
    name: str | None = Field(None, description="Name of the application")
    url: str | None = Field(None, description="URL of the application")
    description: str | None = Field(None, description="Description of the application")
    identity_count: int | None = Field(None, description="Number of identities associated with this application")
    auth_methods: list[str] | None = Field(None, description="Authentication methods available for this application")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the application was created")
    updated_at: AwareDatetime | None = Field(None, description="Timestamp when the application was last updated")


class UpdateApplicationRequest(BaseModel):
    allowed_domains: list[str] | None = Field(None, description="List of allowed domains for this application")


class UpdateApplicationResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the application")
    url: str | None = Field(None, description="URL of the application")


class DeleteApplicationResponse(BaseModel):
    success: bool | None = Field(None, description="Whether the deletion was successful")


class ApplicationIdentityItem(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the identity")
    name: str | None = Field(None, description="Name of the identity")
    auth_flow: str | None = Field(None, description="Authentication flow associated with this identity")
    status: Literal["pending", "validated", "failed"] | None = Field(None, description="Status of the identity")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the identity was created")
    updated_at: AwareDatetime | None = Field(None, description="Timestamp when the identity was last updated")


class ListApplicationIdentitiesResponse(BaseModel):
    identities: list[ApplicationIdentityItem] | None = None


class CustomFieldDefinition(BaseModel):
    name: str = Field(..., description="Name of the custom field")


class AuthFlowItem(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the authentication flow")
    name: str | None = Field(None, description="Name of the authentication flow")
    description: str | None = Field(None, description="Description of the authentication flow")
    is_recommended: bool | None = Field(None, description="Whether this is the recommended authentication flow")
    methods: list[str] | None = Field(None, description="Authentication methods in this flow")
    custom_fields: list[CustomFieldDefinition] | None = Field(
        None, description="Custom fields for this authentication flow"
    )
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the authentication flow was created")
    updated_at: AwareDatetime | None = Field(
        None, description="Timestamp when the authentication flow was last updated"
    )


class ListApplicationAuthFlowsResponse(BaseModel):
    auth_flows: list[AuthFlowItem] | None = None


class CreateAuthFlowRequest(BaseModel):
    name: str = Field(..., description="Name of the authentication flow")
    description: str | None = Field(None, description="Description of the authentication flow")
    is_recommended: bool | None = Field(None, description="Whether this is the recommended authentication flow")
    methods: list[Literal["username_password", "authenticator", "custom"]] = Field(
        ..., description="Authentication methods in this flow", min_length=1
    )
    custom_fields: list[CustomFieldDefinition] | None = Field(
        None, description="Custom fields for this authentication flow"
    )


class CreateAuthFlowResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the authentication flow")
    name: str | None = Field(None, description="Name of the authentication flow")
    description: str | None = Field(None, description="Description of the authentication flow")
    is_recommended: bool | None = Field(None, description="Whether this is the recommended authentication flow")
    methods: list[str] | None = Field(None, description="Authentication methods in this flow")
    custom_fields: list[CustomFieldDefinition] | None = Field(
        None, description="Custom fields for this authentication flow"
    )
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the authentication flow was created")
    updated_at: AwareDatetime | None = Field(
        None, description="Timestamp when the authentication flow was last updated"
    )


class UpdateAuthFlowRequest(BaseModel):
    name: str | None = Field(None, description="Name of the authentication flow")
    description: str | None = Field(None, description="Description of the authentication flow")
    is_recommended: bool | None = Field(None, description="Whether this is the recommended authentication flow")
    methods: list[Literal["username_password", "authenticator", "custom"]] | None = Field(
        None, description="Authentication methods in this flow"
    )
    custom_fields: list[CustomFieldDefinition] | None = Field(
        None, description="Custom fields for this authentication flow"
    )


class UpdateAuthFlowResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the authentication flow")
    name: str | None = Field(None, description="Name of the authentication flow")
    description: str | None = Field(None, description="Description of the authentication flow")
    is_recommended: bool | None = Field(None, description="Whether this is the recommended authentication flow")
    methods: list[str] | None = Field(None, description="Authentication methods in this flow")
    custom_fields: list[CustomFieldDefinition] | None = Field(
        None, description="Custom fields for this authentication flow"
    )
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the authentication flow was created")
    updated_at: AwareDatetime | None = Field(
        None, description="Timestamp when the authentication flow was last updated"
    )


class DeleteAuthFlowResponse(BaseModel):
    success: bool | None = Field(None, description="Whether the deletion was successful")


class UsernamePasswordCredential(BaseModel):
    type: Literal["username_password"] = Field(..., description="Credential type")
    username: str = Field(..., description="Username for authentication")
    password: str = Field(..., description="Password for authentication")


class AuthenticatorCredential(BaseModel):
    type: Literal["authenticator"] = Field(..., description="Credential type")
    secret: str = Field(..., description="TOTP secret for authenticator")
    otp: str | None = Field(None, description="Optional OTP code")


class CustomFieldItem(BaseModel):
    name: str = Field(..., description="Field name")
    value: str = Field(..., description="Field value")


class CustomCredential(BaseModel):
    type: Literal["custom"] = Field(..., description="Credential type")
    fields: list[CustomFieldItem] = Field(..., description="Array of custom fields")


class CredentialData(RootModel[UsernamePasswordCredential | AuthenticatorCredential | CustomCredential]):
    root: UsernamePasswordCredential | AuthenticatorCredential | CustomCredential = Field(..., discriminator="type")


class CreateIdentityRequest(BaseModel):
    name: str | None = Field(None, description='Name of the identity. Defaults to "Unnamed Identity" if not provided.')
    source: AnyUrl = Field(..., description="The source URL for the identity (e.g., login page URL)")
    credentials: list[CredentialData] | None = Field(
        None,
        description="Optional credentials to associate with this identity (for example username/password\nor authenticator secrets). Omit this field or supply an empty array when you only\nneed an identity for the given source URL and optional metadata.\n",
    )
    metadata: dict[str, Any] | None = Field(None, description="Optional metadata for the identity")
    application_name: str | None = Field(
        None, alias="applicationName", description="Optional application name to associate with the identity"
    )
    application_description: str | None = Field(
        None, alias="applicationDescription", description="Optional application description"
    )


class CreateIdentityResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the identity")
    name: str | None = Field(None, description="Name of the identity")
    status: Literal["pending", "validated", "failed"] | None = Field(None, description="Status of the identity")
    metadata: dict[str, Any] | None = Field(None, description="Metadata associated with the identity")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the identity was created")


class GetIdentityResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the identity")
    name: str | None = Field(None, description="Name of the identity")
    source: str | None = Field(None, description="Source URL for the identity")
    status: Literal["pending", "validated", "failed"] | None = Field(None, description="Status of the identity")
    metadata: dict[str, Any] | None = Field(None, description="Metadata associated with the identity")
    created_at: AwareDatetime | None = Field(None, description="Timestamp when the identity was created")
    updated_at: AwareDatetime | None = Field(None, description="Timestamp when the identity was last updated")


class UpdateIdentityRequest(BaseModel):
    name: str | None = Field(None, description="Name of the identity")
    metadata: dict[str, Any] | None = Field(None, description="Metadata for the identity")
    credentials: list[CredentialData] | None = Field(None, description="Array of credentials for authentication")


class UpdateIdentityResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the identity")
    name: str | None = Field(None, description="Name of the identity")
    metadata: dict[str, Any] | None = Field(None, description="Metadata associated with the identity")
    updated_at: AwareDatetime | None = Field(None, description="Timestamp when the identity was last updated")


class DeleteIdentityResponse(BaseModel):
    message: str | None = Field(None, description="Deletion result message")


class GetIdentityCredentialsResponse(BaseModel):
    id: UUID | None = Field(None, description="Unique identifier for the identity")
    name: str | None = Field(None, description="Name of the identity")
    source: str | None = Field(None, description="Source URL for the identity")
    credentials: list[CredentialData] | None = Field(None, description="Array of credentials with sensitive data")


class CreateIdentityTokenRequest(BaseModel):
    callback_url: AnyUrl = Field(
        ...,
        alias="callbackUrl",
        description="The HTTPS URL where the user will be redirected after authentication. Must use HTTPS protocol.",
        examples=["https://example.com/callback"],
    )


class IdentityTokenResponse(BaseModel):
    token: str = Field(..., description="The generated identity token for authentication")
    expires_at: AwareDatetime = Field(..., alias="expiresAt", description="The timestamp when the token expires")
    token_hash: str = Field(..., alias="tokenHash", description="A hash of the token for verification purposes")


class WebhookEventType(
    RootModel[
        Literal[
            "task.completed",
            "task.failed",
            "task.cancelled",
            "task.healed",
            "session.completed",
            "session.failed",
            "session.recording.ready",
            "batch.completed",
            "batch.failed",
            "intervention.requested",
            "intervention.resolved",
            "identity.authenticated",
            "identity.authentication_failed",
        ]
    ]
):
    root: Literal[
        "task.completed",
        "task.failed",
        "task.cancelled",
        "task.healed",
        "session.completed",
        "session.failed",
        "session.recording.ready",
        "batch.completed",
        "batch.failed",
        "intervention.requested",
        "intervention.resolved",
        "identity.authenticated",
        "identity.authentication_failed",
    ] = Field(
        ...,
        description="Catalog of webhook event types Anchor can deliver. Adding a new event\ntype is a coordinated change between session-manager (publisher),\nwebhook-dispatcher (consumer), and the dashboard.\n",
    )


class WebhookPublic(BaseModel):
    id: str = Field(
        ...,
        description="Webhook id. Use as the path parameter on subsequent calls.",
        examples=["wh_01HXJ4MZ7K9P3Q6R8S2T4V5W7Y"],
    )
    project_id: UUID = Field(
        ..., description="The project (team) the webhook belongs to.", examples=["5d2c31f6-ab7e-481a-b6fd-8b4a96a4e197"]
    )
    url: AnyUrl = Field(
        ...,
        description="HTTPS URL Anchor will POST events to.",
        examples=["https://your-app.example.com/anchor/webhooks"],
    )
    description: str = Field(
        ...,
        description="Optional human-readable description.",
        examples=["Production task notifications"],
        max_length=256,
    )
    subscribed_events: list[WebhookEventType] = Field(
        ..., description="Event types this webhook is currently subscribed to."
    )
    enabled: bool = Field(..., description="When `false`, no events fan out to this webhook.", examples=[True])
    created_at: AwareDatetime
    updated_at: AwareDatetime


class WebhookWithSecret(WebhookPublic):
    secret: str = Field(
        ...,
        description="HMAC-SHA256 signing secret. Use this to verify the `Anchor-Signature` header on each delivery.",
        examples=["36da51b166a69268a59a8d5ee0b32c9f5e5aaee7d301c7a5a36844318e116fc6"],
    )


class WebhookCreateRequest(BaseModel):
    url: AnyUrl = Field(
        ...,
        description="HTTPS endpoint Anchor will POST events to. Rejected (400) if it points at\nloopback / private / link-local IPs, cloud metadata services, internal-only\nTLDs, AWS STS / IAM / EKS endpoints, or contains basic-auth credentials.\n",
        examples=["https://your-app.example.com/anchor/webhooks"],
    )
    description: str | None = Field(
        None,
        description="Optional human-readable description.",
        examples=["Production task notifications"],
        max_length=256,
    )
    subscribed_events: list[WebhookEventType] = Field(
        ..., description="Events this webhook should receive. At least one is required.", min_length=1
    )


class WebhookUpdateRequest(BaseModel):
    url: AnyUrl | None = None
    description: str | None = Field(None, max_length=256)
    subscribed_events: list[WebhookEventType] | None = Field(None, min_length=1)
    enabled: bool | None = None


class WebhookListResponse(BaseModel):
    webhooks: list[WebhookPublic]


class WebhookTestRequest(BaseModel):
    event_type: WebhookEventType


class WebhookTestResponse(BaseModel):
    external_event_id: str = Field(
        ...,
        description="The synthetic event id that will appear on the receiver as `id` in the envelope.",
        examples=["evt_56a4c6e7f11e4b44eafce28a"],
    )
    event_type: WebhookEventType


class WebhookEventDeliveryRow(BaseModel):
    id: str = Field(..., description="Internal events-row id (one row per logical delivery to one webhook).")
    external_event_id: str = Field(
        ...,
        description="Customer-facing event id. Same value lands in the envelope `id` field.",
        examples=["evt_56a4c6e7f11e4b44eafce28a"],
    )
    event_type: WebhookEventType
    status: Literal["pending", "in_flight", "succeeded", "failed", "dead"] = Field(
        ...,
        description="* `pending` — accepted, no attempt yet.\n* `in_flight` — currently being POSTed.\n* `succeeded` — receiver returned 2xx.\n* `failed` — receiver returned non-retryable 4xx.\n* `dead` — exhausted all retry attempts.\n",
    )
    attempt: int = Field(
        ..., description="Attempt number for the most recent try (1 = first attempt, ≤ 6 with default policy).", ge=0
    )
    response_status: int | None = Field(None, description="HTTP status code from the most recent attempt, if any.")
    error_message: str | None = None
    scheduled_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class Pagination2(BaseModel):
    limit: int = Field(..., description="Number of rows in this response (max 100).")
    offset: int = Field(..., description="How many rows were skipped from the beginning of the result set.")
    total: int = Field(..., description="Total matching rows across all pages.")


class WebhookEventsListResponse(BaseModel):
    events: list[WebhookEventDeliveryRow]
    pagination: Pagination2


class WebhookDeleteResponse(BaseModel):
    ok: bool = Field(..., examples=[True])


class Data22(BaseModel):
    session_id: str | None = Field(None, description="The unique identifier of the session.")
    team_id: str | None = Field(None, description="The team ID associated with the session.")
    duration: int | None = Field(None, description="The duration of the session in seconds.")
    status: str | None = Field(None, description="The current status of the session.")
    credits_used: float | None = Field(None, description="The number of credits consumed by the session.")
    configuration: dict[str, Any] | None = Field(None, description="The configuration settings for the session.")
    playground: bool | None = Field(None, description="Whether this is a playground session.")
    proxy_bytes: int | None = Field(None, description="The number of bytes transferred through the proxy.")
    tokens: dict[str, Any] | None = Field(None, description="Token usage information.")
    steps: int | None = Field(None, description="Number of AI agent steps executed in the session.")
    tags: dict[str, Any] | None = Field(None, description="Tags associated with the session.")
    created_at: AwareDatetime | None = Field(None, description="The timestamp when the session was created.")


class SessionsGetSessionResponse(BaseModel):
    data: Data22 | None = Field(None, description="The session data.")


class Item(BaseModel):
    id: str = Field(..., description="The unique identifier of the page.")
    title: str = Field(..., description="The title of the page.")
    url: str = Field(..., description="The URL of the page.")
    frontend_url: str = Field(..., description="The frontend URL for accessing the page.")


class Data23(BaseModel):
    count: float = Field(..., description="The number of pages returned.")
    items: list[Item]


class SessionsGetSessionPagesResponse(BaseModel):
    data: Data23


class Data24(BaseModel):
    status: str | None = None
    message: str | None = None


class SessionsUploadFileResponse(BaseModel):
    data: Data24 | None = None


class SessionsMouseClickResponse(BaseModel):
    status: str | None = None


class SessionsMouseDoubleClickResponse(BaseModel):
    status: str | None = None


class SessionsMouseDownResponse(BaseModel):
    status: str | None = None


class SessionsMouseUpResponse(BaseModel):
    status: str | None = None


class SessionsMouseMoveResponse(BaseModel):
    status: str | None = None


class SessionsDragAndDropResponse(BaseModel):
    status: str | None = None


class SessionsScrollResponse(BaseModel):
    status: str | None = None


class SessionsKeyboardTypeResponse(BaseModel):
    status: str | None = None


class SessionsKeyboardShortcutResponse(BaseModel):
    status: str | None = None


class SessionsSetClipboardResponse(BaseModel):
    status: str | None = None


class SessionsPasteResponse(BaseModel):
    status: str | None = None


class SessionsGotoResponse(BaseModel):
    status: str | None = None


class RecordingsPauseRecordingResponse(BaseModel):
    data: SuccessResponse | None = None


class RecordingsResumeRecordingResponse(BaseModel):
    data: SuccessResponse | None = None


class AgentUploadAgentFilesResponse(BaseModel):
    data: Data24 | None = None


class File(BaseModel):
    name: str | None = Field(None, description="The resource name")
    size: int | None = Field(None, description="Resource size in bytes")
    type: str | None = Field(None, description="Resource extension/type")
    last_modified: AwareDatetime | None = Field(
        None, alias="lastModified", description="When the resource was last modified"
    )


class Data26(BaseModel):
    files: list[File] | None = None


class AgentListAgentFilesResponse(BaseModel):
    data: Data26 | None = None


class ExtensionsUploadExtensionResponse(BaseModel):
    data: ExtensionResponseSchema | None = None


class ExtensionsDeleteExtensionResponse(BaseModel):
    data: SuccessResponse | None = None


class Integration1(BaseModel):
    id: UUID | None = None
    deleted: bool | None = None
    path: str | None = None


class Data27(BaseModel):
    integration: Integration1 | None = None


class IntegrationsDeleteIntegrationResponse(BaseModel):
    data: Data27 | None = None


class BatchSessionsListBatchSessionsResponse(BaseModel):
    data: BatchSessionListResponseSchema | None = None


class BatchSessionsCreateBatchSessionResponse(BaseModel):
    data: BatchSessionResponseSchema | None = None


class BatchSessionsGetBatchSessionResponse(BaseModel):
    data: BatchSessionStatusResponseSchema | None = None


class BatchSessionsUpdateBatchSessionResponse(BaseModel):
    data: BatchSessionUpdateResponseSchema | None = None


class BatchSessionsDeleteBatchSessionResponse(BaseModel):
    data: BatchSessionDeleteResponseSchema | None = None


class BatchSessionsRetryBatchSessionResponse(BaseModel):
    data: BatchSessionRetryResponseSchema | None = None


class AnchorProxy(BaseModel):
    active: bool
    type: Literal["anchor_proxy"] | None = Field(
        None,
        description="Create a session with a proxy to access websites as if you're browsing from a computer in that country.",
        title="anchor_proxy",
    )
    country_code: AnchorProxyCountryCode | None = Field(
        "us", description="Supported country codes ISO 2 lowercase\n", validate_default=True
    )
    region: str | None = Field(
        None,
        description="Region code for more specific geographic targeting.\nThe city parameter can only be used when region is also provided.\n",
    )
    city: str | None = Field(
        None,
        description="City name for precise geographic targeting. Supported for anchor_proxy only.\nCan only be used when region is also provided.\n",
    )


class Data4(BaseModel):
    request_id: UUID = Field(..., description="The `request_id` returned from `POST /v1/sessions/async`.")
    status: Literal["pending", "processing", "ready", "completed", "failed", "cancelled"] = Field(
        ...,
        description="Lifecycle of the async request itself. `ready` is surfaced once\nthe underlying browser pod is up and the session is connectable.\n",
    )
    created_at: AwareDatetime = Field(..., description="When the async request was accepted.")
    session: BatchSessionItemSchema | None = Field(
        None,
        description="The single browser session backing this async request.\nAbsent until the underlying pod registers and the session row\nis inserted.\n",
    )
    progress: Progress


class AsyncSessionStatusResponseSchema(BaseModel):
    data: Data4 | None = None


class ProxyConfig(RootModel[AnchorProxy | CustomProxy]):
    root: AnchorProxy | CustomProxy = Field(
        ..., description="Proxy Documentation available at [Proxy Documentation](/advanced/proxy)\n"
    )


class SessionConfig(BaseModel):
    initial_url: AnyUrl | None = Field(
        None,
        description="The URL to navigate to when the browser session starts. If not provided, the browser will load an empty page.",
    )
    tags: list[str] | None = Field(
        None,
        description="Custom labels to categorize and identify browser sessions. Useful for filtering, organizing, and tracking sessions across your workflows.",
        examples=[["production", "scraping", "customer-123"]],
    )
    recording: Recording | None = Field(None, description="Configuration for session recording.")
    proxy: ProxyConfig | None = None
    timeout: Timeout | None = Field(None, description="Timeout configurations for the browser session.")
    live_view: LiveView | None = Field(None, description="Configuration for live viewing the browser session.")
    x402: bool | None = Field(
        False,
        description="Allow this browser session to automatically pay x402-protected resources using Amazon Bedrock AgentCore Payments.",
    )


class SessionCreateRequestSchema(BaseModel):
    session: SessionConfig | None = None
    browser: BrowserConfig | None = None
    integrations: list[Integration] | None = Field(
        None,
        description="Array of integrations to load in the browser session. Integrations must be previously created using the Integrations API.",
        examples=[
            [{"id": "550e8400-e29b-41d4-a716-446655440000", "type": "1PASSWORD", "configuration": {"load_mode": "all"}}]
        ],
    )
    identities: list[Identity] | None = Field(
        None,
        description="Activates an authenticated session.\n",
        examples=[[{"id": "123e4567-e89b-12d3-a456-426614174000"}]],
    )


class BatchSessionRequestSchema(BaseModel):
    count: int = Field(..., description="Number of sessions to create in the batch (1-1000)", ge=1, le=1000)
    configuration: SessionCreateRequestSchema | None = Field(
        None, description="Configuration that applies to all sessions in the batch"
    )
    metadata: dict[str, Any] | None = Field(
        None, description="Optional batch-level metadata for identification and organization"
    )


class Task(BaseModel):
    id: UUID = Field(..., description="Unique identifier for the task")
    name: str = Field(
        ...,
        description="Task name (letters, numbers, hyphens, and underscores only)",
        max_length=255,
        min_length=1,
        pattern="^[a-zA-Z0-9_-]+$",
    )
    team_id: UUID = Field(..., alias="teamId", description="Team identifier that owns this task")
    description: str | None = Field(None, description="Optional description of the task", max_length=1000)
    latest_version: str = Field(
        ..., alias="latestVersion", description="Latest version identifier (draft, latest, or version number)"
    )
    code: str = Field(..., description="Base64 encoded task code")
    language: Literal["typescript"] = Field(..., description="Programming language for the task")
    browser_configuration: SessionConfig | None = Field(
        None, alias="browserConfiguration", description="Browser configuration for task execution"
    )
    deleted: bool = Field(..., description="Whether the task is soft deleted")
    created_at: AwareDatetime = Field(..., alias="createdAt", description="Task creation timestamp")
    updated_at: AwareDatetime = Field(..., alias="updatedAt", description="Task last update timestamp")


class TaskVersion(BaseModel):
    id: UUID = Field(..., description="Unique identifier for the task version")
    task_id: UUID = Field(..., alias="taskId", description="Parent task identifier")
    version: str = Field(..., description="Version identifier (draft, latest, or version number)")
    code: str = Field(..., description="Base64 encoded task code")
    language: Literal["typescript"] | None = Field(None, description="Programming language for the task")
    description: str | None = Field(None, description="Optional description of the version", max_length=1000)
    browser_configuration: SessionConfig | None = Field(
        None, alias="browserConfiguration", description="Browser configuration for task execution"
    )
    deleted: bool = Field(..., description="Whether the version is soft deleted")
    created_at: AwareDatetime = Field(..., alias="createdAt", description="Version creation timestamp")
    updated_at: AwareDatetime = Field(..., alias="updatedAt", description="Version last update timestamp")


class CreateTaskRequest(BaseModel):
    name: str = Field(
        ...,
        description="Task name (letters, numbers, hyphens, and underscores only)",
        max_length=255,
        min_length=1,
        pattern="^[a-zA-Z0-9_-]+$",
    )
    code: str | None = Field(None, description="Base64 encoded task code (optional)", pattern="^[A-Za-z0-9+/]*={0,2}$")
    language: Literal["typescript"] = Field(..., description="Programming language for the task")
    description: str | None = Field(None, description="Optional description of the task", max_length=1000)
    browser_configuration: SessionConfig | None = Field(
        None, alias="browserConfiguration", description="Browser configuration for task execution"
    )


class DraftTaskRequest(BaseModel):
    code: str = Field(..., description="Base64 encoded task code", min_length=1, pattern="^[A-Za-z0-9+/]*={0,2}$")
    language: Literal["typescript"] | None = Field(None, description="Programming language for the task")
    description: str | None = Field(None, description="Optional description of the version", max_length=1000)
    browser_configuration: SessionConfig | None = Field(
        None, alias="browserConfiguration", description="Browser configuration for task execution"
    )


class PublishVersionRequest(BaseModel):
    code: str | None = Field(
        None,
        description="Base64 encoded task code (required for new versions)",
        min_length=1,
        pattern="^[A-Za-z0-9+/]*={0,2}$",
    )
    language: Literal["typescript"] | None = Field(None, description="Programming language for the task")
    description: str | None = Field(None, description="Optional description of the version", max_length=1000)
    browser_configuration: SessionConfig | None = Field(
        None, alias="browserConfiguration", description="Browser configuration for task execution"
    )


class RunTaskRequest(BaseModel):
    task_id: UUID = Field(..., alias="taskId", description="Task identifier")
    version: str | None = Field(
        None, description="Version to run (draft, latest, or version number)", pattern="^(draft|latest|\\d+)$"
    )
    session_id: UUID | None = Field(
        None, alias="sessionId", description="Optional existing browser session ID to use for task execution"
    )
    async_: bool | None = Field(None, alias="async", description="Whether to run the task asynchronously.")
    override_browser_configuration: SessionConfig | None = Field(
        None, alias="overrideBrowserConfiguration", description="Override browser configuration for this execution"
    )
    inputs: dict[constr(pattern=r"^ANCHOR_.*$"), str] | None = Field(
        None, description="Environment variables for task execution (keys must start with ANCHOR_)"
    )
    cleanup_sessions: bool | None = Field(
        True,
        alias="cleanupSessions",
        description="Whether to cleanup browser sessions after task execution. Defaults to true.",
    )


class RunTaskByNameRequest(BaseModel):
    session_id: UUID | None = Field(
        None, alias="sessionId", description="Optional existing browser session ID to use for task execution"
    )
    async_: bool | None = Field(None, alias="async", description="Whether to run the task asynchronously")
    override_browser_configuration: SessionConfig | None = Field(
        None, alias="overrideBrowserConfiguration", description="Override browser configuration for this execution"
    )
    inputs: dict[constr(pattern=r"^ANCHOR_.*$"), str] | None = Field(
        None, description="Environment variables for task execution (keys must start with ANCHOR_)"
    )
    cleanup_sessions: bool | None = Field(
        True,
        alias="cleanupSessions",
        description="Whether to cleanup browser sessions after task execution. Defaults to true.",
    )


class Data17(BaseModel):
    tasks: list[Task]
    total: int = Field(..., description="Total number of tasks", ge=0)
    page: int = Field(..., description="Current page number", ge=1)
    limit: int = Field(..., description="Number of tasks per page", ge=1, le=100)


class TaskListResponse(BaseModel):
    data: Data17 | None = None


class TaskResponse(BaseModel):
    data: Task | None = None


class TaskVersionResponse(BaseModel):
    data: TaskVersion | None = None
