# Generated by scripts/generate from spec/openapi.yaml — do not edit.

from __future__ import annotations

from typing import Any, Literal, TypeAlias, TypedDict
from typing_extensions import NotRequired


class Data(TypedDict):
    status: NotRequired[str]


class SuccessResponse(TypedDict):
    data: NotRequired[Data]


class Error(TypedDict):
    code: NotRequired[int]
    message: NotRequired[str]


class ErrorResponse(TypedDict):
    error: NotRequired[Error]


class CustomProxy(TypedDict):
    type: Literal["custom"]
    server: str
    username: str
    password: str
    active: bool


AnchorProxyCountryCode: TypeAlias = Literal[
    "af",
    "al",
    "dz",
    "ad",
    "ao",
    "as",
    "ag",
    "ar",
    "am",
    "aw",
    "au",
    "at",
    "az",
    "bs",
    "bh",
    "bb",
    "by",
    "be",
    "bz",
    "bj",
    "bm",
    "bo",
    "ba",
    "br",
    "bg",
    "bf",
    "cm",
    "ca",
    "cv",
    "td",
    "cl",
    "co",
    "cg",
    "cr",
    "ci",
    "hr",
    "cu",
    "cy",
    "cz",
    "dk",
    "dm",
    "do",
    "ec",
    "eg",
    "sv",
    "ee",
    "et",
    "fo",
    "fi",
    "fr",
    "gf",
    "pf",
    "ga",
    "gm",
    "ge",
    "de",
    "gh",
    "gi",
    "gr",
    "gd",
    "gp",
    "gt",
    "gg",
    "gn",
    "gw",
    "gy",
    "ht",
    "hn",
    "hu",
    "is",
    "in",
    "ir",
    "iq",
    "ie",
    "il",
    "it",
    "jm",
    "jp",
    "jo",
    "kz",
    "kw",
    "kg",
    "lv",
    "lb",
    "ly",
    "li",
    "lt",
    "lu",
    "mk",
    "ml",
    "mt",
    "mq",
    "mr",
    "mx",
    "md",
    "mc",
    "me",
    "ma",
    "nl",
    "nz",
    "ni",
    "ng",
    False,
    "pk",
    "pa",
    "py",
    "pe",
    "ph",
    "pl",
    "pt",
    "pr",
    "qa",
    "ro",
    "lc",
    "sm",
    "sa",
    "sn",
    "rs",
    "sc",
    "sl",
    "sk",
    "si",
    "so",
    "za",
    "kr",
    "es",
    "sr",
    "se",
    "ch",
    "sy",
    "st",
    "tw",
    "tj",
    "tg",
    "tt",
    "tn",
    "tr",
    "tc",
    "ua",
    "ae",
    "us",
    "uy",
    "uz",
    "ve",
    "ye",
]


class ProfileRequestSchema(TypedDict):
    name: str
    description: NotRequired[str]
    source: NotRequired[Literal["session"]]
    session_id: NotRequired[str]
    dedicated_sticky_ip: NotRequired[bool]


class ProfileResponseSchema(TypedDict):
    name: NotRequired[str]
    description: NotRequired[str]
    source: NotRequired[Literal["session"]]
    session_id: NotRequired[str]
    status: NotRequired[str]
    created_at: NotRequired[str]


class Data1(TypedDict):
    count: NotRequired[int]
    items: NotRequired[list[ProfileResponseSchema]]


class ProfileListResponse(TypedDict):
    data: NotRequired[Data1]


class ProfileResponse(TypedDict):
    data: NotRequired[ProfileResponseSchema]


class Recording(TypedDict):
    active: NotRequired[bool]


class Timeout(TypedDict):
    max_duration: NotRequired[int]
    idle_timeout: NotRequired[int]


class LiveView(TypedDict):
    read_only: NotRequired[bool]
    one_time_url: NotRequired[bool]


class PutSessionTags(TypedDict):
    tags: list[str]


class SessionTagsResponse(TypedDict):
    tags: list[str]


class SessionTagsMutationResponse(TypedDict):
    success: bool
    message: NotRequired[str]


class Profile(TypedDict):
    name: NotRequired[str]
    persist: NotRequired[bool]


class Adblock(TypedDict):
    active: NotRequired[bool]


class PopupBlocker(TypedDict):
    active: NotRequired[bool]


class CaptchaSolver(TypedDict):
    active: NotRequired[bool]


class Headless(TypedDict):
    active: NotRequired[bool]


class Viewport(TypedDict):
    width: NotRequired[int]
    height: NotRequired[int]


class Fullscreen(TypedDict):
    active: NotRequired[bool]


class PdfViewer(TypedDict):
    active: NotRequired[bool]


class P2pDownload(TypedDict):
    active: NotRequired[bool]


class DisableWebSecurity(TypedDict):
    active: NotRequired[bool]


class ExtraStealth(TypedDict):
    active: NotRequired[bool]


class ForcePopupsAsTabs(TypedDict):
    active: NotRequired[bool]


class WebBotAuth(TypedDict):
    active: NotRequired[bool]


class DisableDialogs(TypedDict):
    active: NotRequired[bool]


class Tracing(TypedDict):
    active: NotRequired[bool]
    snapshots: NotRequired[bool]
    sources: NotRequired[bool]


class CustomPattern(TypedDict):
    regex: NotRequired[str]
    mask: NotRequired[str]


class SensitiveDataMask(TypedDict):
    active: NotRequired[bool]
    custom_selectors: NotRequired[list[str]]
    site_selectors: NotRequired[dict[str, list[str]]]
    custom_patterns: NotRequired[list[CustomPattern]]


class BrowserConfig(TypedDict):
    profile: NotRequired[Profile]
    adblock: NotRequired[Adblock]
    popup_blocker: NotRequired[PopupBlocker]
    captcha_solver: NotRequired[CaptchaSolver]
    headless: NotRequired[Headless]
    viewport: NotRequired[Viewport]
    fullscreen: NotRequired[Fullscreen]
    pdf_viewer: NotRequired[PdfViewer]
    p2p_download: NotRequired[P2pDownload]
    extensions: NotRequired[list[str]]
    disable_web_security: NotRequired[DisableWebSecurity]
    extra_stealth: NotRequired[ExtraStealth]
    force_popups_as_tabs: NotRequired[ForcePopupsAsTabs]
    web_bot_auth: NotRequired[WebBotAuth]
    disable_dialogs: NotRequired[DisableDialogs]
    tracing: NotRequired[Tracing]
    sensitive_data_mask: NotRequired[SensitiveDataMask]


class Identity(TypedDict):
    id: NotRequired[str]


class Data2(TypedDict):
    id: NotRequired[str]
    cdp_url: NotRequired[str]
    live_view_url: NotRequired[str]


class SessionCreateResponseSchema(TypedDict):
    data: NotRequired[Data2]


class Data3(TypedDict):
    request_id: str
    status: Literal["pending"]
    session_id: None


class AsyncSessionCreateResponseSchema(TypedDict):
    data: NotRequired[Data3]


class Progress(TypedDict):
    current_phase: Literal["queued", "provisioning", "configuring", "ready"]


class SessionStatus(TypedDict):
    session_id: str
    status: str
    tags: NotRequired[list[str]]
    created_at: str


class Data5(TypedDict):
    count: NotRequired[int]
    items: NotRequired[list[SessionStatus]]


class SessionListResponse(TypedDict):
    data: NotRequired[Data5]


UsedCredits: TypeAlias = str


class SessionHistoryPageItem(TypedDict):
    id: str
    status: str
    tags: NotRequired[list[str]]
    headless: bool
    recording: bool
    used_credits: float | UsedCredits | Literal["N/A"]
    proxy_bytes: NotRequired[float]
    proxy_type: NotRequired[str]
    steps: NotRequired[float]
    duration: NotRequired[float]
    created_at: str
    user_configuration: dict[str, Any]
    task_initiated: bool
    task_executions_count: float
    api_key_name: str
    browser_ip: str
    domains: NotRequired[list[str]]


class Data6(TypedDict):
    sessions: list[SessionHistoryPageItem]
    total: float
    page: float
    total_pages: float


class SessionHistoryPageResponse(TypedDict):
    data: NotRequired[Data6]


class SessionHistoryDataPoint(TypedDict):
    date: NotRequired[str]
    session_count: NotRequired[float]
    proxy_bytes: NotRequired[float]
    ai_steps: NotRequired[float]
    session_hours: NotRequired[float]
    credits_used: NotRequired[float]
    screenshots: NotRequired[float]
    network_bytes_total: NotRequired[float]


class SessionHistorySummary(TypedDict):
    total_sessions: NotRequired[float]
    total_proxy_bytes: NotRequired[float]
    total_ai_steps: NotRequired[float]
    total_session_hours: NotRequired[float]
    total_credits_used: NotRequired[float]
    total_screenshots: NotRequired[float]
    total_network_bytes_total: NotRequired[float]


class SessionHistoryPagination(TypedDict):
    current_page: NotRequired[int]
    total_pages: NotRequired[int]
    total_records: NotRequired[int]
    has_next: NotRequired[bool]
    has_prev: NotRequired[bool]


class SessionHistoryResponse(TypedDict):
    data: NotRequired[list[SessionHistoryDataPoint]]
    summary: NotRequired[SessionHistorySummary]
    pagination: NotRequired[SessionHistoryPagination]


class Data7(TypedDict):
    credits: float
    credits_used: float
    included_credits: float
    billing_period: str
    tier: str
    gifts_balance: NotRequired[float]
    max_concurrent_browsers: NotRequired[float]
    cost_limit: NotRequired[float]


class Datum(TypedDict):
    date: str
    credits_used: float


class Usage(TypedDict):
    from_date: str
    to_date: str
    granularity: Literal["hour", "day", "week", "month"]
    total_credits_used: float
    data: list[Datum]


class BillingInfoResponse(TypedDict):
    data: NotRequired[Data7]
    usage: NotRequired[Usage]


class RecordingItem(TypedDict):
    id: NotRequired[str]
    is_primary: NotRequired[bool]
    file_link: NotRequired[str]
    suggested_file_name: NotRequired[str]
    duration: NotRequired[str]
    size: NotRequired[float]
    created_at: NotRequired[str]


class Data8(TypedDict):
    count: NotRequired[int]
    items: NotRequired[list[RecordingItem]]


class RecordingListResponse(TypedDict):
    data: NotRequired[Data8]


class DownloadItem(TypedDict):
    id: NotRequired[str]
    file_link: NotRequired[str]
    original_download_url: NotRequired[str]
    origin_url: NotRequired[str]
    suggested_file_name: NotRequired[str]
    original_file_name: NotRequired[str]
    duration: NotRequired[int]
    size: NotRequired[int]
    created_at: NotRequired[str]


class Data9(TypedDict):
    count: NotRequired[int]
    items: NotRequired[list[DownloadItem]]


class DownloadListResponse(TypedDict):
    data: NotRequired[Data9]


class FetchWebpageRequestSchema(TypedDict):
    url: NotRequired[str]
    format: NotRequired[Literal["html", "markdown"]]
    wait: NotRequired[int]
    new_page: NotRequired[bool]
    page_index: NotRequired[int]
    return_partial_on_timeout: NotRequired[bool]


class WebUnlockerRequestSchema(TypedDict):
    url: str


class ExecuteCodeRequestSchema(TypedDict):
    code: str


class ExecuteCodeToolResponseSchema(TypedDict):
    success: bool
    message: str
    output: NotRequired[str]
    error: NotRequired[str]
    executionResultId: NotRequired[str]


PerformWebTaskRequestSchema = TypedDict(
    "PerformWebTaskRequestSchema",
    {
        "url": NotRequired[str],
        "prompt": str,
        "agent": NotRequired[Literal["browser-use", "openai-cua", "gemini-computer-use", "anthropic-cua", "yutori"]],
        "provider": NotRequired[Literal["openai", "gemini", "groq", "azure", "xai"]],
        "model": NotRequired[str],
        "detect_elements": NotRequired[bool],
        "human_intervention": NotRequired[bool],
        "max_steps": NotRequired[int],
        "llm_timeout": NotRequired[int],
        "secret_values": NotRequired[dict[str, str]],
        "highlight_elements": NotRequired[bool],
        "output_schema": NotRequired[dict[str, Any]],
        "async": NotRequired[bool],
    },
)


class PerformWebTaskSyncResponseData(TypedDict):
    result: dict[str, Any]


class PerformWebTaskAsyncResponseData(TypedDict):
    status: Literal["running"]
    workflow_id: str


class PerformWebTaskResponseSchema(TypedDict):
    data: NotRequired[PerformWebTaskSyncResponseData | PerformWebTaskAsyncResponseData]


class PerformWebTaskStatusSuccessResponseData(TypedDict):
    status: Literal["COMPLETED"]
    result: dict[str, Any]
    sessionId: NotRequired[str]


class PerformWebTaskStatusRunningResponseData(TypedDict):
    status: Literal["RUNNING"]
    sessionId: NotRequired[str]


class PerformWebTaskStatusFailedResponseData(TypedDict):
    status: Literal["FAILED"]
    error: str
    sessionId: NotRequired[str]


class PerformWebTaskStatusResponseSchema(TypedDict):
    data: (
        PerformWebTaskStatusSuccessResponseData
        | PerformWebTaskStatusRunningResponseData
        | PerformWebTaskStatusFailedResponseData
    )


class HumanInterventionField(TypedDict):
    name: str
    label: str
    description: NotRequired[str]
    required: NotRequired[bool]
    type: NotRequired[Literal["text", "number", "url", "email", "password"]]
    placeholder: NotRequired[str]
    defaultValue: NotRequired[str]


class HumanInterventionRequest(TypedDict):
    requestId: str
    message: str
    inputType: NotRequired[Literal["text", "confirm", "fields"]]
    fields: NotRequired[list[HumanInterventionField]]


class PendingInterventionItem(HumanInterventionRequest):
    sessionId: str
    tags: list[str]


class Data10(TypedDict):
    count: int
    items: list[PendingInterventionItem]


class PendingInterventionsResponse(TypedDict):
    data: Data10


class Data11(TypedDict):
    status: str
    message: NotRequired[str]
    requests: list[HumanInterventionRequest]


class HumanInterventionRequestsResponse(TypedDict):
    data: Data11


class HumanInterventionResponseRequest(TypedDict):
    requestId: NotRequired[str]
    response: str | bool | dict[str, Any]


class Data12(TypedDict):
    status: str
    message: NotRequired[str]


class HumanInterventionResponseResponse(TypedDict):
    data: Data12


class ScreenshotRequestSchema(TypedDict):
    url: NotRequired[str]
    width: NotRequired[int]
    height: NotRequired[int]
    image_quality: NotRequired[int]
    wait: NotRequired[int]
    scroll_all_content: NotRequired[bool]
    capture_full_height: NotRequired[bool]
    s3_target_address: NotRequired[str]


class CoordinatesRequestSchema(TypedDict):
    x: int
    y: int


class MouseClickRequestSchema(CoordinatesRequestSchema):
    button: NotRequired[Literal["left", "middle", "right"]]


class MouseSingleClickRequestSchema(TypedDict):
    x: NotRequired[float]
    y: NotRequired[float]
    button: NotRequired[Literal["left", "middle", "right"]]
    selector: NotRequired[str]
    timeout: NotRequired[float]
    index: NotRequired[float]


class DragDropRequestSchema(TypedDict):
    startX: int
    startY: int
    endX: int
    endY: int
    button: NotRequired[Literal["left", "middle", "right"]]


class ScrollRequestSchema(CoordinatesRequestSchema):
    deltaX: NotRequired[int]
    deltaY: int
    steps: NotRequired[int]
    useOs: NotRequired[bool]


class TypeTextRequestSchema(TypedDict):
    text: str
    delay: NotRequired[int]


class KeyboardShortcutRequestSchema(TypedDict):
    keys: list[str]
    holdTime: NotRequired[int]


class Data13(TypedDict):
    text: NotRequired[str]


class ClipboardResponseSchema(TypedDict):
    data: NotRequired[Data13]


class ClipboardRequestSchema(TypedDict):
    text: str


class CopyResponseSchema(TypedDict):
    text: NotRequired[str]


class PasteRequestSchema(TypedDict):
    text: str


class NavigateRequestSchema(TypedDict):
    url: str


class WaitForEventRequestSchema(TypedDict):
    timeoutMs: NotRequired[int]


class SignalEventRequestSchema(TypedDict):
    data: dict[str, Any]


class EventResponseSchema(TypedDict):
    data: NotRequired[dict[str, Any]]


class ExtensionManifest(TypedDict):
    name: NotRequired[str]
    version: NotRequired[str]
    manifest_version: NotRequired[int]
    description: NotRequired[str]
    permissions: NotRequired[list[str]]


class ExtensionResponseSchema(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    manifest: NotRequired[ExtensionManifest]
    createdAt: NotRequired[str]
    updatedAt: NotRequired[str]


class ExtensionListResponse(TypedDict):
    data: NotRequired[list[ExtensionResponseSchema]]


class ExtensionResponse(TypedDict):
    data: NotRequired[ExtensionResponseSchema]


class CertificateResponseSchema(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    createdAt: NotRequired[str]


class CertificateListResponse(TypedDict):
    data: NotRequired[list[CertificateResponseSchema]]


class CertificateResponse(TypedDict):
    data: NotRequired[CertificateResponseSchema]


class BatchSessionResponseSchema(TypedDict):
    batch_id: NotRequired[str]
    status: NotRequired[Literal["pending", "processing", "completed", "failed", "cancelled"]]
    total_requests: NotRequired[int]
    created_at: NotRequired[str]


class BatchSessionItemSchema(TypedDict):
    item_index: NotRequired[int]
    session_id: NotRequired[str]
    status: NotRequired[Literal["pending", "processing", "completed", "failed", "cancelled"]]
    cdp_url: NotRequired[str]
    live_view_url: NotRequired[str]
    error: NotRequired[str]
    retry_count: NotRequired[int]
    started_at: NotRequired[str]
    completed_at: NotRequired[str]
    metadata: NotRequired[dict[str, Any]]


class Progress1(TypedDict):
    percentage: NotRequired[float]
    current_phase: NotRequired[Literal["queued", "provisioning", "configuring", "ready"]]


class BatchSessionStatusResponseSchema(TypedDict):
    batch_id: NotRequired[str]
    status: NotRequired[Literal["pending", "processing", "completed", "failed", "cancelled"]]
    total_requests: NotRequired[int]
    completed_requests: NotRequired[int]
    failed_requests: NotRequired[int]
    processing_requests: NotRequired[int]
    pending_requests: NotRequired[int]
    created_at: NotRequired[str]
    actual_completion_time: NotRequired[str]
    error: NotRequired[str]
    sessions: NotRequired[list[BatchSessionItemSchema]]
    progress: NotRequired[Progress1]


class BatchSessionListItemSchema(TypedDict):
    batch_id: NotRequired[str]
    status: NotRequired[Literal["pending", "processing", "completed", "failed", "cancelled"]]
    total_requests: NotRequired[int]
    completed_requests: NotRequired[int]
    failed_requests: NotRequired[int]
    created_at: NotRequired[str]
    actual_completion_time: NotRequired[str]


class Pagination(TypedDict):
    current_page: NotRequired[int]
    total_pages: NotRequired[int]
    total_records: NotRequired[int]
    has_next: NotRequired[bool]
    has_prev: NotRequired[bool]


class BatchSessionListResponseSchema(TypedDict):
    batches: NotRequired[list[BatchSessionListItemSchema]]
    pagination: NotRequired[Pagination]


class Error1(TypedDict):
    session_id: NotRequired[str]
    error: NotRequired[str]


class BatchSessionDeleteResponseSchema(TypedDict):
    batch_id: NotRequired[str]
    deleted_sessions: NotRequired[int]
    failed_deletions: NotRequired[int]
    errors: NotRequired[list[Error1]]
    message: NotRequired[str]


class BatchSessionUpdateRequestSchema(TypedDict):
    status: Literal["cancelled"]


class BatchSessionUpdateResponseSchema(TypedDict):
    batch_id: NotRequired[str]
    status: NotRequired[Literal["cancelled"]]
    cancelled_sessions: NotRequired[int]
    message: NotRequired[str]


class BatchSessionRetryRequestSchema(TypedDict):
    retry_failed_only: NotRequired[bool]
    max_retries: NotRequired[int]


class BatchSessionRetryResponseSchema(TypedDict):
    batch_id: NotRequired[str]
    status: NotRequired[Literal["pending", "processing", "completed", "failed", "cancelled"]]
    retried_sessions: NotRequired[int]
    message: NotRequired[str]


IntegrationType: TypeAlias = Literal["1PASSWORD"]


class OnePasswordAllSecretsConfig(TypedDict):
    load_mode: Literal["all"]


class OnePasswordSpecificSecretsConfig(TypedDict):
    load_mode: Literal["specific"]
    secrets: list[str]


OnePasswordConfig: TypeAlias = OnePasswordAllSecretsConfig | OnePasswordSpecificSecretsConfig


class OnePasswordIntegration(TypedDict):
    id: str
    type: Literal["1PASSWORD"]
    configuration: OnePasswordConfig


Integration: TypeAlias = OnePasswordIntegration


class Data14(TypedDict):
    serviceAccount: str


class ServiceAccountCredentials(TypedDict):
    type: Literal["serviceAccount"]
    data: Data14


class CreateIntegrationRequest(TypedDict):
    name: str
    type: IntegrationType
    credentials: ServiceAccountCredentials


class IntegrationItem(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[IntegrationType]
    path: NotRequired[str]
    createdAt: NotRequired[str]


class Data15(TypedDict):
    integrations: NotRequired[list[IntegrationItem]]


class IntegrationListResponse(TypedDict):
    data: NotRequired[Data15]


class Data16(TypedDict):
    integration: NotRequired[IntegrationItem]


class IntegrationResponse(TypedDict):
    data: NotRequired[Data16]


class TaskMetadata(TypedDict):
    id: str
    name: str
    teamId: str
    description: NotRequired[str]
    latest: str
    deleted: bool
    createdAt: str
    updatedAt: str


class TaskExecutionResult(TypedDict):
    id: str
    taskVersionId: str
    version: str
    status: Literal["success", "failure", "timeout", "cancelled", "queued", "running"]
    output: NotRequired[str]
    errorMessage: NotRequired[str]
    startTime: str
    executionTime: NotRequired[float]


class UpdateTaskMetadataRequest(TypedDict):
    name: NotRequired[str]
    description: NotRequired[str]


class RunTaskV2Request(TypedDict):
    input_params: dict[str, str]
    identity_id: NotRequired[str]
    session_id: NotRequired[str]
    cleanup_sessions: NotRequired[bool]
    identity_skip_validation: NotRequired[bool]
    sync: NotRequired[bool]


class ReauthenticateIdentityRequest(TypedDict):
    sync: NotRequired[bool]


ReauthenticateIdentityResponse = TypedDict(
    "ReauthenticateIdentityResponse",
    {
        "identityId": str,
        "async": bool,
    },
)


class AuthFlowV2StartRequest(TypedDict):
    url: str
    host: str


class AuthFlowV2DecisionResolve(TypedDict):
    choice: str


class AuthFlowV2FormResolve(TypedDict):
    option_index: int
    values: dict[str, str]


AuthFlowV2ResolveRequest: TypeAlias = AuthFlowV2FormResolve | AuthFlowV2DecisionResolve


class AuthFlowV2FinalizeRequest(TypedDict):
    identity_name: NotRequired[str]
    profile_name: NotRequired[str]


class AuthFlowV2DecisionOption(TypedDict):
    step_id: str
    label: str
    automatable: bool


class Input(TypedDict):
    name: str
    type: str
    label: NotRequired[str]
    placeholder: NotRequired[str]
    value: NotRequired[str]


class ExtraData(TypedDict):
    create_integration_url: NotRequired[str]
    number: NotRequired[str]


class AuthFlowV2FormOption(TypedDict):
    type: Literal[
        "credentials",
        "mfa_totp",
        "mfa_sms",
        "mfa_email",
        "sso",
        "captcha",
        "consent",
        "magic_link",
        "passkey",
        "generic",
        "totp_secret",
        "gmail_one_click_integration",
    ]
    automatable: bool
    inputs: NotRequired[list[Input]]
    extra_data: NotRequired[ExtraData]
    message: NotRequired[str]
    provider: NotRequired[str]
    phoneHint: NotRequired[str]


class AuthFlowV2ViewBase(TypedDict):
    session_id: str
    host: str
    current_step_label: str
    step_id: str
    cdp_url: str
    live_view_url: str
    discovery_error: NotRequired[str]


class AuthFlowV2DecisionView(AuthFlowV2ViewBase):
    type: Literal["decision"]
    options: list[AuthFlowV2DecisionOption]


class AuthFlowV2FormView(AuthFlowV2ViewBase):
    type: Literal["form"]
    options: list[AuthFlowV2FormOption]
    credentials_rejected: NotRequired[bool]
    credentials_passed: NotRequired[bool]


class AuthFlowV2DetectionFailedView(AuthFlowV2ViewBase):
    type: Literal["detection_failed"]
    node_status: Literal["detected", "failed", "explored"]
    last_error: NotRequired[str]
    retryable: bool
    message: str


class AuthFlowV2AuthenticatedView(AuthFlowV2ViewBase):
    type: Literal["authenticated"]
    message: NotRequired[str]


class AuthFlowV2FailedView(AuthFlowV2ViewBase):
    type: Literal["failed"]
    error: str
    retryable: bool


AuthFlowV2View: TypeAlias = (
    AuthFlowV2DecisionView
    | AuthFlowV2FormView
    | AuthFlowV2DetectionFailedView
    | AuthFlowV2AuthenticatedView
    | AuthFlowV2FailedView
)


class Target(TypedDict):
    step_id: NotRequired[str]
    label: NotRequired[str]


class Nav(TypedDict):
    status: Literal["pending", "succeeded", "failed", "none"]
    error: NotRequired[str]
    credentials_rejected: NotRequired[bool]


class AuthFlowV2State(TypedDict):
    session_id: str
    graph_id: int
    current_step_id: str
    discovery_status: Literal["in_progress", "complete", "failed"]
    discovery_error: NotRequired[str]
    phase: Literal["navigating", "settled"]
    updated_at: float
    target: NotRequired[Target]
    nav: Nav
    view: NotRequired[AuthFlowV2View]


class AuthFlowV2FinalizeResult(TypedDict):
    identityId: str
    profileName: str
    automatable: bool
    nonAutomatableReasons: list[str]


class TaskRunStatusV2Response(TypedDict):
    run_id: str
    status: Literal["queued", "running", "success", "failure", "timeout", "cancelled"]
    result: NotRequired[dict[str, Any]]
    error: NotRequired[str]
    session_id: NotRequired[str]


class TaskParameterV2(TypedDict):
    name: str
    type: Literal["string", "number", "boolean", "secret", "file"]
    required: NotRequired[bool]
    description: NotRequired[str]
    defaultValue: NotRequired[Any]
    options: NotRequired[list[str]]


GenerateTaskV2Request = TypedDict(
    "GenerateTaskV2Request",
    {
        "taskName": str,
        "taskPrompt": str,
        "async": NotRequired[bool],
        "description": NotRequired[str],
        "application_id": NotRequired[str],
        "identity_id": NotRequired[str],
        "input_schema": NotRequired[list[TaskParameterV2]],
        "output_schema": NotRequired[list[TaskParameterV2]],
        "output_file_only": NotRequired[bool],
        "human_intervention": NotRequired[bool],
        "browser_session_id": NotRequired[str],
        "task_browser_default_configuration": NotRequired[dict[str, Any]],
    },
)


class GenerateTaskV2Response(TypedDict):
    id: str
    status: Literal["generating"]
    taskId: NotRequired[str]
    taskVersionId: NotRequired[str]
    projectId: NotRequired[str]


class TaskGenerationStatusV2Response(TypedDict):
    id: str
    status: Literal["generating", "ready", "failed", "waiting-for-session"]
    project_state: NotRequired[str]
    error: NotRequired[str]


class TaskMetadataResponse(TypedDict):
    data: NotRequired[TaskMetadata]


class Version(TypedDict):
    version: str
    description: NotRequired[str]
    createdAt: str
    updatedAt: str


class Data18(TypedDict):
    taskId: str
    versions: list[Version]


class TaskVersionsListResponse(TypedDict):
    data: NotRequired[Data18]


class Pagination1(TypedDict):
    page: int
    limit: int
    total: int
    totalPages: int


class Data19(TypedDict):
    results: list[TaskExecutionResult]
    pagination: Pagination1


class TaskExecutionResultsListResponse(TypedDict):
    data: NotRequired[Data19]


class TaskExecutionResultResponse(TypedDict):
    data: NotRequired[TaskExecutionResult]


Data20 = TypedDict(
    "Data20",
    {
        "success": bool,
        "async": bool,
        "message": str,
        "taskId": str,
        "executionTime": NotRequired[float],
        "output": NotRequired[str],
        "error": NotRequired[str],
        "executionResultId": NotRequired[str],
    },
)


class RunTaskResponse(TypedDict):
    data: NotRequired[Data20]


class Data21(TypedDict):
    success: bool
    message: str


class DeleteTaskResponse(TypedDict):
    data: NotRequired[Data21]


class ApplicationItem(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    url: NotRequired[str]
    description: NotRequired[str]
    identity_count: NotRequired[int]
    auth_methods: NotRequired[list[str]]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class CreateApplicationRequest(TypedDict):
    source: str
    name: NotRequired[str]
    description: NotRequired[str]


class CreateApplicationResponse(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    url: NotRequired[str]
    description: NotRequired[str]
    created_at: NotRequired[str]


class ListApplicationsResponse(TypedDict):
    applications: NotRequired[list[ApplicationItem]]


class GetApplicationResponse(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    url: NotRequired[str]
    description: NotRequired[str]
    identity_count: NotRequired[int]
    auth_methods: NotRequired[list[str]]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class UpdateApplicationRequest(TypedDict):
    allowed_domains: NotRequired[list[str]]


class UpdateApplicationResponse(TypedDict):
    id: NotRequired[str]
    url: NotRequired[str]


class DeleteApplicationResponse(TypedDict):
    success: NotRequired[bool]


class ApplicationIdentityItem(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    auth_flow: NotRequired[str]
    status: NotRequired[Literal["pending", "validated", "failed"]]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class ListApplicationIdentitiesResponse(TypedDict):
    identities: NotRequired[list[ApplicationIdentityItem]]


class CustomFieldDefinition(TypedDict):
    name: str


class AuthFlowItem(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    is_recommended: NotRequired[bool]
    methods: NotRequired[list[str]]
    custom_fields: NotRequired[list[CustomFieldDefinition]]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class ListApplicationAuthFlowsResponse(TypedDict):
    auth_flows: NotRequired[list[AuthFlowItem]]


class CreateAuthFlowRequest(TypedDict):
    name: str
    description: NotRequired[str]
    is_recommended: NotRequired[bool]
    methods: list[Literal["username_password", "authenticator", "custom"]]
    custom_fields: NotRequired[list[CustomFieldDefinition]]


class CreateAuthFlowResponse(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    is_recommended: NotRequired[bool]
    methods: NotRequired[list[str]]
    custom_fields: NotRequired[list[CustomFieldDefinition]]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class UpdateAuthFlowRequest(TypedDict):
    name: NotRequired[str]
    description: NotRequired[str]
    is_recommended: NotRequired[bool]
    methods: NotRequired[list[Literal["username_password", "authenticator", "custom"]]]
    custom_fields: NotRequired[list[CustomFieldDefinition]]


class UpdateAuthFlowResponse(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    is_recommended: NotRequired[bool]
    methods: NotRequired[list[str]]
    custom_fields: NotRequired[list[CustomFieldDefinition]]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class DeleteAuthFlowResponse(TypedDict):
    success: NotRequired[bool]


class UsernamePasswordCredential(TypedDict):
    type: Literal["username_password"]
    username: str
    password: str


class AuthenticatorCredential(TypedDict):
    type: Literal["authenticator"]
    secret: str
    otp: NotRequired[str]


class CustomFieldItem(TypedDict):
    name: str
    value: str


class CustomCredential(TypedDict):
    type: Literal["custom"]
    fields: list[CustomFieldItem]


CredentialData: TypeAlias = UsernamePasswordCredential | AuthenticatorCredential | CustomCredential


class CreateIdentityRequest(TypedDict):
    name: NotRequired[str]
    source: str
    credentials: NotRequired[list[CredentialData]]
    metadata: NotRequired[dict[str, Any]]
    applicationName: NotRequired[str]
    applicationDescription: NotRequired[str]


class CreateIdentityResponse(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    status: NotRequired[Literal["pending", "validated", "failed"]]
    metadata: NotRequired[dict[str, Any]]
    created_at: NotRequired[str]


class GetIdentityResponse(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    source: NotRequired[str]
    status: NotRequired[Literal["pending", "validated", "failed"]]
    metadata: NotRequired[dict[str, Any]]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class UpdateIdentityRequest(TypedDict):
    name: NotRequired[str]
    metadata: NotRequired[dict[str, Any]]
    credentials: NotRequired[list[CredentialData]]


class UpdateIdentityResponse(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    metadata: NotRequired[dict[str, Any]]
    updated_at: NotRequired[str]


class DeleteIdentityResponse(TypedDict):
    message: NotRequired[str]


class GetIdentityCredentialsResponse(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    source: NotRequired[str]
    credentials: NotRequired[list[CredentialData]]


class CreateIdentityTokenRequest(TypedDict):
    callbackUrl: str


class IdentityTokenResponse(TypedDict):
    token: str
    expiresAt: str
    tokenHash: str


WebhookEventType: TypeAlias = Literal[
    "task.completed",
    "task.failed",
    "task.cancelled",
    "task.healed",
    "session.ready",
    "session.completed",
    "session.failed",
    "session.recording.ready",
    "batch.completed",
    "batch.failed",
    "intervention.requested",
    "intervention.resolved",
    "identity.authenticated",
    "identity.authentication_failed",
]


class WebhookPublic(TypedDict):
    id: str
    project_id: str
    url: str
    description: str
    subscribed_events: list[WebhookEventType]
    enabled: bool
    created_at: str
    updated_at: str


class WebhookWithSecret(WebhookPublic):
    secret: str


class WebhookCreateRequest(TypedDict):
    url: str
    description: NotRequired[str]
    subscribed_events: list[WebhookEventType]


class WebhookUpdateRequest(TypedDict):
    url: NotRequired[str]
    description: NotRequired[str]
    subscribed_events: NotRequired[list[WebhookEventType]]
    enabled: NotRequired[bool]


class WebhookListResponse(TypedDict):
    webhooks: list[WebhookPublic]


class WebhookTestRequest(TypedDict):
    event_type: WebhookEventType


class WebhookTestResponse(TypedDict):
    external_event_id: str
    event_type: WebhookEventType


class WebhookEventDeliveryRow(TypedDict):
    id: str
    external_event_id: str
    event_type: WebhookEventType
    status: Literal["pending", "succeeded", "failed", "dead"]
    attempt: int
    response_status: NotRequired[int]
    error_message: NotRequired[str]
    scheduled_at: NotRequired[str]
    completed_at: NotRequired[str]
    payload: NotRequired[dict[str, Any]]


class Pagination2(TypedDict):
    limit: int
    offset: int
    total: int


class WebhookEventsListResponse(TypedDict):
    events: list[WebhookEventDeliveryRow]
    pagination: Pagination2


class WebhookDeleteResponse(TypedDict):
    ok: bool


class AgentAccessNextStep(TypedDict):
    method: Literal["GET", "POST"]
    path: str
    description: str


class AgentAccessInstructions(TypedDict):
    submit: str
    appendix: str
    api_key_header: str
    optional_identity: str
    anonymous_credits: float
    identity_credits: float


class AgentAccessError(TypedDict):
    error: str
    next: AgentAccessNextStep
    docs: str


class Credits(TypedDict):
    anonymous: float
    with_identity: float


class Limits(TypedDict):
    session_max_duration_minutes: float


class FlowItem(TypedDict):
    step: float
    method: Literal["GET", "POST"]
    path: str
    why: str


class OidcItem(TypedDict):
    provider: str
    issuer: str
    how: str


class Identity1(TypedDict):
    optional: bool
    extra_credits: float
    submit: str
    oidc: list[OidcItem]


class AgentAccessGetAgentAccessGuideResponse(TypedDict):
    purpose: str
    docs: str
    credits: Credits
    ttl_seconds: float
    limits: Limits
    flow: list[FlowItem]
    next: AgentAccessNextStep
    identity: Identity1


class Auth(TypedDict):
    api_key_header: str
    identity_token_header: NotRequired[str]
    identity_token_required: bool


class Upgrade(TypedDict):
    message: str


class AgentAccessCreateAgentAccessProjectResponse(TypedDict):
    api_key: str
    project_id: str
    credits_granted: float
    agent_identity_token: NotRequired[str]
    auth: Auth
    upgrade: NotRequired[Upgrade]
    next: AgentAccessNextStep
    docs: str
    limits: Limits


class Challenge(TypedDict):
    id: str
    type: str
    icon: str
    title: str
    description: str
    prompt: str
    timeLimit: float


class AgentAccessGetAgentAccessChallengeResponse(TypedDict):
    challenge: Challenge
    token: str
    appendix_ref: NotRequired[str]
    appendix_url: NotRequired[str]
    instructions: AgentAccessInstructions
    next: NotRequired[AgentAccessNextStep]


class AgentAccessGetAgentAccessAppendixResponse(TypedDict):
    appendix_ref: str
    inventory: str
    next: NotRequired[AgentAccessNextStep]


class Data22(TypedDict):
    session_id: NotRequired[str]
    team_id: NotRequired[str]
    duration: NotRequired[int]
    status: NotRequired[str]
    credits_used: NotRequired[float]
    configuration: NotRequired[dict[str, Any]]
    proxy_bytes: NotRequired[int]
    tokens: NotRequired[dict[str, Any]]
    steps: NotRequired[int]
    tags: NotRequired[list[str]]
    created_at: NotRequired[str]


class SessionsGetSessionResponse(TypedDict):
    data: NotRequired[Data22]


class Item(TypedDict):
    id: str
    title: str
    url: str
    frontend_url: str


class Data23(TypedDict):
    count: float
    items: list[Item]


class SessionsGetSessionPagesResponse(TypedDict):
    data: Data23


class Data24(TypedDict):
    status: NotRequired[str]
    message: NotRequired[str]


class SessionsUploadFileResponse(TypedDict):
    data: NotRequired[Data24]


class SessionsMouseClickResponse(TypedDict):
    status: NotRequired[str]


class SessionsMouseDoubleClickResponse(TypedDict):
    status: NotRequired[str]


class SessionsMouseDownResponse(TypedDict):
    status: NotRequired[str]


class SessionsMouseUpResponse(TypedDict):
    status: NotRequired[str]


class SessionsMouseMoveResponse(TypedDict):
    status: NotRequired[str]


class SessionsDragAndDropResponse(TypedDict):
    status: NotRequired[str]


class SessionsScrollResponse(TypedDict):
    status: NotRequired[str]


class SessionsKeyboardTypeResponse(TypedDict):
    status: NotRequired[str]


class SessionsKeyboardShortcutResponse(TypedDict):
    status: NotRequired[str]


class SessionsSetClipboardResponse(TypedDict):
    status: NotRequired[str]


class SessionsPasteResponse(TypedDict):
    status: NotRequired[str]


class SessionsGotoResponse(TypedDict):
    status: NotRequired[str]


class RecordingsPauseRecordingResponse(TypedDict):
    data: NotRequired[SuccessResponse]


class RecordingsResumeRecordingResponse(TypedDict):
    data: NotRequired[SuccessResponse]


class AgentUploadAgentFilesResponse(TypedDict):
    data: NotRequired[Data24]


class File(TypedDict):
    name: NotRequired[str]
    size: NotRequired[int]
    type: NotRequired[str]
    lastModified: NotRequired[str]


class Data26(TypedDict):
    files: NotRequired[list[File]]


class AgentListAgentFilesResponse(TypedDict):
    data: NotRequired[Data26]


class ExtensionsUploadExtensionResponse(TypedDict):
    data: NotRequired[ExtensionResponseSchema]


class ExtensionsDeleteExtensionResponse(TypedDict):
    data: NotRequired[SuccessResponse]


class Integration1(TypedDict):
    id: NotRequired[str]
    deleted: NotRequired[bool]
    path: NotRequired[str]


class Data27(TypedDict):
    integration: NotRequired[Integration1]


class IntegrationsDeleteIntegrationResponse(TypedDict):
    data: NotRequired[Data27]


class BatchSessionsListBatchSessionsResponse(TypedDict):
    data: NotRequired[BatchSessionListResponseSchema]


class BatchSessionsCreateBatchSessionResponse(TypedDict):
    data: NotRequired[BatchSessionResponseSchema]


class BatchSessionsGetBatchSessionResponse(TypedDict):
    data: NotRequired[BatchSessionStatusResponseSchema]


class BatchSessionsUpdateBatchSessionResponse(TypedDict):
    data: NotRequired[BatchSessionUpdateResponseSchema]


class BatchSessionsDeleteBatchSessionResponse(TypedDict):
    data: NotRequired[BatchSessionDeleteResponseSchema]


class BatchSessionsRetryBatchSessionResponse(TypedDict):
    data: NotRequired[BatchSessionRetryResponseSchema]


class AnchorProxy(TypedDict):
    active: bool
    type: NotRequired[Literal["anchor_proxy"]]
    country_code: NotRequired[AnchorProxyCountryCode]
    region: NotRequired[str]
    city: NotRequired[str]


class Data4(TypedDict):
    request_id: str
    status: Literal["pending", "processing", "ready", "completed", "failed", "cancelled"]
    created_at: str
    session: NotRequired[BatchSessionItemSchema]
    progress: Progress


class AsyncSessionStatusResponseSchema(TypedDict):
    data: NotRequired[Data4]


ProxyConfig: TypeAlias = AnchorProxy | CustomProxy


class SessionConfig(TypedDict):
    initial_url: NotRequired[str]
    tags: NotRequired[list[str]]
    recording: NotRequired[Recording]
    proxy: NotRequired[ProxyConfig]
    timeout: NotRequired[Timeout]
    live_view: NotRequired[LiveView]
    x402: NotRequired[bool]


class SessionCreateRequestSchema(TypedDict):
    session: NotRequired[SessionConfig]
    browser: NotRequired[BrowserConfig]
    integrations: NotRequired[list[Integration]]
    identities: NotRequired[list[Identity]]
    identity_skip_validation: NotRequired[bool]
    identity_async_auth: NotRequired[bool]


class BatchSessionRequestSchema(TypedDict):
    count: int
    configuration: NotRequired[SessionCreateRequestSchema]
    metadata: NotRequired[dict[str, Any]]


class Task(TypedDict):
    id: str
    name: str
    teamId: str
    description: NotRequired[str]
    latestVersion: str
    code: str
    language: Literal["typescript"]
    browserConfiguration: NotRequired[SessionConfig]
    deleted: bool
    createdAt: str
    updatedAt: str


class TaskVersion(TypedDict):
    id: str
    taskId: str
    version: str
    code: str
    language: NotRequired[Literal["typescript"]]
    description: NotRequired[str]
    browserConfiguration: NotRequired[SessionConfig]
    deleted: bool
    createdAt: str
    updatedAt: str


class CreateTaskRequest(TypedDict):
    name: str
    code: NotRequired[str]
    language: Literal["typescript"]
    description: NotRequired[str]
    browserConfiguration: NotRequired[SessionConfig]


class DraftTaskRequest(TypedDict):
    code: str
    language: NotRequired[Literal["typescript"]]
    description: NotRequired[str]
    browserConfiguration: NotRequired[SessionConfig]


class PublishVersionRequest(TypedDict):
    code: NotRequired[str]
    language: NotRequired[Literal["typescript"]]
    description: NotRequired[str]
    browserConfiguration: NotRequired[SessionConfig]


RunTaskRequest = TypedDict(
    "RunTaskRequest",
    {
        "taskId": str,
        "version": NotRequired[str],
        "sessionId": NotRequired[str],
        "async": NotRequired[bool],
        "overrideBrowserConfiguration": NotRequired[SessionConfig],
        "inputs": NotRequired[dict[str, str]],
        "cleanupSessions": NotRequired[bool],
    },
)


RunTaskByNameRequest = TypedDict(
    "RunTaskByNameRequest",
    {
        "sessionId": NotRequired[str],
        "async": NotRequired[bool],
        "overrideBrowserConfiguration": NotRequired[SessionConfig],
        "inputs": NotRequired[dict[str, str]],
        "cleanupSessions": NotRequired[bool],
    },
)


class Data17(TypedDict):
    tasks: list[Task]
    total: int
    page: int
    limit: int


class TaskListResponse(TypedDict):
    data: NotRequired[Data17]


class TaskResponse(TypedDict):
    data: NotRequired[Task]


class TaskVersionResponse(TypedDict):
    data: NotRequired[TaskVersion]
