# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from .agent import AgentResource, AsyncAgentResource
from .tasks import TasksResource, AsyncTasksResource
from .tools import ToolsResource, AsyncToolsResource
from .events import EventsResource, AsyncEventsResource
from .billing import BillingResource, AsyncBillingResource
from .._compat import cached_property
from .profiles import ProfilesResource, AsyncProfilesResource
from .sessions import SessionsResource, AsyncSessionsResource
from .webhooks import WebhooksResource, AsyncWebhooksResource
from .extensions import ExtensionsResource, AsyncExtensionsResource
from .identities import IdentitiesResource, AsyncIdentitiesResource
from .recordings import RecordingsResource, AsyncRecordingsResource
from .agent_access import AgentAccessResource, AsyncAgentAccessResource
from .applications import ApplicationsResource, AsyncApplicationsResource
from .certificates import CertificatesResource, AsyncCertificatesResource
from .integrations import IntegrationsResource, AsyncIntegrationsResource
from .tasks_legacy import TasksLegacyResource, AsyncTasksLegacyResource
from .batch_sessions import BatchSessionsResource, AsyncBatchSessionsResource


class SyncResourcesMixin:
    @cached_property
    def agent(self) -> AgentResource:
        return AgentResource(self)  # type: ignore[arg-type]

    @cached_property
    def agent_access(self) -> AgentAccessResource:
        return AgentAccessResource(self)  # type: ignore[arg-type]

    @cached_property
    def applications(self) -> ApplicationsResource:
        return ApplicationsResource(self)  # type: ignore[arg-type]

    @cached_property
    def batch_sessions(self) -> BatchSessionsResource:
        return BatchSessionsResource(self)  # type: ignore[arg-type]

    @cached_property
    def billing(self) -> BillingResource:
        return BillingResource(self)  # type: ignore[arg-type]

    @cached_property
    def certificates(self) -> CertificatesResource:
        return CertificatesResource(self)  # type: ignore[arg-type]

    @cached_property
    def events(self) -> EventsResource:
        return EventsResource(self)  # type: ignore[arg-type]

    @cached_property
    def extensions(self) -> ExtensionsResource:
        return ExtensionsResource(self)  # type: ignore[arg-type]

    @cached_property
    def identities(self) -> IdentitiesResource:
        return IdentitiesResource(self)  # type: ignore[arg-type]

    @cached_property
    def integrations(self) -> IntegrationsResource:
        return IntegrationsResource(self)  # type: ignore[arg-type]

    @cached_property
    def profiles(self) -> ProfilesResource:
        return ProfilesResource(self)  # type: ignore[arg-type]

    @cached_property
    def recordings(self) -> RecordingsResource:
        return RecordingsResource(self)  # type: ignore[arg-type]

    @cached_property
    def sessions(self) -> SessionsResource:
        return SessionsResource(self)  # type: ignore[arg-type]

    @cached_property
    def tasks(self) -> TasksResource:
        return TasksResource(self)  # type: ignore[arg-type]

    @cached_property
    def tasks_legacy(self) -> TasksLegacyResource:
        return TasksLegacyResource(self)  # type: ignore[arg-type]

    @cached_property
    def tools(self) -> ToolsResource:
        return ToolsResource(self)  # type: ignore[arg-type]

    @cached_property
    def webhooks(self) -> WebhooksResource:
        return WebhooksResource(self)  # type: ignore[arg-type]


class AsyncResourcesMixin:
    @cached_property
    def agent(self) -> AsyncAgentResource:
        return AsyncAgentResource(self)  # type: ignore[arg-type]

    @cached_property
    def agent_access(self) -> AsyncAgentAccessResource:
        return AsyncAgentAccessResource(self)  # type: ignore[arg-type]

    @cached_property
    def applications(self) -> AsyncApplicationsResource:
        return AsyncApplicationsResource(self)  # type: ignore[arg-type]

    @cached_property
    def batch_sessions(self) -> AsyncBatchSessionsResource:
        return AsyncBatchSessionsResource(self)  # type: ignore[arg-type]

    @cached_property
    def billing(self) -> AsyncBillingResource:
        return AsyncBillingResource(self)  # type: ignore[arg-type]

    @cached_property
    def certificates(self) -> AsyncCertificatesResource:
        return AsyncCertificatesResource(self)  # type: ignore[arg-type]

    @cached_property
    def events(self) -> AsyncEventsResource:
        return AsyncEventsResource(self)  # type: ignore[arg-type]

    @cached_property
    def extensions(self) -> AsyncExtensionsResource:
        return AsyncExtensionsResource(self)  # type: ignore[arg-type]

    @cached_property
    def identities(self) -> AsyncIdentitiesResource:
        return AsyncIdentitiesResource(self)  # type: ignore[arg-type]

    @cached_property
    def integrations(self) -> AsyncIntegrationsResource:
        return AsyncIntegrationsResource(self)  # type: ignore[arg-type]

    @cached_property
    def profiles(self) -> AsyncProfilesResource:
        return AsyncProfilesResource(self)  # type: ignore[arg-type]

    @cached_property
    def recordings(self) -> AsyncRecordingsResource:
        return AsyncRecordingsResource(self)  # type: ignore[arg-type]

    @cached_property
    def sessions(self) -> AsyncSessionsResource:
        return AsyncSessionsResource(self)  # type: ignore[arg-type]

    @cached_property
    def tasks(self) -> AsyncTasksResource:
        return AsyncTasksResource(self)  # type: ignore[arg-type]

    @cached_property
    def tasks_legacy(self) -> AsyncTasksLegacyResource:
        return AsyncTasksLegacyResource(self)  # type: ignore[arg-type]

    @cached_property
    def tools(self) -> AsyncToolsResource:
        return AsyncToolsResource(self)  # type: ignore[arg-type]

    @cached_property
    def webhooks(self) -> AsyncWebhooksResource:
        return AsyncWebhooksResource(self)  # type: ignore[arg-type]
