# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["AgentAccessResource", "AsyncAgentAccessResource"]


class AgentAccessResource(SyncAPIResource):
    def get_agent_access_guide(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentAccessGetAgentAccessGuideResponse:
        """
        Agent Access guide

        Unauthenticated onboarding guide. This GET does **not** issue an API key.
        Follow the `next` field: GET `/v1/agent-access/challenge`, solve, then POST
        `/v1/agent-access`
        with `{ token, answer }`. Optional `identity_token` (OIDC JWT) grants more credits.
        Docs: https://docs.anchorbrowser.io/quickstart/agent-access
        """
        return self._get(
            "/v1/agent-access",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentAccessGetAgentAccessGuideResponse,
        )

    def create_agent_access_project(
        self,
        *,
        token: str,
        answer: str,
        identity_provider: str | NotGiven = not_given,
        identity_token: str | NotGiven = not_given,
        identity_audience: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentAccessCreateAgentAccessProjectResponse:
        """
        Create Agent Access project

        Issue an Agent Access API key. Submit the challenge `token` and computed integer `answer`
        from GET /v1/agent-access/challenge. GET on this path returns a guide, not a key.
        Optional `identity_token` as an OIDC JWT grants more credits. `identity_provider` is
        optional
        when the JWT `iss` is Google (`https://accounts.google.com`), GitHub Actions
        (`https://token.actions.githubusercontent.com`), or Vercel (`https://vercel.com`).
        Returns `api_key` for header `anchor-api-key`.
        Docs: https://docs.anchorbrowser.io/quickstart/agent-access

        Args:
          token: Token returned by GET /v1/agent-access/challenge. Not the puzzle answer.
          answer: Final integer from the challenge prompt, as a string.
          identity_provider: Optional when identity_token is an OIDC JWT whose iss matches a known
          provider (google, github, or vercel). Required for opaque OAuth access tokens (google or
          github).
          identity_token: OIDC JWT preferred (iss auto-detected). GitHub Actions — GET
          $ACTIONS_ID_TOKEN_REQUEST_URL with Authorization bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN.
          Google — ID token JWT. Vercel — Sign in with Vercel user ID token (iss
          https://vercel.com). Opaque OAuth access tokens also work with identity_provider set.
          identity_audience: Optional. Pin the JWT aud claim. Omit unless you requested a specific
          aud.
        """
        return self._post(
            "/v1/agent-access",
            body=strip_not_given(
                {
                    "token": token,
                    "answer": answer,
                    "identity_provider": identity_provider,
                    "identity_token": identity_token,
                    "identity_audience": identity_audience,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentAccessCreateAgentAccessProjectResponse,
        )

    def get_agent_access_challenge(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentAccessGetAgentAccessChallengeResponse:
        """
        Get Agent Access challenge

        Get a puzzle and token. Follow next and challenge.prompt, then POST /v1/agent-access with
        token and answer.
        """
        return self._get(
            "/v1/agent-access/challenge",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentAccessGetAgentAccessChallengeResponse,
        )

    def get_agent_access_appendix(
        self,
        appendix_ref: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentAccessGetAgentAccessAppendixResponse:
        """
        Agent Access challenge data

        Supporting data for an active Agent Access challenge. Path comes from the challenge
        response.
        """
        if not appendix_ref:
            raise ValueError(f"Expected a non-empty value for `appendix_ref` but received {appendix_ref!r}")
        return self._get(
            path_template("/v1/agent-access/appendix/{appendixRef}", appendixRef=appendix_ref),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentAccessGetAgentAccessAppendixResponse,
        )


class AsyncAgentAccessResource(AsyncAPIResource):
    async def get_agent_access_guide(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentAccessGetAgentAccessGuideResponse:
        """
        Agent Access guide

        Unauthenticated onboarding guide. This GET does **not** issue an API key.
        Follow the `next` field: GET `/v1/agent-access/challenge`, solve, then POST
        `/v1/agent-access`
        with `{ token, answer }`. Optional `identity_token` (OIDC JWT) grants more credits.
        Docs: https://docs.anchorbrowser.io/quickstart/agent-access
        """
        return await self._get(
            "/v1/agent-access",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentAccessGetAgentAccessGuideResponse,
        )

    async def create_agent_access_project(
        self,
        *,
        token: str,
        answer: str,
        identity_provider: str | NotGiven = not_given,
        identity_token: str | NotGiven = not_given,
        identity_audience: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentAccessCreateAgentAccessProjectResponse:
        """
        Create Agent Access project

        Issue an Agent Access API key. Submit the challenge `token` and computed integer `answer`
        from GET /v1/agent-access/challenge. GET on this path returns a guide, not a key.
        Optional `identity_token` as an OIDC JWT grants more credits. `identity_provider` is
        optional
        when the JWT `iss` is Google (`https://accounts.google.com`), GitHub Actions
        (`https://token.actions.githubusercontent.com`), or Vercel (`https://vercel.com`).
        Returns `api_key` for header `anchor-api-key`.
        Docs: https://docs.anchorbrowser.io/quickstart/agent-access

        Args:
          token: Token returned by GET /v1/agent-access/challenge. Not the puzzle answer.
          answer: Final integer from the challenge prompt, as a string.
          identity_provider: Optional when identity_token is an OIDC JWT whose iss matches a known
          provider (google, github, or vercel). Required for opaque OAuth access tokens (google or
          github).
          identity_token: OIDC JWT preferred (iss auto-detected). GitHub Actions — GET
          $ACTIONS_ID_TOKEN_REQUEST_URL with Authorization bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN.
          Google — ID token JWT. Vercel — Sign in with Vercel user ID token (iss
          https://vercel.com). Opaque OAuth access tokens also work with identity_provider set.
          identity_audience: Optional. Pin the JWT aud claim. Omit unless you requested a specific
          aud.
        """
        return await self._post(
            "/v1/agent-access",
            body=strip_not_given(
                {
                    "token": token,
                    "answer": answer,
                    "identity_provider": identity_provider,
                    "identity_token": identity_token,
                    "identity_audience": identity_audience,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentAccessCreateAgentAccessProjectResponse,
        )

    async def get_agent_access_challenge(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentAccessGetAgentAccessChallengeResponse:
        """
        Get Agent Access challenge

        Get a puzzle and token. Follow next and challenge.prompt, then POST /v1/agent-access with
        token and answer.
        """
        return await self._get(
            "/v1/agent-access/challenge",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentAccessGetAgentAccessChallengeResponse,
        )

    async def get_agent_access_appendix(
        self,
        appendix_ref: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentAccessGetAgentAccessAppendixResponse:
        """
        Agent Access challenge data

        Supporting data for an active Agent Access challenge. Path comes from the challenge
        response.
        """
        if not appendix_ref:
            raise ValueError(f"Expected a non-empty value for `appendix_ref` but received {appendix_ref!r}")
        return await self._get(
            path_template("/v1/agent-access/appendix/{appendixRef}", appendixRef=appendix_ref),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentAccessGetAgentAccessAppendixResponse,
        )
