# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Dict, Union, Mapping, cast

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, FileTypes, not_given
from .._utils import extract_files, path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["AgentResource", "AsyncAgentResource"]


class AgentResource(SyncAPIResource):
    def upload_agent_files(
        self,
        session_id: str,
        *,
        file: FileTypes,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentUploadAgentFilesResponse:
        """
        Upload Agent Resources

        Upload files as agent resources to a browser session using multipart/form-data.
        If you upload a ZIP file, it will be automatically extracted and the files will be made
        available as agent resources.
        If you upload a single file, it will be saved directly as an agent resource.
        Resources are then accessible to AI agents for task completion and automation.

        Args:
          session_id: The browser session ID
          file: File to upload as agent resource (ZIP files will be extracted automatically)
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        body = strip_not_given({"file": file})
        files = extract_files(cast(Mapping[str, object], body), paths=[["file"]])
        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}
        return self._post(
            path_template("/v1/sessions/{sessionId}/agent/files", sessionId=session_id),
            body=body,
            files=files,
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentUploadAgentFilesResponse,
        )

    def list_agent_files(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentListAgentFilesResponse:
        """
        List Agent Resources

        List all resources that have been uploaded to the browser session for agent use.
        Returns resource metadata including name, size, type, and last modified timestamp.

        Args:
          session_id: The browser session ID
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return self._get(
            path_template("/v1/sessions/{sessionId}/agent/files", sessionId=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentListAgentFilesResponse,
        )

    def pause_agent(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Pause Agent

        Pauses the AI agent for the specified browser session.

        Args:
          session_id: The ID of the browser session
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return self._post(
            path_template("/v1/sessions/{session_id}/agent/pause", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )

    def resume_agent(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Resume Agent

        Resumes the AI agent for the specified browser session.

        Args:
          session_id: The ID of the browser session
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return self._post(
            path_template("/v1/sessions/{session_id}/agent/resume", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )

    def list_pending_interventions(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.PendingInterventionsResponse:
        """
        List Pending Human Interventions

        Returns all pending human-in-the-loop (HITL) requests across the team's active
        browser sessions. Each item includes the intervention request plus the session
        ID and tags for routing responses.
        """
        return self._get(
            "/v1/sessions/pending-interventions",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.PendingInterventionsResponse,
        )

    def get_requested_human_intervention(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.HumanInterventionRequestsResponse:
        """
        Get Requested Human Interventions

        Retrieves pending human-in-the-loop (HITL) requests for a specific active browser
        session. Requires `human_intervention: true` on the task that is running in the
        session. The agent pauses until a response is submitted via
        `POST /v1/sessions/{session_id}/agent/respond-to-human-intervention`.

        Args:
          session_id: The ID of the browser session
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return self._get(
            path_template("/v1/sessions/{session_id}/agent/requested-human-intervention", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.HumanInterventionRequestsResponse,
        )

    def respond_to_human_intervention(
        self,
        session_id: str,
        *,
        response: Union[Dict[str, object], bool, str],
        request_id: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.HumanInterventionResponseResponse:
        """
        Respond to Human Intervention

        Sends a response to a pending human-in-the-loop (HITL) request for the specified
        session. Resolving a request unblocks the agent and emits an `intervention.resolved`
        webhook event when `requestId` is provided.

        Args:
          session_id: The ID of the browser session
          request_id: ID of the intervention request to respond to. If omitted, the most recent
          pending request for the session is used.
          response: Response payload. For `text` input type, pass a string. For `confirm`, pass
          a boolean or confirmation string. For `fields`, pass an object keyed by field name.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return self._post(
            path_template("/v1/sessions/{session_id}/agent/respond-to-human-intervention", session_id=session_id),
            body=strip_not_given({"requestId": request_id, "response": response}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.HumanInterventionResponseResponse,
        )


class AsyncAgentResource(AsyncAPIResource):
    async def upload_agent_files(
        self,
        session_id: str,
        *,
        file: FileTypes,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentUploadAgentFilesResponse:
        """
        Upload Agent Resources

        Upload files as agent resources to a browser session using multipart/form-data.
        If you upload a ZIP file, it will be automatically extracted and the files will be made
        available as agent resources.
        If you upload a single file, it will be saved directly as an agent resource.
        Resources are then accessible to AI agents for task completion and automation.

        Args:
          session_id: The browser session ID
          file: File to upload as agent resource (ZIP files will be extracted automatically)
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        body = strip_not_given({"file": file})
        files = extract_files(cast(Mapping[str, object], body), paths=[["file"]])
        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}
        return await self._post(
            path_template("/v1/sessions/{sessionId}/agent/files", sessionId=session_id),
            body=body,
            files=files,
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentUploadAgentFilesResponse,
        )

    async def list_agent_files(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.AgentListAgentFilesResponse:
        """
        List Agent Resources

        List all resources that have been uploaded to the browser session for agent use.
        Returns resource metadata including name, size, type, and last modified timestamp.

        Args:
          session_id: The browser session ID
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return await self._get(
            path_template("/v1/sessions/{sessionId}/agent/files", sessionId=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.AgentListAgentFilesResponse,
        )

    async def pause_agent(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Pause Agent

        Pauses the AI agent for the specified browser session.

        Args:
          session_id: The ID of the browser session
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return await self._post(
            path_template("/v1/sessions/{session_id}/agent/pause", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )

    async def resume_agent(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Resume Agent

        Resumes the AI agent for the specified browser session.

        Args:
          session_id: The ID of the browser session
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return await self._post(
            path_template("/v1/sessions/{session_id}/agent/resume", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )

    async def list_pending_interventions(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.PendingInterventionsResponse:
        """
        List Pending Human Interventions

        Returns all pending human-in-the-loop (HITL) requests across the team's active
        browser sessions. Each item includes the intervention request plus the session
        ID and tags for routing responses.
        """
        return await self._get(
            "/v1/sessions/pending-interventions",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.PendingInterventionsResponse,
        )

    async def get_requested_human_intervention(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.HumanInterventionRequestsResponse:
        """
        Get Requested Human Interventions

        Retrieves pending human-in-the-loop (HITL) requests for a specific active browser
        session. Requires `human_intervention: true` on the task that is running in the
        session. The agent pauses until a response is submitted via
        `POST /v1/sessions/{session_id}/agent/respond-to-human-intervention`.

        Args:
          session_id: The ID of the browser session
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return await self._get(
            path_template("/v1/sessions/{session_id}/agent/requested-human-intervention", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.HumanInterventionRequestsResponse,
        )

    async def respond_to_human_intervention(
        self,
        session_id: str,
        *,
        response: Union[Dict[str, object], bool, str],
        request_id: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.HumanInterventionResponseResponse:
        """
        Respond to Human Intervention

        Sends a response to a pending human-in-the-loop (HITL) request for the specified
        session. Resolving a request unblocks the agent and emits an `intervention.resolved`
        webhook event when `requestId` is provided.

        Args:
          session_id: The ID of the browser session
          request_id: ID of the intervention request to respond to. If omitted, the most recent
          pending request for the session is used.
          response: Response payload. For `text` input type, pass a string. For `confirm`, pass
          a boolean or confirmation string. For `fields`, pass an object keyed by field name.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return await self._post(
            path_template("/v1/sessions/{session_id}/agent/respond-to-human-intervention", session_id=session_id),
            body=strip_not_given({"requestId": request_id, "response": response}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.HumanInterventionResponseResponse,
        )
