# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Literal, Iterable

import httpx

from ..types import models, params
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["ApplicationsResource", "AsyncApplicationsResource"]


class ApplicationsResource(SyncAPIResource):
    def create_application(
        self,
        *,
        source: str,
        name: str | NotGiven = not_given,
        description: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CreateApplicationResponse:
        """
        Create Application

        Creates a new application for identity management.

        Args:
          source: The source URL of the application
          name: Name of the application
          description: Description of the application
        """
        return self._post(
            "/v1/applications",
            body=strip_not_given({"source": source, "name": name, "description": description}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.CreateApplicationResponse,
        )

    def list_applications(
        self,
        *,
        search: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ListApplicationsResponse:
        """
        List Applications

        Retrieves all applications for the authenticated team.

        Args:
          search: Search query to filter applications by name
        """
        return self._get(
            "/v1/applications",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"search": search}),
            ),
            cast_to=models.ListApplicationsResponse,
        )

    def get_application(
        self,
        application_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.GetApplicationResponse:
        """
        Get Application

        Retrieves details of a specific application by its ID.

        Args:
          application_id: The ID of the application to retrieve
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return self._get(
            path_template("/v1/applications/{applicationId}", applicationId=application_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.GetApplicationResponse,
        )

    def delete_application(
        self,
        application_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteApplicationResponse:
        """
        Delete Application

        Deletes an existing application.

        Args:
          application_id: The ID of the application to delete
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return self._delete(
            path_template("/v1/applications/{applicationId}", applicationId=application_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteApplicationResponse,
        )

    def list_application_identities(
        self,
        application_id: str,
        *,
        search: str | NotGiven = not_given,
        metadata: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ListApplicationIdentitiesResponse:
        """
        List Application Identities

        Retrieves all identities associated with a specific application.

        Args:
          application_id: The ID of the application
          search: Search query to filter identities by name
          metadata: Filter identities by metadata. Pass a **JSON object** to filter identities
          whose metadata contains the specified key-value pairs.
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return self._get(
            path_template("/v1/applications/{applicationId}/identities", applicationId=application_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"search": search, "metadata": metadata}),
            ),
            cast_to=models.ListApplicationIdentitiesResponse,
        )

    def list_auth_flows(
        self,
        application_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ListApplicationAuthFlowsResponse:
        """
        List Application Authentication Flows

        Retrieves all authentication flows for a specific application.

        Args:
          application_id: The ID of the application
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return self._get(
            path_template("/v1/applications/{applicationId}/auth-flows", applicationId=application_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ListApplicationAuthFlowsResponse,
        )

    def create_auth_flow(
        self,
        application_id: str,
        *,
        name: str,
        methods: Iterable[Literal["username_password", "authenticator", "custom"]],
        description: str | NotGiven = not_given,
        is_recommended: bool | NotGiven = not_given,
        custom_fields: Iterable[params.CustomFieldDefinition] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CreateAuthFlowResponse:
        """
        Create Authentication Flow

        Creates a new authentication flow for an application.

        Args:
          application_id: The ID of the application
          name: Name of the authentication flow
          description: Description of the authentication flow
          is_recommended: Whether this is the recommended authentication flow
          methods: Authentication methods in this flow
          custom_fields: Custom fields for this authentication flow
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return self._post(
            path_template("/v1/applications/{applicationId}/auth-flows", applicationId=application_id),
            body=strip_not_given(
                {
                    "name": name,
                    "description": description,
                    "is_recommended": is_recommended,
                    "methods": methods,
                    "custom_fields": custom_fields,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.CreateAuthFlowResponse,
        )

    def update_auth_flow(
        self,
        application_id: str,
        auth_flow_id: str,
        *,
        name: str | NotGiven = not_given,
        description: str | NotGiven = not_given,
        is_recommended: bool | NotGiven = not_given,
        methods: Iterable[Literal["username_password", "authenticator", "custom"]] | NotGiven = not_given,
        custom_fields: Iterable[params.CustomFieldDefinition] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.UpdateAuthFlowResponse:
        """
        Update Authentication Flow

        Updates an existing authentication flow.

        Args:
          application_id: The ID of the application
          auth_flow_id: The ID of the authentication flow to update
          name: Name of the authentication flow
          description: Description of the authentication flow
          is_recommended: Whether this is the recommended authentication flow
          methods: Authentication methods in this flow
          custom_fields: Custom fields for this authentication flow
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        if not auth_flow_id:
            raise ValueError(f"Expected a non-empty value for `auth_flow_id` but received {auth_flow_id!r}")
        return self._patch(
            path_template(
                "/v1/applications/{applicationId}/auth-flows/{authFlowId}",
                applicationId=application_id,
                authFlowId=auth_flow_id,
            ),
            body=strip_not_given(
                {
                    "name": name,
                    "description": description,
                    "is_recommended": is_recommended,
                    "methods": methods,
                    "custom_fields": custom_fields,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.UpdateAuthFlowResponse,
        )

    def delete_auth_flow(
        self,
        application_id: str,
        auth_flow_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteAuthFlowResponse:
        """
        Delete Authentication Flow

        Deletes an existing authentication flow.

        Args:
          application_id: The ID of the application
          auth_flow_id: The ID of the authentication flow to delete
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        if not auth_flow_id:
            raise ValueError(f"Expected a non-empty value for `auth_flow_id` but received {auth_flow_id!r}")
        return self._delete(
            path_template(
                "/v1/applications/{applicationId}/auth-flows/{authFlowId}",
                applicationId=application_id,
                authFlowId=auth_flow_id,
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteAuthFlowResponse,
        )

    def create_identity_token(
        self,
        application_id: str,
        *,
        callback_url: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.IdentityTokenResponse:
        """
        Create Identity Token

        Creates an identity token for a specific application. This token is used to initiate
        an authentication flow for linking user identities to the application.

        The callback URL must use HTTPS and is where the user will be redirected after
        authentication.

        Args:
          application_id: The unique identifier of the application
          callback_url: The HTTPS URL where the user will be redirected after authentication. Must
          use HTTPS protocol.
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return self._post(
            path_template("/v1/applications/{applicationId}/tokens", applicationId=application_id),
            body=strip_not_given({"callbackUrl": callback_url}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.IdentityTokenResponse,
        )


class AsyncApplicationsResource(AsyncAPIResource):
    async def create_application(
        self,
        *,
        source: str,
        name: str | NotGiven = not_given,
        description: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CreateApplicationResponse:
        """
        Create Application

        Creates a new application for identity management.

        Args:
          source: The source URL of the application
          name: Name of the application
          description: Description of the application
        """
        return await self._post(
            "/v1/applications",
            body=strip_not_given({"source": source, "name": name, "description": description}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.CreateApplicationResponse,
        )

    async def list_applications(
        self,
        *,
        search: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ListApplicationsResponse:
        """
        List Applications

        Retrieves all applications for the authenticated team.

        Args:
          search: Search query to filter applications by name
        """
        return await self._get(
            "/v1/applications",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"search": search}),
            ),
            cast_to=models.ListApplicationsResponse,
        )

    async def get_application(
        self,
        application_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.GetApplicationResponse:
        """
        Get Application

        Retrieves details of a specific application by its ID.

        Args:
          application_id: The ID of the application to retrieve
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return await self._get(
            path_template("/v1/applications/{applicationId}", applicationId=application_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.GetApplicationResponse,
        )

    async def delete_application(
        self,
        application_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteApplicationResponse:
        """
        Delete Application

        Deletes an existing application.

        Args:
          application_id: The ID of the application to delete
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return await self._delete(
            path_template("/v1/applications/{applicationId}", applicationId=application_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteApplicationResponse,
        )

    async def list_application_identities(
        self,
        application_id: str,
        *,
        search: str | NotGiven = not_given,
        metadata: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ListApplicationIdentitiesResponse:
        """
        List Application Identities

        Retrieves all identities associated with a specific application.

        Args:
          application_id: The ID of the application
          search: Search query to filter identities by name
          metadata: Filter identities by metadata. Pass a **JSON object** to filter identities
          whose metadata contains the specified key-value pairs.
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return await self._get(
            path_template("/v1/applications/{applicationId}/identities", applicationId=application_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"search": search, "metadata": metadata}),
            ),
            cast_to=models.ListApplicationIdentitiesResponse,
        )

    async def list_auth_flows(
        self,
        application_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ListApplicationAuthFlowsResponse:
        """
        List Application Authentication Flows

        Retrieves all authentication flows for a specific application.

        Args:
          application_id: The ID of the application
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return await self._get(
            path_template("/v1/applications/{applicationId}/auth-flows", applicationId=application_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ListApplicationAuthFlowsResponse,
        )

    async def create_auth_flow(
        self,
        application_id: str,
        *,
        name: str,
        methods: Iterable[Literal["username_password", "authenticator", "custom"]],
        description: str | NotGiven = not_given,
        is_recommended: bool | NotGiven = not_given,
        custom_fields: Iterable[params.CustomFieldDefinition] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CreateAuthFlowResponse:
        """
        Create Authentication Flow

        Creates a new authentication flow for an application.

        Args:
          application_id: The ID of the application
          name: Name of the authentication flow
          description: Description of the authentication flow
          is_recommended: Whether this is the recommended authentication flow
          methods: Authentication methods in this flow
          custom_fields: Custom fields for this authentication flow
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return await self._post(
            path_template("/v1/applications/{applicationId}/auth-flows", applicationId=application_id),
            body=strip_not_given(
                {
                    "name": name,
                    "description": description,
                    "is_recommended": is_recommended,
                    "methods": methods,
                    "custom_fields": custom_fields,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.CreateAuthFlowResponse,
        )

    async def update_auth_flow(
        self,
        application_id: str,
        auth_flow_id: str,
        *,
        name: str | NotGiven = not_given,
        description: str | NotGiven = not_given,
        is_recommended: bool | NotGiven = not_given,
        methods: Iterable[Literal["username_password", "authenticator", "custom"]] | NotGiven = not_given,
        custom_fields: Iterable[params.CustomFieldDefinition] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.UpdateAuthFlowResponse:
        """
        Update Authentication Flow

        Updates an existing authentication flow.

        Args:
          application_id: The ID of the application
          auth_flow_id: The ID of the authentication flow to update
          name: Name of the authentication flow
          description: Description of the authentication flow
          is_recommended: Whether this is the recommended authentication flow
          methods: Authentication methods in this flow
          custom_fields: Custom fields for this authentication flow
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        if not auth_flow_id:
            raise ValueError(f"Expected a non-empty value for `auth_flow_id` but received {auth_flow_id!r}")
        return await self._patch(
            path_template(
                "/v1/applications/{applicationId}/auth-flows/{authFlowId}",
                applicationId=application_id,
                authFlowId=auth_flow_id,
            ),
            body=strip_not_given(
                {
                    "name": name,
                    "description": description,
                    "is_recommended": is_recommended,
                    "methods": methods,
                    "custom_fields": custom_fields,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.UpdateAuthFlowResponse,
        )

    async def delete_auth_flow(
        self,
        application_id: str,
        auth_flow_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteAuthFlowResponse:
        """
        Delete Authentication Flow

        Deletes an existing authentication flow.

        Args:
          application_id: The ID of the application
          auth_flow_id: The ID of the authentication flow to delete
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        if not auth_flow_id:
            raise ValueError(f"Expected a non-empty value for `auth_flow_id` but received {auth_flow_id!r}")
        return await self._delete(
            path_template(
                "/v1/applications/{applicationId}/auth-flows/{authFlowId}",
                applicationId=application_id,
                authFlowId=auth_flow_id,
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteAuthFlowResponse,
        )

    async def create_identity_token(
        self,
        application_id: str,
        *,
        callback_url: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.IdentityTokenResponse:
        """
        Create Identity Token

        Creates an identity token for a specific application. This token is used to initiate
        an authentication flow for linking user identities to the application.

        The callback URL must use HTTPS and is where the user will be redirected after
        authentication.

        Args:
          application_id: The unique identifier of the application
          callback_url: The HTTPS URL where the user will be redirected after authentication. Must
          use HTTPS protocol.
        """
        if not application_id:
            raise ValueError(f"Expected a non-empty value for `application_id` but received {application_id!r}")
        return await self._post(
            path_template("/v1/applications/{applicationId}/tokens", applicationId=application_id),
            body=strip_not_given({"callbackUrl": callback_url}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.IdentityTokenResponse,
        )
