# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Dict, Literal

import httpx

from ..types import models, params
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["BatchSessionsResource", "AsyncBatchSessionsResource"]


class BatchSessionsResource(SyncAPIResource):
    def list_batch_sessions(
        self,
        *,
        status: Literal["pending", "processing", "completed", "failed", "cancelled"] | NotGiven = not_given,
        page: int | NotGiven = not_given,
        limit: int | NotGiven = not_given,
        created_after: str | NotGiven = not_given,
        created_before: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsListBatchSessionsResponse:
        """
        List Batch Sessions

        Lists all batch session requests for the authenticated team, with optional filtering
        by status and pagination support.

        Args:
          status: Filter batches by status
          page: Page number (1-based)
          limit: Number of results per page
          created_after: Filter batches created after this timestamp (ISO 8601)
          created_before: Filter batches created before this timestamp (ISO 8601)
        """
        return self._get(
            "/v1/batch-sessions",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given(
                    {
                        "status": status,
                        "page": page,
                        "limit": limit,
                        "created_after": created_after,
                        "created_before": created_before,
                    }
                ),
            ),
            cast_to=models.BatchSessionsListBatchSessionsResponse,
        )

    def create_batch_session(
        self,
        *,
        count: int,
        configuration: params.SessionCreateRequestSchema | NotGiven = not_given,
        metadata: Dict[str, object] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsCreateBatchSessionResponse:
        """
        Create Batch Sessions

        Creates multiple browser sessions in a single batch operation. This endpoint allows you to
        create up to 5,000 browser sessions simultaneously with the same configuration.

        The batch will be processed asynchronously, and you can monitor progress using the batch
        status endpoint.

        Args:
          count: Number of sessions to create in the batch (1-1000)
          configuration: Configuration that applies to all sessions in the batch
          metadata: Optional batch-level metadata for identification and organization
        """
        return self._post(
            "/v1/batch-sessions",
            body=strip_not_given({"count": count, "configuration": configuration, "metadata": metadata}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsCreateBatchSessionResponse,
        )

    def get_batch_session(
        self,
        batch_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsGetBatchSessionResponse:
        """
        Get Batch Session Status

        Retrieves detailed status information for a specific batch, including progress,
        individual session details, and any errors that occurred.

        Args:
          batch_id: The unique identifier of the batch
        """
        if not batch_id:
            raise ValueError(f"Expected a non-empty value for `batch_id` but received {batch_id!r}")
        return self._get(
            path_template("/v1/batch-sessions/{batch_id}", batch_id=batch_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsGetBatchSessionResponse,
        )

    def update_batch_session(
        self,
        batch_id: str,
        *,
        status: Literal["cancelled"],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsUpdateBatchSessionResponse:
        """
        Update Batch Session

        Updates a batch session. Supports cancelling a running or pending batch,
        which terminates all running sessions in the batch.

        Args:
          batch_id: The unique identifier of the batch
          status: Target status for the batch
        """
        if not batch_id:
            raise ValueError(f"Expected a non-empty value for `batch_id` but received {batch_id!r}")
        return self._patch(
            path_template("/v1/batch-sessions/{batch_id}", batch_id=batch_id),
            body=strip_not_given({"status": status}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsUpdateBatchSessionResponse,
        )

    def delete_batch_session(
        self,
        batch_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsDeleteBatchSessionResponse:
        """
        Delete Batch Sessions

        Deletes all sessions in a batch. Running sessions will be terminated
        and all session data will be removed.

        Args:
          batch_id: The unique identifier of the batch
        """
        if not batch_id:
            raise ValueError(f"Expected a non-empty value for `batch_id` but received {batch_id!r}")
        return self._delete(
            path_template("/v1/batch-sessions/{batch_id}", batch_id=batch_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsDeleteBatchSessionResponse,
        )

    def retry_batch_session(
        self,
        batch_id: str,
        *,
        retry_failed_only: bool | NotGiven = not_given,
        max_retries: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsRetryBatchSessionResponse:
        """
        Retry Failed Batch Sessions

        Retries failed sessions in a batch by creating new browser pods for each
        failed session. The batch status will be set back to 'processing'.

        Args:
          batch_id: The unique identifier of the batch
          retry_failed_only: Whether to only retry failed sessions
          max_retries: Maximum number of attempts per failed session. Each session is retried up to
          this many times, stopping on first success.
        """
        if not batch_id:
            raise ValueError(f"Expected a non-empty value for `batch_id` but received {batch_id!r}")
        return self._post(
            path_template("/v1/batch-sessions/{batch_id}/retry", batch_id=batch_id),
            body=strip_not_given({"retry_failed_only": retry_failed_only, "max_retries": max_retries}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsRetryBatchSessionResponse,
        )


class AsyncBatchSessionsResource(AsyncAPIResource):
    async def list_batch_sessions(
        self,
        *,
        status: Literal["pending", "processing", "completed", "failed", "cancelled"] | NotGiven = not_given,
        page: int | NotGiven = not_given,
        limit: int | NotGiven = not_given,
        created_after: str | NotGiven = not_given,
        created_before: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsListBatchSessionsResponse:
        """
        List Batch Sessions

        Lists all batch session requests for the authenticated team, with optional filtering
        by status and pagination support.

        Args:
          status: Filter batches by status
          page: Page number (1-based)
          limit: Number of results per page
          created_after: Filter batches created after this timestamp (ISO 8601)
          created_before: Filter batches created before this timestamp (ISO 8601)
        """
        return await self._get(
            "/v1/batch-sessions",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given(
                    {
                        "status": status,
                        "page": page,
                        "limit": limit,
                        "created_after": created_after,
                        "created_before": created_before,
                    }
                ),
            ),
            cast_to=models.BatchSessionsListBatchSessionsResponse,
        )

    async def create_batch_session(
        self,
        *,
        count: int,
        configuration: params.SessionCreateRequestSchema | NotGiven = not_given,
        metadata: Dict[str, object] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsCreateBatchSessionResponse:
        """
        Create Batch Sessions

        Creates multiple browser sessions in a single batch operation. This endpoint allows you to
        create up to 5,000 browser sessions simultaneously with the same configuration.

        The batch will be processed asynchronously, and you can monitor progress using the batch
        status endpoint.

        Args:
          count: Number of sessions to create in the batch (1-1000)
          configuration: Configuration that applies to all sessions in the batch
          metadata: Optional batch-level metadata for identification and organization
        """
        return await self._post(
            "/v1/batch-sessions",
            body=strip_not_given({"count": count, "configuration": configuration, "metadata": metadata}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsCreateBatchSessionResponse,
        )

    async def get_batch_session(
        self,
        batch_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsGetBatchSessionResponse:
        """
        Get Batch Session Status

        Retrieves detailed status information for a specific batch, including progress,
        individual session details, and any errors that occurred.

        Args:
          batch_id: The unique identifier of the batch
        """
        if not batch_id:
            raise ValueError(f"Expected a non-empty value for `batch_id` but received {batch_id!r}")
        return await self._get(
            path_template("/v1/batch-sessions/{batch_id}", batch_id=batch_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsGetBatchSessionResponse,
        )

    async def update_batch_session(
        self,
        batch_id: str,
        *,
        status: Literal["cancelled"],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsUpdateBatchSessionResponse:
        """
        Update Batch Session

        Updates a batch session. Supports cancelling a running or pending batch,
        which terminates all running sessions in the batch.

        Args:
          batch_id: The unique identifier of the batch
          status: Target status for the batch
        """
        if not batch_id:
            raise ValueError(f"Expected a non-empty value for `batch_id` but received {batch_id!r}")
        return await self._patch(
            path_template("/v1/batch-sessions/{batch_id}", batch_id=batch_id),
            body=strip_not_given({"status": status}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsUpdateBatchSessionResponse,
        )

    async def delete_batch_session(
        self,
        batch_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsDeleteBatchSessionResponse:
        """
        Delete Batch Sessions

        Deletes all sessions in a batch. Running sessions will be terminated
        and all session data will be removed.

        Args:
          batch_id: The unique identifier of the batch
        """
        if not batch_id:
            raise ValueError(f"Expected a non-empty value for `batch_id` but received {batch_id!r}")
        return await self._delete(
            path_template("/v1/batch-sessions/{batch_id}", batch_id=batch_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsDeleteBatchSessionResponse,
        )

    async def retry_batch_session(
        self,
        batch_id: str,
        *,
        retry_failed_only: bool | NotGiven = not_given,
        max_retries: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BatchSessionsRetryBatchSessionResponse:
        """
        Retry Failed Batch Sessions

        Retries failed sessions in a batch by creating new browser pods for each
        failed session. The batch status will be set back to 'processing'.

        Args:
          batch_id: The unique identifier of the batch
          retry_failed_only: Whether to only retry failed sessions
          max_retries: Maximum number of attempts per failed session. Each session is retried up to
          this many times, stopping on first success.
        """
        if not batch_id:
            raise ValueError(f"Expected a non-empty value for `batch_id` but received {batch_id!r}")
        return await self._post(
            path_template("/v1/batch-sessions/{batch_id}/retry", batch_id=batch_id),
            body=strip_not_given({"retry_failed_only": retry_failed_only, "max_retries": max_retries}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BatchSessionsRetryBatchSessionResponse,
        )
