# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["BillingResource", "AsyncBillingResource"]


class BillingResource(SyncAPIResource):
    def get_billing(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BillingInfoResponse:
        """
        Get Billing Info

        Retrieves credit balance, current-period credit usage, tier, and billing limits for the
        authenticated project.
        """
        return self._get(
            "/v1/billing",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BillingInfoResponse,
        )


class AsyncBillingResource(AsyncAPIResource):
    async def get_billing(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.BillingInfoResponse:
        """
        Get Billing Info

        Retrieves credit balance, current-period credit usage, tier, and billing limits for the
        authenticated project.
        """
        return await self._get(
            "/v1/billing",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.BillingInfoResponse,
        )
