# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Mapping, cast

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, FileTypes, not_given
from .._utils import extract_files, path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["CertificatesResource", "AsyncCertificatesResource"]


class CertificatesResource(SyncAPIResource):
    def create_certificate(
        self,
        *,
        file: FileTypes,
        name: str,
        description: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CertificateResponse:
        """
        Upload Certificate

        Upload a CA certificate to trust in browser sessions. Certificates are managed at the team
        level.
        Once uploaded, reference the certificate by name when creating sessions to trust services
        using that CA.

        See [CA Certificates documentation](/advanced/ca-certificates) for more details.

        Args:
          file: Certificate file (.crt, .pem, .cer, or .der format)
          name: Unique identifier for the certificate (alphanumeric, hyphens, underscores only,
          1-255 characters)
          description: Optional description of the certificate (max 1000 characters)
        """
        body = strip_not_given({"file": file, "name": name, "description": description})
        files = extract_files(cast(Mapping[str, object], body), paths=[["file"]])
        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}
        return self._post(
            "/v1/certificates",
            body=body,
            files=files,
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.CertificateResponse,
        )

    def list_certificates(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CertificateListResponse:
        """
        List Certificates

        Get all CA certificates uploaded for the team
        """
        return self._get(
            "/v1/certificates",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.CertificateListResponse,
        )

    def delete_certificate(
        self,
        name: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Delete Certificate

        Delete a CA certificate by name. The certificate will be removed from storage and can no
        longer be used in new sessions.

        Args:
          name: The name of the certificate to delete
        """
        if not name:
            raise ValueError(f"Expected a non-empty value for `name` but received {name!r}")
        return self._delete(
            path_template("/v1/certificates/{name}", name=name),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )


class AsyncCertificatesResource(AsyncAPIResource):
    async def create_certificate(
        self,
        *,
        file: FileTypes,
        name: str,
        description: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CertificateResponse:
        """
        Upload Certificate

        Upload a CA certificate to trust in browser sessions. Certificates are managed at the team
        level.
        Once uploaded, reference the certificate by name when creating sessions to trust services
        using that CA.

        See [CA Certificates documentation](/advanced/ca-certificates) for more details.

        Args:
          file: Certificate file (.crt, .pem, .cer, or .der format)
          name: Unique identifier for the certificate (alphanumeric, hyphens, underscores only,
          1-255 characters)
          description: Optional description of the certificate (max 1000 characters)
        """
        body = strip_not_given({"file": file, "name": name, "description": description})
        files = extract_files(cast(Mapping[str, object], body), paths=[["file"]])
        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}
        return await self._post(
            "/v1/certificates",
            body=body,
            files=files,
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.CertificateResponse,
        )

    async def list_certificates(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CertificateListResponse:
        """
        List Certificates

        Get all CA certificates uploaded for the team
        """
        return await self._get(
            "/v1/certificates",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.CertificateListResponse,
        )

    async def delete_certificate(
        self,
        name: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Delete Certificate

        Delete a CA certificate by name. The certificate will be removed from storage and can no
        longer be used in new sessions.

        Args:
          name: The name of the certificate to delete
        """
        if not name:
            raise ValueError(f"Expected a non-empty value for `name` but received {name!r}")
        return await self._delete(
            path_template("/v1/certificates/{name}", name=name),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )
