# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Dict

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["EventsResource", "AsyncEventsResource"]


class EventsResource(SyncAPIResource):
    def wait_for_event(
        self,
        event_name: str,
        *,
        timeout_ms: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.EventResponseSchema:
        """
        Wait for Event

        Waits for a specific event to be signaled by another process, workflow, or session.
        This endpoint blocks until the event is signaled or the timeout is reached.
        Useful for coordinating between multiple browser sessions or workflows.

        Args:
          event_name: The name of the event to wait for
          timeout_ms: Timeout in milliseconds to wait for the event. Defaults to 60000ms (1 minute).
        """
        if not event_name:
            raise ValueError(f"Expected a non-empty value for `event_name` but received {event_name!r}")
        return self._post(
            path_template("/v1/events/{event_name}/wait", event_name=event_name),
            body=strip_not_given({"timeoutMs": timeout_ms}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.EventResponseSchema,
        )

    def signal_event(
        self,
        event_name: str,
        *,
        data: Dict[str, object],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Signal Event

        Signals an event with associated data, unblocking any clients waiting for this event.
        This enables coordination between different browser sessions, workflows, or external
        processes.

        Args:
          event_name: The name of the event to signal
          data: Event data to be passed to waiting clients
        """
        if not event_name:
            raise ValueError(f"Expected a non-empty value for `event_name` but received {event_name!r}")
        return self._post(
            path_template("/v1/events/{event_name}", event_name=event_name),
            body=strip_not_given({"data": data}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )


class AsyncEventsResource(AsyncAPIResource):
    async def wait_for_event(
        self,
        event_name: str,
        *,
        timeout_ms: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.EventResponseSchema:
        """
        Wait for Event

        Waits for a specific event to be signaled by another process, workflow, or session.
        This endpoint blocks until the event is signaled or the timeout is reached.
        Useful for coordinating between multiple browser sessions or workflows.

        Args:
          event_name: The name of the event to wait for
          timeout_ms: Timeout in milliseconds to wait for the event. Defaults to 60000ms (1 minute).
        """
        if not event_name:
            raise ValueError(f"Expected a non-empty value for `event_name` but received {event_name!r}")
        return await self._post(
            path_template("/v1/events/{event_name}/wait", event_name=event_name),
            body=strip_not_given({"timeoutMs": timeout_ms}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.EventResponseSchema,
        )

    async def signal_event(
        self,
        event_name: str,
        *,
        data: Dict[str, object],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Signal Event

        Signals an event with associated data, unblocking any clients waiting for this event.
        This enables coordination between different browser sessions, workflows, or external
        processes.

        Args:
          event_name: The name of the event to signal
          data: Event data to be passed to waiting clients
        """
        if not event_name:
            raise ValueError(f"Expected a non-empty value for `event_name` but received {event_name!r}")
        return await self._post(
            path_template("/v1/events/{event_name}", event_name=event_name),
            body=strip_not_given({"data": data}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )
