# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Mapping, cast

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, FileTypes, not_given
from .._utils import extract_files, path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["ExtensionsResource", "AsyncExtensionsResource"]


class ExtensionsResource(SyncAPIResource):
    def upload_extension(
        self,
        *,
        file: FileTypes,
        name: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ExtensionsUploadExtensionResponse:
        """
        Upload Extension

        Upload a new browser extension as a ZIP file. The extension will be validated and stored
        for use in browser sessions.

        Args:
          file: ZIP file containing the browser extension
          name: User-friendly name for the extension (1-255 characters)
        """
        body = strip_not_given({"file": file, "name": name})
        files = extract_files(cast(Mapping[str, object], body), paths=[["file"]])
        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}
        return self._post(
            "/v1/extensions",
            body=body,
            files=files,
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ExtensionsUploadExtensionResponse,
        )

    def list_extensions(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ExtensionListResponse:
        """
        List Extensions

        Get all extensions for the authenticated user
        """
        return self._get(
            "/v1/extensions",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ExtensionListResponse,
        )

    def get_extension(
        self,
        id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ExtensionResponseSchema:
        """
        Get Extension Details

        Get details of a specific extension by its ID

        Args:
          id: The ID of the extension to retrieve
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return self._get(
            path_template("/v1/extensions/{id}", id=id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ExtensionResponseSchema,
        )

    def delete_extension(
        self,
        id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ExtensionsDeleteExtensionResponse:
        """
        Delete Extension

        Delete an extension and remove it from storage

        Args:
          id: The ID of the extension to delete
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return self._delete(
            path_template("/v1/extensions/{id}", id=id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ExtensionsDeleteExtensionResponse,
        )


class AsyncExtensionsResource(AsyncAPIResource):
    async def upload_extension(
        self,
        *,
        file: FileTypes,
        name: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ExtensionsUploadExtensionResponse:
        """
        Upload Extension

        Upload a new browser extension as a ZIP file. The extension will be validated and stored
        for use in browser sessions.

        Args:
          file: ZIP file containing the browser extension
          name: User-friendly name for the extension (1-255 characters)
        """
        body = strip_not_given({"file": file, "name": name})
        files = extract_files(cast(Mapping[str, object], body), paths=[["file"]])
        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}
        return await self._post(
            "/v1/extensions",
            body=body,
            files=files,
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ExtensionsUploadExtensionResponse,
        )

    async def list_extensions(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ExtensionListResponse:
        """
        List Extensions

        Get all extensions for the authenticated user
        """
        return await self._get(
            "/v1/extensions",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ExtensionListResponse,
        )

    async def get_extension(
        self,
        id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ExtensionResponseSchema:
        """
        Get Extension Details

        Get details of a specific extension by its ID

        Args:
          id: The ID of the extension to retrieve
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return await self._get(
            path_template("/v1/extensions/{id}", id=id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ExtensionResponseSchema,
        )

    async def delete_extension(
        self,
        id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ExtensionsDeleteExtensionResponse:
        """
        Delete Extension

        Delete an extension and remove it from storage

        Args:
          id: The ID of the extension to delete
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return await self._delete(
            path_template("/v1/extensions/{id}", id=id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ExtensionsDeleteExtensionResponse,
        )
