# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Dict, Iterable

import httpx

from ..types import models, params
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["IdentitiesResource", "AsyncIdentitiesResource"]


class IdentitiesResource(SyncAPIResource):
    def create_identity(
        self,
        *,
        source: str,
        name: str | NotGiven = not_given,
        credentials: Iterable[params.CredentialData] | NotGiven = not_given,
        metadata: Dict[str, object] | NotGiven = not_given,
        application_name: str | NotGiven = not_given,
        application_description: str | NotGiven = not_given,
        validate_async: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CreateIdentityResponse:
        """
        Create Identity

        Creates a new identity for the given source. Credentials are optional.

        Args:
          name: Name of the identity. Defaults to "Unnamed Identity" if not provided.
          source: The source URL for the identity (e.g., login page URL)
          credentials: Optional credentials to associate with this identity (for example
          username/password
          or authenticator secrets). Omit this field or supply an empty array when you only
          need an identity for the given source URL and optional metadata.
          metadata: Optional metadata for the identity
          application_name: Optional application name to associate with the identity
          application_description: Optional application description
          validate_async: Whether to validate the identity asynchronously. Defaults to true.
        """
        return self._post(
            "/v1/identities",
            body=strip_not_given(
                {
                    "name": name,
                    "source": source,
                    "credentials": credentials,
                    "metadata": metadata,
                    "applicationName": application_name,
                    "applicationDescription": application_description,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"validateAsync": validate_async}),
            ),
            cast_to=models.CreateIdentityResponse,
        )

    def get_identity(
        self,
        identity_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.GetIdentityResponse:
        """
        Get Identity

        Retrieves details of a specific identity by its ID.

        Args:
          identity_id: The ID of the identity to retrieve
        """
        if not identity_id:
            raise ValueError(f"Expected a non-empty value for `identity_id` but received {identity_id!r}")
        return self._get(
            path_template("/v1/identities/{identityId}", identityId=identity_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.GetIdentityResponse,
        )

    def update_identity(
        self,
        identity_id: str,
        *,
        name: str | NotGiven = not_given,
        metadata: Dict[str, object] | NotGiven = not_given,
        credentials: Iterable[params.CredentialData] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.UpdateIdentityResponse:
        """
        Update Identity

        Updates an existing identity's name, metadata, or credentials.

        Args:
          identity_id: The ID of the identity to update
          name: Name of the identity
          metadata: Metadata for the identity
          credentials: Array of credentials for authentication
        """
        if not identity_id:
            raise ValueError(f"Expected a non-empty value for `identity_id` but received {identity_id!r}")
        return self._put(
            path_template("/v1/identities/{identityId}", identityId=identity_id),
            body=strip_not_given({"name": name, "metadata": metadata, "credentials": credentials}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.UpdateIdentityResponse,
        )

    def delete_identity(
        self,
        identity_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteIdentityResponse:
        """
        Delete Identity

        Deletes an existing identity.

        Args:
          identity_id: The ID of the identity to delete
        """
        if not identity_id:
            raise ValueError(f"Expected a non-empty value for `identity_id` but received {identity_id!r}")
        return self._delete(
            path_template("/v1/identities/{identityId}", identityId=identity_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteIdentityResponse,
        )


class AsyncIdentitiesResource(AsyncAPIResource):
    async def create_identity(
        self,
        *,
        source: str,
        name: str | NotGiven = not_given,
        credentials: Iterable[params.CredentialData] | NotGiven = not_given,
        metadata: Dict[str, object] | NotGiven = not_given,
        application_name: str | NotGiven = not_given,
        application_description: str | NotGiven = not_given,
        validate_async: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.CreateIdentityResponse:
        """
        Create Identity

        Creates a new identity for the given source. Credentials are optional.

        Args:
          name: Name of the identity. Defaults to "Unnamed Identity" if not provided.
          source: The source URL for the identity (e.g., login page URL)
          credentials: Optional credentials to associate with this identity (for example
          username/password
          or authenticator secrets). Omit this field or supply an empty array when you only
          need an identity for the given source URL and optional metadata.
          metadata: Optional metadata for the identity
          application_name: Optional application name to associate with the identity
          application_description: Optional application description
          validate_async: Whether to validate the identity asynchronously. Defaults to true.
        """
        return await self._post(
            "/v1/identities",
            body=strip_not_given(
                {
                    "name": name,
                    "source": source,
                    "credentials": credentials,
                    "metadata": metadata,
                    "applicationName": application_name,
                    "applicationDescription": application_description,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"validateAsync": validate_async}),
            ),
            cast_to=models.CreateIdentityResponse,
        )

    async def get_identity(
        self,
        identity_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.GetIdentityResponse:
        """
        Get Identity

        Retrieves details of a specific identity by its ID.

        Args:
          identity_id: The ID of the identity to retrieve
        """
        if not identity_id:
            raise ValueError(f"Expected a non-empty value for `identity_id` but received {identity_id!r}")
        return await self._get(
            path_template("/v1/identities/{identityId}", identityId=identity_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.GetIdentityResponse,
        )

    async def update_identity(
        self,
        identity_id: str,
        *,
        name: str | NotGiven = not_given,
        metadata: Dict[str, object] | NotGiven = not_given,
        credentials: Iterable[params.CredentialData] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.UpdateIdentityResponse:
        """
        Update Identity

        Updates an existing identity's name, metadata, or credentials.

        Args:
          identity_id: The ID of the identity to update
          name: Name of the identity
          metadata: Metadata for the identity
          credentials: Array of credentials for authentication
        """
        if not identity_id:
            raise ValueError(f"Expected a non-empty value for `identity_id` but received {identity_id!r}")
        return await self._put(
            path_template("/v1/identities/{identityId}", identityId=identity_id),
            body=strip_not_given({"name": name, "metadata": metadata, "credentials": credentials}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.UpdateIdentityResponse,
        )

    async def delete_identity(
        self,
        identity_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteIdentityResponse:
        """
        Delete Identity

        Deletes an existing identity.

        Args:
          identity_id: The ID of the identity to delete
        """
        if not identity_id:
            raise ValueError(f"Expected a non-empty value for `identity_id` but received {identity_id!r}")
        return await self._delete(
            path_template("/v1/identities/{identityId}", identityId=identity_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteIdentityResponse,
        )
