# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Literal

import httpx

from ..types import models, params
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["IntegrationsResource", "AsyncIntegrationsResource"]


class IntegrationsResource(SyncAPIResource):
    def create_integration(
        self,
        *,
        name: str,
        type: Literal["1PASSWORD"],
        credentials: params.ServiceAccountCredentials,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.IntegrationResponse:
        """
        Create Integration

        Creates a new integration with a third-party service like 1Password.
        The integration can then be used in browser sessions to automatically load secrets and
        credentials.

        Args:
          name: Name for the integration
          type: The type of integration
        """
        return self._post(
            "/v1/integrations",
            body=strip_not_given({"name": name, "type": type, "credentials": credentials}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.IntegrationResponse,
        )

    def list_integrations(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.IntegrationListResponse:
        """
        List Integrations

        Retrieves all integrations for the authenticated team.
        """
        return self._get(
            "/v1/integrations",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.IntegrationListResponse,
        )

    def delete_integration(
        self,
        integration_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.IntegrationsDeleteIntegrationResponse:
        """
        Delete Integration

        Deletes an existing integration and removes its stored credentials.

        Args:
          integration_id: The ID of the integration to delete
        """
        if not integration_id:
            raise ValueError(f"Expected a non-empty value for `integration_id` but received {integration_id!r}")
        return self._delete(
            path_template("/v1/integrations/{integrationId}", integrationId=integration_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.IntegrationsDeleteIntegrationResponse,
        )


class AsyncIntegrationsResource(AsyncAPIResource):
    async def create_integration(
        self,
        *,
        name: str,
        type: Literal["1PASSWORD"],
        credentials: params.ServiceAccountCredentials,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.IntegrationResponse:
        """
        Create Integration

        Creates a new integration with a third-party service like 1Password.
        The integration can then be used in browser sessions to automatically load secrets and
        credentials.

        Args:
          name: Name for the integration
          type: The type of integration
        """
        return await self._post(
            "/v1/integrations",
            body=strip_not_given({"name": name, "type": type, "credentials": credentials}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.IntegrationResponse,
        )

    async def list_integrations(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.IntegrationListResponse:
        """
        List Integrations

        Retrieves all integrations for the authenticated team.
        """
        return await self._get(
            "/v1/integrations",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.IntegrationListResponse,
        )

    async def delete_integration(
        self,
        integration_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.IntegrationsDeleteIntegrationResponse:
        """
        Delete Integration

        Deletes an existing integration and removes its stored credentials.

        Args:
          integration_id: The ID of the integration to delete
        """
        if not integration_id:
            raise ValueError(f"Expected a non-empty value for `integration_id` but received {integration_id!r}")
        return await self._delete(
            path_template("/v1/integrations/{integrationId}", integrationId=integration_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.IntegrationsDeleteIntegrationResponse,
        )
