# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Literal

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["ProfilesResource", "AsyncProfilesResource"]


class ProfilesResource(SyncAPIResource):
    def create_profile(
        self,
        *,
        name: str,
        description: str | NotGiven = not_given,
        source: Literal["session"] | NotGiven = not_given,
        session_id: str | NotGiven = not_given,
        dedicated_sticky_ip: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Create Profile

        Creates a new profile from a browser session. A Profile stores cookies, local storage, and
        cache.

        Args:
          name: The name of the profile.
          description: A description of the profile.
          source: The source of the profile data. currently only `session` is supported.
          session_id: The browser session ID is required if the source is set to `session`. The
          browser session must be running, and the profile will be stored once the browser session
          terminates.
          dedicated_sticky_ip: Whether to use a dedicated sticky IP for this profile. Defaults to
          false.
        """
        return self._post(
            "/v1/profiles",
            body=strip_not_given(
                {
                    "name": name,
                    "description": description,
                    "source": source,
                    "session_id": session_id,
                    "dedicated_sticky_ip": dedicated_sticky_ip,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )

    def list_profiles(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ProfileListResponse:
        """
        List Profiles

        Fetches all stored profiles.
        """
        return self._get(
            "/v1/profiles",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ProfileListResponse,
        )

    def get_profile(
        self,
        name: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ProfileResponse:
        """
        Get Profile

        Retrieves details of a specific profile by its name.

        Args:
          name: The name of the profile to retrieve.
        """
        if not name:
            raise ValueError(f"Expected a non-empty value for `name` but received {name!r}")
        return self._get(
            path_template("/v1/profiles/{name}", name=name),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ProfileResponse,
        )

    def delete_profile(
        self,
        name: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Delete Profile

        Deletes an existing profile by its name.

        Args:
          name: The name of the profile to delete.
        """
        if not name:
            raise ValueError(f"Expected a non-empty value for `name` but received {name!r}")
        return self._delete(
            path_template("/v1/profiles/{name}", name=name),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )


class AsyncProfilesResource(AsyncAPIResource):
    async def create_profile(
        self,
        *,
        name: str,
        description: str | NotGiven = not_given,
        source: Literal["session"] | NotGiven = not_given,
        session_id: str | NotGiven = not_given,
        dedicated_sticky_ip: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Create Profile

        Creates a new profile from a browser session. A Profile stores cookies, local storage, and
        cache.

        Args:
          name: The name of the profile.
          description: A description of the profile.
          source: The source of the profile data. currently only `session` is supported.
          session_id: The browser session ID is required if the source is set to `session`. The
          browser session must be running, and the profile will be stored once the browser session
          terminates.
          dedicated_sticky_ip: Whether to use a dedicated sticky IP for this profile. Defaults to
          false.
        """
        return await self._post(
            "/v1/profiles",
            body=strip_not_given(
                {
                    "name": name,
                    "description": description,
                    "source": source,
                    "session_id": session_id,
                    "dedicated_sticky_ip": dedicated_sticky_ip,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )

    async def list_profiles(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ProfileListResponse:
        """
        List Profiles

        Fetches all stored profiles.
        """
        return await self._get(
            "/v1/profiles",
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ProfileListResponse,
        )

    async def get_profile(
        self,
        name: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.ProfileResponse:
        """
        Get Profile

        Retrieves details of a specific profile by its name.

        Args:
          name: The name of the profile to retrieve.
        """
        if not name:
            raise ValueError(f"Expected a non-empty value for `name` but received {name!r}")
        return await self._get(
            path_template("/v1/profiles/{name}", name=name),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.ProfileResponse,
        )

    async def delete_profile(
        self,
        name: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Delete Profile

        Deletes an existing profile by its name.

        Args:
          name: The name of the profile to delete.
        """
        if not name:
            raise ValueError(f"Expected a non-empty value for `name` but received {name!r}")
        return await self._delete(
            path_template("/v1/profiles/{name}", name=name),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )
