# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template
from .._resource import SyncAPIResource, AsyncAPIResource
from .._response import BinaryAPIResponse, AsyncBinaryAPIResponse
from .._base_client import make_request_options

__all__ = ["RecordingsResource", "AsyncRecordingsResource"]


class RecordingsResource(SyncAPIResource):
    def pause_recording(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RecordingsPauseRecordingResponse:
        """
        Pause Session Recording

        Pauses the video recording for the specified browser session.

        Args:
          session_id: The ID of the browser session for which to pause recording.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return self._post(
            path_template("/v1/sessions/{session_id}/recordings/pause", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RecordingsPauseRecordingResponse,
        )

    def resume_recording(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RecordingsResumeRecordingResponse:
        """
        Resume Session Recording

        Resumes the video recording for the specified browser session.

        Args:
          session_id: The ID of the browser session for which to resume recording.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return self._post(
            path_template("/v1/sessions/{session_id}/recordings/resume", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RecordingsResumeRecordingResponse,
        )

    def list_recordings(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RecordingListResponse:
        """
        List Session Recordings

        Retrieves the URLs of the browser session's video recordings. Requires a valid API key for
        authentication.

        Args:
          session_id: The ID of the browser session to retrieve recordings for.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return self._get(
            path_template("/v1/sessions/{session_id}/recordings", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RecordingListResponse,
        )

    def fetch_primary_recording(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> BinaryAPIResponse:
        """
        Get Session Recording

        Downloads the primary recording file for the specified browser session. Returns the
        recording as an MP4 file.

        Args:
          session_id: The ID of the browser session to download the recording for.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        extra_headers = {"Accept": "video/mp4", **(extra_headers or {})}
        return self._get(
            path_template("/v1/sessions/{session_id}/recordings/primary/fetch", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=BinaryAPIResponse,
        )

    def delete_recording(
        self,
        session_id: str,
        recording_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Delete Session Recording

        Deletes a specific recording from a browser session. Use "primary" as the recording_id to
        delete the primary recording.

        Args:
          session_id: The ID of the browser session the recording belongs to.
          recording_id: The ID of the recording to delete. Use "primary" to delete the primary
          recording.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        if not recording_id:
            raise ValueError(f"Expected a non-empty value for `recording_id` but received {recording_id!r}")
        return self._delete(
            path_template(
                "/v1/sessions/{session_id}/recordings/{recording_id}", session_id=session_id, recording_id=recording_id
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )


class AsyncRecordingsResource(AsyncAPIResource):
    async def pause_recording(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RecordingsPauseRecordingResponse:
        """
        Pause Session Recording

        Pauses the video recording for the specified browser session.

        Args:
          session_id: The ID of the browser session for which to pause recording.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return await self._post(
            path_template("/v1/sessions/{session_id}/recordings/pause", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RecordingsPauseRecordingResponse,
        )

    async def resume_recording(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RecordingsResumeRecordingResponse:
        """
        Resume Session Recording

        Resumes the video recording for the specified browser session.

        Args:
          session_id: The ID of the browser session for which to resume recording.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return await self._post(
            path_template("/v1/sessions/{session_id}/recordings/resume", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RecordingsResumeRecordingResponse,
        )

    async def list_recordings(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RecordingListResponse:
        """
        List Session Recordings

        Retrieves the URLs of the browser session's video recordings. Requires a valid API key for
        authentication.

        Args:
          session_id: The ID of the browser session to retrieve recordings for.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        return await self._get(
            path_template("/v1/sessions/{session_id}/recordings", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RecordingListResponse,
        )

    async def fetch_primary_recording(
        self,
        session_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncBinaryAPIResponse:
        """
        Get Session Recording

        Downloads the primary recording file for the specified browser session. Returns the
        recording as an MP4 file.

        Args:
          session_id: The ID of the browser session to download the recording for.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        extra_headers = {"Accept": "video/mp4", **(extra_headers or {})}
        return await self._get(
            path_template("/v1/sessions/{session_id}/recordings/primary/fetch", session_id=session_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=AsyncBinaryAPIResponse,
        )

    async def delete_recording(
        self,
        session_id: str,
        recording_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.SuccessResponse:
        """
        Delete Session Recording

        Deletes a specific recording from a browser session. Use "primary" as the recording_id to
        delete the primary recording.

        Args:
          session_id: The ID of the browser session the recording belongs to.
          recording_id: The ID of the recording to delete. Use "primary" to delete the primary
          recording.
        """
        if not session_id:
            raise ValueError(f"Expected a non-empty value for `session_id` but received {session_id!r}")
        if not recording_id:
            raise ValueError(f"Expected a non-empty value for `recording_id` but received {recording_id!r}")
        return await self._delete(
            path_template(
                "/v1/sessions/{session_id}/recordings/{recording_id}", session_id=session_id, recording_id=recording_id
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.SuccessResponse,
        )
