# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Dict, Literal

import httpx

from ..types import models, params
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["TasksLegacyResource", "AsyncTasksLegacyResource"]


class TasksLegacyResource(SyncAPIResource):
    def create_task(
        self,
        *,
        name: str,
        language: Literal["typescript"],
        code: str | NotGiven = not_given,
        description: str | NotGiven = not_given,
        browser_configuration: params.SessionConfig | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskResponse:
        """
        Create Task (Legacy)

        Creates a new task or updates an existing task with the same name. Tasks are reusable code
        snippets
        that can be executed in browser sessions. Tasks support versioning with draft and published
        versions.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          name: Task name (letters, numbers, hyphens, and underscores only)
          code: Base64 encoded task code (optional)
          language: Programming language for the task
          description: Optional description of the task
          browser_configuration: Browser configuration for task execution
        """
        return self._post(
            "/v1/task",
            body=strip_not_given(
                {
                    "name": name,
                    "code": code,
                    "language": language,
                    "description": description,
                    "browserConfiguration": browser_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskResponse,
        )

    def list_tasks(
        self,
        *,
        page: str | NotGiven = not_given,
        limit: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskListResponse:
        """
        List Tasks (Legacy)

        Retrieves a paginated list of all tasks for the authenticated team. Tasks are returned
        with their latest version information and metadata.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          page: Page number
          limit: Number of tasks per page
        """
        return self._get(
            "/v1/task",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"page": page, "limit": limit}),
            ),
            cast_to=models.TaskListResponse,
        )

    def run_adhoc_task(
        self,
        *,
        task_id: str,
        version: str | NotGiven = not_given,
        session_id: str | NotGiven = not_given,
        async_: bool | NotGiven = not_given,
        override_browser_configuration: params.SessionConfig | NotGiven = not_given,
        inputs: Dict[str, object] | NotGiven = not_given,
        cleanup_sessions: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RunTaskResponse:
        """
        Run Task (Legacy)

        Executes a task in a browser session. The task can be run with a specific version or the
        latest version.
        Optionally, you can provide an existing session ID or let the system create a new one.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: Task identifier
          version: Version to run (draft, latest, or version number)
          session_id: Optional existing browser session ID to use for task execution
          async_: Whether to run the task asynchronously.
          override_browser_configuration: Override browser configuration for this execution
          inputs: Environment variables for task execution (keys must start with ANCHOR_)
          cleanup_sessions: Whether to cleanup browser sessions after task execution. Defaults to
          true.
        """
        return self._post(
            "/v1/task/run",
            body=strip_not_given(
                {
                    "taskId": task_id,
                    "version": version,
                    "sessionId": session_id,
                    "async": async_,
                    "overrideBrowserConfiguration": override_browser_configuration,
                    "inputs": inputs,
                    "cleanupSessions": cleanup_sessions,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RunTaskResponse,
        )

    def run_task_by_name(
        self,
        task_name: str,
        *,
        session_id: str | NotGiven = not_given,
        async_: bool | NotGiven = not_given,
        override_browser_configuration: params.SessionConfig | NotGiven = not_given,
        inputs: Dict[str, object] | NotGiven = not_given,
        cleanup_sessions: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RunTaskResponse:
        """
        Run Task by Name (Legacy)

        Executes a task by its name, always using the latest version. This is a convenience endpoint
        for running tasks without needing to know the task ID.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_name: The name of the task to run
          session_id: Optional existing browser session ID to use for task execution
          async_: Whether to run the task asynchronously
          override_browser_configuration: Override browser configuration for this execution
          inputs: Environment variables for task execution (keys must start with ANCHOR_)
          cleanup_sessions: Whether to cleanup browser sessions after task execution. Defaults to
          true.
        """
        if not task_name:
            raise ValueError(f"Expected a non-empty value for `task_name` but received {task_name!r}")
        return self._post(
            path_template("/v1/task/run/{taskName}", taskName=task_name),
            body=strip_not_given(
                {
                    "sessionId": session_id,
                    "async": async_,
                    "overrideBrowserConfiguration": override_browser_configuration,
                    "inputs": inputs,
                    "cleanupSessions": cleanup_sessions,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RunTaskResponse,
        )

    def get_task(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskMetadataResponse:
        """
        Get Task Metadata (Legacy)

        Retrieves task metadata without the code content. Useful for getting task information
        without downloading the full task code.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task to retrieve
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._get(
            path_template("/v1/task/{taskId}", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskMetadataResponse,
        )

    def update_task(
        self,
        task_id: str,
        *,
        name: str | NotGiven = not_given,
        description: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskMetadataResponse:
        """
        Update Task Metadata (Legacy)

        Updates task metadata (name and description). This does not affect the task code or
        versions.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task to update
          name: Task name (letters, numbers, hyphens, and underscores only)
          description: Optional description of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._put(
            path_template("/v1/task/{taskId}", taskId=task_id),
            body=strip_not_given({"name": name, "description": description}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskMetadataResponse,
        )

    def delete_task(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteTaskResponse:
        """
        Delete Task (Legacy)

        Soft deletes a task and all its versions. The task will no longer be accessible
        but the data is preserved for potential recovery.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task to delete
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._delete(
            path_template("/v1/task/{taskId}", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteTaskResponse,
        )

    def list_task_versions(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionsListResponse:
        """
        List Task Versions (Legacy)

        Retrieves all versions of a specific task, including draft and published versions.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._get(
            path_template("/v1/task/{taskId}/versions", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionsListResponse,
        )

    def get_latest_task_version(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Get Latest Task Version (Legacy)

        Retrieves the latest version of a task, including the full code content.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._get(
            path_template("/v1/task/{taskId}/latest", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    def get_task_draft(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Get Task Draft (Legacy)

        Retrieves the draft version of a task, including the full code content.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._get(
            path_template("/v1/task/{taskId}/draft", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    def save_task_draft(
        self,
        task_id: str,
        *,
        code: str,
        language: Literal["typescript"] | NotGiven = not_given,
        description: str | NotGiven = not_given,
        browser_configuration: params.SessionConfig | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Create or Update Task Draft (Legacy)

        Creates or updates the draft version of a task. Draft versions are used for development
        and testing before publishing.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
          code: Base64 encoded task code
          language: Programming language for the task
          description: Optional description of the version
          browser_configuration: Browser configuration for task execution
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._post(
            path_template("/v1/task/{taskId}/draft", taskId=task_id),
            body=strip_not_given(
                {
                    "code": code,
                    "language": language,
                    "description": description,
                    "browserConfiguration": browser_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    def deploy_task(
        self,
        task_id: str,
        *,
        code: str | NotGiven = not_given,
        language: Literal["typescript"] | NotGiven = not_given,
        description: str | NotGiven = not_given,
        browser_configuration: params.SessionConfig | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Deploy Task (Legacy)

        Deploys a task by creating a new version with auto-incremented version number.
        This is the recommended way to publish task changes.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
          code: Base64 encoded task code (required for new versions)
          language: Programming language for the task
          description: Optional description of the version
          browser_configuration: Browser configuration for task execution
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._post(
            path_template("/v1/task/{taskId}/deploy", taskId=task_id),
            body=strip_not_given(
                {
                    "code": code,
                    "language": language,
                    "description": description,
                    "browserConfiguration": browser_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    def list_task_executions(
        self,
        task_id: str,
        *,
        page: str | NotGiven = not_given,
        limit: str | NotGiven = not_given,
        status: Literal["success", "failure", "timeout", "cancelled", "queued", "running"] | NotGiven = not_given,
        version: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskExecutionResultsListResponse:
        """
        List Task Executions (Legacy)

        Retrieves execution history for a task, including success/failure status,
        execution times, and outputs. Results can be filtered by version and status.

        If you are using the new Task Builder, see the Tasks V2 endpoints in this API reference.

        Args:
          task_id: The ID of the task
          page: Page number
          limit: Number of results per page
          status: Filter by execution status
          version: Filter by task version
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._get(
            path_template("/v1/task/{taskId}/executions", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"page": page, "limit": limit, "status": status, "version": version}),
            ),
            cast_to=models.TaskExecutionResultsListResponse,
        )

    def get_task_execution(
        self,
        task_id: str,
        execution_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskExecutionResultResponse:
        """
        Get Task Execution Result (Legacy)

        Retrieves a single execution result by its ID. This endpoint is useful for polling
        execution status in async mode or retrieving detailed execution information.

        If you are using the new Task Builder, see the Tasks V2 endpoints in this API reference.

        Args:
          task_id: The ID of the task
          execution_id: The ID of the execution result
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        if not execution_id:
            raise ValueError(f"Expected a non-empty value for `execution_id` but received {execution_id!r}")
        return self._get(
            path_template("/v1/task/{taskId}/executions/{executionId}", taskId=task_id, executionId=execution_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskExecutionResultResponse,
        )

    def get_task_version(
        self,
        task_id: str,
        task_version: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Get Task Version (Legacy)

        Retrieves a specific version of a task, including the full code content.

        If you are using the new Task Builder, see the Tasks V2 endpoints in this API reference.

        Args:
          task_id: The ID of the task
          task_version: The version to retrieve (draft, latest, or version number)
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        if not task_version:
            raise ValueError(f"Expected a non-empty value for `task_version` but received {task_version!r}")
        return self._get(
            path_template("/v1/task/{taskId}/{taskVersion}", taskId=task_id, taskVersion=task_version),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    def publish_task_version(
        self,
        task_id: str,
        task_version: str,
        *,
        code: str | NotGiven = not_given,
        language: Literal["typescript"] | NotGiven = not_given,
        description: str | NotGiven = not_given,
        browser_configuration: params.SessionConfig | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Publish Task Version (Legacy)

        Publishes a specific version of a task. This creates a new version if it doesn't exist,
        or updates an existing version's metadata.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
          task_version: The version to publish (cannot be draft)
          code: Base64 encoded task code (required for new versions)
          language: Programming language for the task
          description: Optional description of the version
          browser_configuration: Browser configuration for task execution
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        if not task_version:
            raise ValueError(f"Expected a non-empty value for `task_version` but received {task_version!r}")
        return self._post(
            path_template("/v1/task/{taskId}/{taskVersion}", taskId=task_id, taskVersion=task_version),
            body=strip_not_given(
                {
                    "code": code,
                    "language": language,
                    "description": description,
                    "browserConfiguration": browser_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    def delete_task_version(
        self,
        task_id: str,
        task_version: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteTaskResponse:
        """
        Delete Task Version (Legacy)

        Soft deletes a specific version of a task. The version will no longer be accessible
        but the data is preserved for potential recovery.

        If you are using the new Task Builder, see the Tasks V2 endpoints in this API reference.

        Args:
          task_id: The ID of the task
          task_version: The version to delete
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        if not task_version:
            raise ValueError(f"Expected a non-empty value for `task_version` but received {task_version!r}")
        return self._delete(
            path_template("/v1/task/{taskId}/{taskVersion}", taskId=task_id, taskVersion=task_version),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteTaskResponse,
        )


class AsyncTasksLegacyResource(AsyncAPIResource):
    async def create_task(
        self,
        *,
        name: str,
        language: Literal["typescript"],
        code: str | NotGiven = not_given,
        description: str | NotGiven = not_given,
        browser_configuration: params.SessionConfig | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskResponse:
        """
        Create Task (Legacy)

        Creates a new task or updates an existing task with the same name. Tasks are reusable code
        snippets
        that can be executed in browser sessions. Tasks support versioning with draft and published
        versions.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          name: Task name (letters, numbers, hyphens, and underscores only)
          code: Base64 encoded task code (optional)
          language: Programming language for the task
          description: Optional description of the task
          browser_configuration: Browser configuration for task execution
        """
        return await self._post(
            "/v1/task",
            body=strip_not_given(
                {
                    "name": name,
                    "code": code,
                    "language": language,
                    "description": description,
                    "browserConfiguration": browser_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskResponse,
        )

    async def list_tasks(
        self,
        *,
        page: str | NotGiven = not_given,
        limit: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskListResponse:
        """
        List Tasks (Legacy)

        Retrieves a paginated list of all tasks for the authenticated team. Tasks are returned
        with their latest version information and metadata.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          page: Page number
          limit: Number of tasks per page
        """
        return await self._get(
            "/v1/task",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"page": page, "limit": limit}),
            ),
            cast_to=models.TaskListResponse,
        )

    async def run_adhoc_task(
        self,
        *,
        task_id: str,
        version: str | NotGiven = not_given,
        session_id: str | NotGiven = not_given,
        async_: bool | NotGiven = not_given,
        override_browser_configuration: params.SessionConfig | NotGiven = not_given,
        inputs: Dict[str, object] | NotGiven = not_given,
        cleanup_sessions: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RunTaskResponse:
        """
        Run Task (Legacy)

        Executes a task in a browser session. The task can be run with a specific version or the
        latest version.
        Optionally, you can provide an existing session ID or let the system create a new one.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: Task identifier
          version: Version to run (draft, latest, or version number)
          session_id: Optional existing browser session ID to use for task execution
          async_: Whether to run the task asynchronously.
          override_browser_configuration: Override browser configuration for this execution
          inputs: Environment variables for task execution (keys must start with ANCHOR_)
          cleanup_sessions: Whether to cleanup browser sessions after task execution. Defaults to
          true.
        """
        return await self._post(
            "/v1/task/run",
            body=strip_not_given(
                {
                    "taskId": task_id,
                    "version": version,
                    "sessionId": session_id,
                    "async": async_,
                    "overrideBrowserConfiguration": override_browser_configuration,
                    "inputs": inputs,
                    "cleanupSessions": cleanup_sessions,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RunTaskResponse,
        )

    async def run_task_by_name(
        self,
        task_name: str,
        *,
        session_id: str | NotGiven = not_given,
        async_: bool | NotGiven = not_given,
        override_browser_configuration: params.SessionConfig | NotGiven = not_given,
        inputs: Dict[str, object] | NotGiven = not_given,
        cleanup_sessions: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.RunTaskResponse:
        """
        Run Task by Name (Legacy)

        Executes a task by its name, always using the latest version. This is a convenience endpoint
        for running tasks without needing to know the task ID.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_name: The name of the task to run
          session_id: Optional existing browser session ID to use for task execution
          async_: Whether to run the task asynchronously
          override_browser_configuration: Override browser configuration for this execution
          inputs: Environment variables for task execution (keys must start with ANCHOR_)
          cleanup_sessions: Whether to cleanup browser sessions after task execution. Defaults to
          true.
        """
        if not task_name:
            raise ValueError(f"Expected a non-empty value for `task_name` but received {task_name!r}")
        return await self._post(
            path_template("/v1/task/run/{taskName}", taskName=task_name),
            body=strip_not_given(
                {
                    "sessionId": session_id,
                    "async": async_,
                    "overrideBrowserConfiguration": override_browser_configuration,
                    "inputs": inputs,
                    "cleanupSessions": cleanup_sessions,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.RunTaskResponse,
        )

    async def get_task(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskMetadataResponse:
        """
        Get Task Metadata (Legacy)

        Retrieves task metadata without the code content. Useful for getting task information
        without downloading the full task code.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task to retrieve
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._get(
            path_template("/v1/task/{taskId}", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskMetadataResponse,
        )

    async def update_task(
        self,
        task_id: str,
        *,
        name: str | NotGiven = not_given,
        description: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskMetadataResponse:
        """
        Update Task Metadata (Legacy)

        Updates task metadata (name and description). This does not affect the task code or
        versions.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task to update
          name: Task name (letters, numbers, hyphens, and underscores only)
          description: Optional description of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._put(
            path_template("/v1/task/{taskId}", taskId=task_id),
            body=strip_not_given({"name": name, "description": description}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskMetadataResponse,
        )

    async def delete_task(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteTaskResponse:
        """
        Delete Task (Legacy)

        Soft deletes a task and all its versions. The task will no longer be accessible
        but the data is preserved for potential recovery.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task to delete
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._delete(
            path_template("/v1/task/{taskId}", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteTaskResponse,
        )

    async def list_task_versions(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionsListResponse:
        """
        List Task Versions (Legacy)

        Retrieves all versions of a specific task, including draft and published versions.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._get(
            path_template("/v1/task/{taskId}/versions", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionsListResponse,
        )

    async def get_latest_task_version(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Get Latest Task Version (Legacy)

        Retrieves the latest version of a task, including the full code content.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._get(
            path_template("/v1/task/{taskId}/latest", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    async def get_task_draft(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Get Task Draft (Legacy)

        Retrieves the draft version of a task, including the full code content.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._get(
            path_template("/v1/task/{taskId}/draft", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    async def save_task_draft(
        self,
        task_id: str,
        *,
        code: str,
        language: Literal["typescript"] | NotGiven = not_given,
        description: str | NotGiven = not_given,
        browser_configuration: params.SessionConfig | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Create or Update Task Draft (Legacy)

        Creates or updates the draft version of a task. Draft versions are used for development
        and testing before publishing.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
          code: Base64 encoded task code
          language: Programming language for the task
          description: Optional description of the version
          browser_configuration: Browser configuration for task execution
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._post(
            path_template("/v1/task/{taskId}/draft", taskId=task_id),
            body=strip_not_given(
                {
                    "code": code,
                    "language": language,
                    "description": description,
                    "browserConfiguration": browser_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    async def deploy_task(
        self,
        task_id: str,
        *,
        code: str | NotGiven = not_given,
        language: Literal["typescript"] | NotGiven = not_given,
        description: str | NotGiven = not_given,
        browser_configuration: params.SessionConfig | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Deploy Task (Legacy)

        Deploys a task by creating a new version with auto-incremented version number.
        This is the recommended way to publish task changes.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
          code: Base64 encoded task code (required for new versions)
          language: Programming language for the task
          description: Optional description of the version
          browser_configuration: Browser configuration for task execution
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._post(
            path_template("/v1/task/{taskId}/deploy", taskId=task_id),
            body=strip_not_given(
                {
                    "code": code,
                    "language": language,
                    "description": description,
                    "browserConfiguration": browser_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    async def list_task_executions(
        self,
        task_id: str,
        *,
        page: str | NotGiven = not_given,
        limit: str | NotGiven = not_given,
        status: Literal["success", "failure", "timeout", "cancelled", "queued", "running"] | NotGiven = not_given,
        version: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskExecutionResultsListResponse:
        """
        List Task Executions (Legacy)

        Retrieves execution history for a task, including success/failure status,
        execution times, and outputs. Results can be filtered by version and status.

        If you are using the new Task Builder, see the Tasks V2 endpoints in this API reference.

        Args:
          task_id: The ID of the task
          page: Page number
          limit: Number of results per page
          status: Filter by execution status
          version: Filter by task version
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._get(
            path_template("/v1/task/{taskId}/executions", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"page": page, "limit": limit, "status": status, "version": version}),
            ),
            cast_to=models.TaskExecutionResultsListResponse,
        )

    async def get_task_execution(
        self,
        task_id: str,
        execution_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskExecutionResultResponse:
        """
        Get Task Execution Result (Legacy)

        Retrieves a single execution result by its ID. This endpoint is useful for polling
        execution status in async mode or retrieving detailed execution information.

        If you are using the new Task Builder, see the Tasks V2 endpoints in this API reference.

        Args:
          task_id: The ID of the task
          execution_id: The ID of the execution result
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        if not execution_id:
            raise ValueError(f"Expected a non-empty value for `execution_id` but received {execution_id!r}")
        return await self._get(
            path_template("/v1/task/{taskId}/executions/{executionId}", taskId=task_id, executionId=execution_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskExecutionResultResponse,
        )

    async def get_task_version(
        self,
        task_id: str,
        task_version: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Get Task Version (Legacy)

        Retrieves a specific version of a task, including the full code content.

        If you are using the new Task Builder, see the Tasks V2 endpoints in this API reference.

        Args:
          task_id: The ID of the task
          task_version: The version to retrieve (draft, latest, or version number)
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        if not task_version:
            raise ValueError(f"Expected a non-empty value for `task_version` but received {task_version!r}")
        return await self._get(
            path_template("/v1/task/{taskId}/{taskVersion}", taskId=task_id, taskVersion=task_version),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    async def publish_task_version(
        self,
        task_id: str,
        task_version: str,
        *,
        code: str | NotGiven = not_given,
        language: Literal["typescript"] | NotGiven = not_given,
        description: str | NotGiven = not_given,
        browser_configuration: params.SessionConfig | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskVersionResponse:
        """
        Publish Task Version (Legacy)

        Publishes a specific version of a task. This creates a new version if it doesn't exist,
        or updates an existing version's metadata.

        If you are using the new Task Builder, see the non-deprecated Tasks endpoints in this API
        reference.

        Args:
          task_id: The ID of the task
          task_version: The version to publish (cannot be draft)
          code: Base64 encoded task code (required for new versions)
          language: Programming language for the task
          description: Optional description of the version
          browser_configuration: Browser configuration for task execution
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        if not task_version:
            raise ValueError(f"Expected a non-empty value for `task_version` but received {task_version!r}")
        return await self._post(
            path_template("/v1/task/{taskId}/{taskVersion}", taskId=task_id, taskVersion=task_version),
            body=strip_not_given(
                {
                    "code": code,
                    "language": language,
                    "description": description,
                    "browserConfiguration": browser_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskVersionResponse,
        )

    async def delete_task_version(
        self,
        task_id: str,
        task_version: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.DeleteTaskResponse:
        """
        Delete Task Version (Legacy)

        Soft deletes a specific version of a task. The version will no longer be accessible
        but the data is preserved for potential recovery.

        If you are using the new Task Builder, see the Tasks V2 endpoints in this API reference.

        Args:
          task_id: The ID of the task
          task_version: The version to delete
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        if not task_version:
            raise ValueError(f"Expected a non-empty value for `task_version` but received {task_version!r}")
        return await self._delete(
            path_template("/v1/task/{taskId}/{taskVersion}", taskId=task_id, taskVersion=task_version),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.DeleteTaskResponse,
        )
