# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Dict, Iterable

import httpx

from ..types import models, params
from .._types import Body, Query, Headers, NotGiven, not_given
from .._utils import path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["TasksResource", "AsyncTasksResource"]


class TasksResource(SyncAPIResource):
    def run_task(
        self,
        task_id: str,
        *,
        input_params: Dict[str, object],
        identity_id: str | NotGiven = not_given,
        session_id: str | NotGiven = not_given,
        cleanup_sessions: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskRunStatusV2Response:
        """
        Run a Task

        Triggers execution of a task by ID using the non-deprecated Tasks endpoints.

        Args:
          task_id: The ID of the task to run
          input_params: Key-value pairs of input parameters for the task
          identity_id: Optional identity ID to use for the task
          session_id: Optional session ID to run the task in
          cleanup_sessions: Whether to clean up sessions after execution (default: true)
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._post(
            path_template("/v2/tasks/{taskId}/run", taskId=task_id),
            body=strip_not_given(
                {
                    "input_params": input_params,
                    "identity_id": identity_id,
                    "session_id": session_id,
                    "cleanup_sessions": cleanup_sessions,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskRunStatusV2Response,
        )

    def get_task_run_status(
        self,
        run_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskRunStatusV2Response:
        """
        Get Task Run Status

        Retrieves the current status and result of a task run in the non-deprecated Tasks endpoints.

        Args:
          run_id: The ID of the task run
        """
        if not run_id:
            raise ValueError(f"Expected a non-empty value for `run_id` but received {run_id!r}")
        return self._get(
            path_template("/v2/tasks/runs/{runId}/status", runId=run_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskRunStatusV2Response,
        )

    def generate_task(
        self,
        *,
        task_name: str,
        task_prompt: str,
        async_: bool | NotGiven = not_given,
        description: str | NotGiven = not_given,
        application_id: str | NotGiven = not_given,
        identity_id: str | NotGiven = not_given,
        input_schema: Iterable[params.TaskParameterV2] | NotGiven = not_given,
        output_schema: Iterable[params.TaskParameterV2] | NotGiven = not_given,
        output_file_only: bool | NotGiven = not_given,
        human_intervention: bool | NotGiven = not_given,
        browser_session_id: str | NotGiven = not_given,
        task_browser_default_configuration: Dict[str, object] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.GenerateTaskV2Response:
        """
        Generate a Task

        Starts asynchronous generation of a new task from a natural-language prompt.
        Poll `GET /v2/tasks/{taskId}/generation-status` until the status is `ready`.

        Args:
          task_name: Name of the task
          task_prompt: Natural-language description of what the task should do, used for AI
          generation. Make it as detailed as possible with all the logic and steps needed to
          complete the task.
          async_: Whether to generate the task asynchronously
          description: Description of the task
          application_id: Optional application (connection) ID to associate with the task
          identity_id: Optional identity ID to use during task generation
          input_schema: Input parameters the task accepts
          output_schema: Output fields the task produces
          output_file_only: Whether task runs should return only the bundled session downloads file
          human_intervention: Allow human intervention during task execution
          browser_session_id: Existing finished browser session id to generate the workflow from
          task_browser_default_configuration: Optional default browser/session configuration when
          running this task
        """
        return self._post(
            "/v2/tasks/generate",
            body=strip_not_given(
                {
                    "taskName": task_name,
                    "taskPrompt": task_prompt,
                    "async": async_,
                    "description": description,
                    "application_id": application_id,
                    "identity_id": identity_id,
                    "input_schema": input_schema,
                    "output_schema": output_schema,
                    "output_file_only": output_file_only,
                    "human_intervention": human_intervention,
                    "browser_session_id": browser_session_id,
                    "task_browser_default_configuration": task_browser_default_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.GenerateTaskV2Response,
        )

    def get_task_generation_status(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskGenerationStatusV2Response:
        """
        Get Task Generation Status

        Returns the generation status of a task created via `POST /v2/tasks/generate`.

        Args:
          task_id: The ID of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return self._get(
            path_template("/v2/tasks/{taskId}/generation-status", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskGenerationStatusV2Response,
        )


class AsyncTasksResource(AsyncAPIResource):
    async def run_task(
        self,
        task_id: str,
        *,
        input_params: Dict[str, object],
        identity_id: str | NotGiven = not_given,
        session_id: str | NotGiven = not_given,
        cleanup_sessions: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskRunStatusV2Response:
        """
        Run a Task

        Triggers execution of a task by ID using the non-deprecated Tasks endpoints.

        Args:
          task_id: The ID of the task to run
          input_params: Key-value pairs of input parameters for the task
          identity_id: Optional identity ID to use for the task
          session_id: Optional session ID to run the task in
          cleanup_sessions: Whether to clean up sessions after execution (default: true)
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._post(
            path_template("/v2/tasks/{taskId}/run", taskId=task_id),
            body=strip_not_given(
                {
                    "input_params": input_params,
                    "identity_id": identity_id,
                    "session_id": session_id,
                    "cleanup_sessions": cleanup_sessions,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskRunStatusV2Response,
        )

    async def get_task_run_status(
        self,
        run_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskRunStatusV2Response:
        """
        Get Task Run Status

        Retrieves the current status and result of a task run in the non-deprecated Tasks endpoints.

        Args:
          run_id: The ID of the task run
        """
        if not run_id:
            raise ValueError(f"Expected a non-empty value for `run_id` but received {run_id!r}")
        return await self._get(
            path_template("/v2/tasks/runs/{runId}/status", runId=run_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskRunStatusV2Response,
        )

    async def generate_task(
        self,
        *,
        task_name: str,
        task_prompt: str,
        async_: bool | NotGiven = not_given,
        description: str | NotGiven = not_given,
        application_id: str | NotGiven = not_given,
        identity_id: str | NotGiven = not_given,
        input_schema: Iterable[params.TaskParameterV2] | NotGiven = not_given,
        output_schema: Iterable[params.TaskParameterV2] | NotGiven = not_given,
        output_file_only: bool | NotGiven = not_given,
        human_intervention: bool | NotGiven = not_given,
        browser_session_id: str | NotGiven = not_given,
        task_browser_default_configuration: Dict[str, object] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.GenerateTaskV2Response:
        """
        Generate a Task

        Starts asynchronous generation of a new task from a natural-language prompt.
        Poll `GET /v2/tasks/{taskId}/generation-status` until the status is `ready`.

        Args:
          task_name: Name of the task
          task_prompt: Natural-language description of what the task should do, used for AI
          generation. Make it as detailed as possible with all the logic and steps needed to
          complete the task.
          async_: Whether to generate the task asynchronously
          description: Description of the task
          application_id: Optional application (connection) ID to associate with the task
          identity_id: Optional identity ID to use during task generation
          input_schema: Input parameters the task accepts
          output_schema: Output fields the task produces
          output_file_only: Whether task runs should return only the bundled session downloads file
          human_intervention: Allow human intervention during task execution
          browser_session_id: Existing finished browser session id to generate the workflow from
          task_browser_default_configuration: Optional default browser/session configuration when
          running this task
        """
        return await self._post(
            "/v2/tasks/generate",
            body=strip_not_given(
                {
                    "taskName": task_name,
                    "taskPrompt": task_prompt,
                    "async": async_,
                    "description": description,
                    "application_id": application_id,
                    "identity_id": identity_id,
                    "input_schema": input_schema,
                    "output_schema": output_schema,
                    "output_file_only": output_file_only,
                    "human_intervention": human_intervention,
                    "browser_session_id": browser_session_id,
                    "task_browser_default_configuration": task_browser_default_configuration,
                }
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.GenerateTaskV2Response,
        )

    async def get_task_generation_status(
        self,
        task_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.TaskGenerationStatusV2Response:
        """
        Get Task Generation Status

        Returns the generation status of a task created via `POST /v2/tasks/generate`.

        Args:
          task_id: The ID of the task
        """
        if not task_id:
            raise ValueError(f"Expected a non-empty value for `task_id` but received {task_id!r}")
        return await self._get(
            path_template("/v2/tasks/{taskId}/generation-status", taskId=task_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.TaskGenerationStatusV2Response,
        )
