# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.

from __future__ import annotations

from typing import Literal, Mapping, cast

import httpx

from ..types import models
from .._types import Body, Query, Headers, NotGiven, FileTypes, not_given
from .._utils import extract_files, path_template, strip_not_given
from .._resource import SyncAPIResource, AsyncAPIResource
from .._base_client import make_request_options

__all__ = ["VolumesResource", "AsyncVolumesResource"]


class VolumesResource(SyncAPIResource):
    def create_volume(
        self,
        *,
        name: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeResponse:
        """
        Create Volume

        Create a persistent volume for your team. The volume is usually `ready` immediately; if the
        response says `creating`, poll `GET /v1/volumes/{volume_id}` until it is. Each team can
        have up to 10 volumes.

        Args:
          name: Volume name, unique within your team. Letters, numbers, `_` and `-`, up to 64
          characters.
        """
        return self._post(
            "/v1/volumes",
            body=strip_not_given({"name": name}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeResponse,
        )

    def list_volumes(
        self,
        *,
        include_deleted: Literal["true", "false"] | NotGiven = not_given,
        state: Literal["creating", "ready", "deleting", "deleted", "error"] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeListResponse:
        """
        List Volumes

        List the volumes of your team.

        Args:
          include_deleted: Include deleted volumes. Defaults to `false`.
          state: Only return volumes in this state
        """
        return self._get(
            "/v1/volumes",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"include_deleted": include_deleted, "state": state}),
            ),
            cast_to=models.VolumeListResponse,
        )

    def get_volume_by_name(
        self,
        name: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeResponse:
        """
        Get Volume By Name

        Get a volume by its name.
        """
        if not name:
            raise ValueError(f"Expected a non-empty value for `name` but received {name!r}")
        return self._get(
            path_template("/v1/volumes/by-name/{name}", name=name),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeResponse,
        )

    def get_volume(
        self,
        volume_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeResponse:
        """
        Get Volume

        Get a volume by its ID. Deleted volumes return `404`; use `GET
        /v1/volumes?include_deleted=true` to see them.
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._get(
            path_template("/v1/volumes/{volume_id}", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeResponse,
        )

    def delete_volume(
        self,
        volume_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumesDeleteVolumeResponse:
        """
        Delete Volume

        Delete a volume and every file in it. Refused while a running session has the volume
        mounted; end those sessions first.
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._delete(
            path_template("/v1/volumes/{volume_id}", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumesDeleteVolumeResponse,
        )

    def list_files(
        self,
        volume_id: str,
        *,
        path: str | NotGiven = not_given,
        recursive: Literal["true", "false"] | NotGiven = not_given,
        cursor: str | NotGiven = not_given,
        limit: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeFileListResponse:
        """
        List Files

        List the contents of a folder in the volume (one level, like `ls`), or the whole tree with
        `recursive=true`. Files written by a running session appear here about a minute after the
        session stops writing to them.

        Args:
          path: Folder to list, relative to the volume root. Omit for the root.
          recursive: List every file under `path` instead of one level
          cursor: `next_cursor` from the previous page
          limit: Page size, 1 to 1000
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._get(
            path_template("/v1/volumes/{volume_id}/files", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"path": path, "recursive": recursive, "cursor": cursor, "limit": limit}),
            ),
            cast_to=models.VolumeFileListResponse,
        )

    def upload_file(
        self,
        volume_id: str,
        *,
        file: FileTypes,
        path: str | NotGiven = not_given,
        overwrite: Literal["true", "false"] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeFileInfoResponse:
        """
        Upload File

        Upload a file into the volume in one multipart request. For files larger than 10 MB use
        `POST /v1/volumes/{volume_id}/files/upload-url` instead.

        Args:
          file: The file to upload
          path: Destination path relative to the volume root, e.g. `downloads/report.pdf`. Defaults
          to the uploaded file's name at the root.
          overwrite: Replace an existing file at `path`. Defaults to `false`.
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        body = strip_not_given({"file": file, "path": path, "overwrite": overwrite})
        files = extract_files(cast(Mapping[str, object], body), paths=[["file"]])
        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}
        return self._post(
            path_template("/v1/volumes/{volume_id}/files", volume_id=volume_id),
            body=body,
            files=files,
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeFileInfoResponse,
        )

    def delete_files(
        self,
        volume_id: str,
        *,
        path: str | NotGiven = not_given,
        prefix: str | NotGiven = not_given,
        recursive: Literal["true", "false"] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumesDeleteFilesResponse:
        """
        Delete Files

        Delete one file (`path`) or everything under a folder (`prefix` with `recursive=true`).

        Args:
          path: File to delete, relative to the volume root
          prefix: Folder to delete recursively; requires `recursive=true`
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._delete(
            path_template("/v1/volumes/{volume_id}/files", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"path": path, "prefix": prefix, "recursive": recursive}),
            ),
            cast_to=models.VolumesDeleteFilesResponse,
        )

    def create_upload_url(
        self,
        volume_id: str,
        *,
        path: str,
        content_type: str | NotGiven = not_given,
        size: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeUploadUrlResponse:
        """
        Create Upload URL

        Get a pre-signed URL to upload a file of any size (up to 5 GB) directly to storage. `PUT`
        the file body to `signed_url` and send the returned `headers` unchanged.

        Args:
          path: Destination path relative to the volume root
          content_type: MIME type of the file. Defaults to `application/octet-stream`.
          size: Size in bytes, if known
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._post(
            path_template("/v1/volumes/{volume_id}/files/upload-url", volume_id=volume_id),
            body=strip_not_given({"path": path, "content_type": content_type, "size": size}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeUploadUrlResponse,
        )

    def get_file_info(
        self,
        volume_id: str,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeFileInfoResponse:
        """
        Get File Info

        Size, type and modification time of one file.

        Args:
          path: File path relative to the volume root
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._get(
            path_template("/v1/volumes/{volume_id}/files/stat", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"path": path}),
            ),
            cast_to=models.VolumeFileInfoResponse,
        )

    def get_download_url(
        self,
        volume_id: str,
        *,
        path: str,
        redirect: Literal["true", "false"] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeDownloadUrlResponse:
        """
        Download File

        Get a pre-signed URL for a file. Pass `redirect=true` to be redirected to the file instead
        of receiving the URL.

        Args:
          path: File path relative to the volume root
          redirect: Respond with a `302` to the file instead of JSON
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._get(
            path_template("/v1/volumes/{volume_id}/files/download", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"path": path, "redirect": redirect}),
            ),
            cast_to=models.VolumeDownloadUrlResponse,
        )

    def list_paths(
        self,
        volume_id: str,
        *,
        prefix: str | NotGiven = not_given,
        cursor: str | NotGiven = not_given,
        limit: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumePathListResponse:
        """
        List All Paths

        Flat list of every path in the volume, optionally under a prefix. Folders appear with a
        trailing slash (for example `downloads/`).

        Args:
          prefix: Only paths under this folder
          limit: Page size, 1 to 1000
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._get(
            path_template("/v1/volumes/{volume_id}/paths", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"prefix": prefix, "cursor": cursor, "limit": limit}),
            ),
            cast_to=models.VolumePathListResponse,
        )

    def create_directory(
        self,
        volume_id: str,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumesCreateDirectoryResponse:
        """
        Create Directory

        Create an empty folder in the volume. Folders are also created implicitly when a file is
        uploaded to a path inside them.
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return self._post(
            path_template("/v1/volumes/{volume_id}/directories", volume_id=volume_id),
            body=strip_not_given({"path": path}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumesCreateDirectoryResponse,
        )


class AsyncVolumesResource(AsyncAPIResource):
    async def create_volume(
        self,
        *,
        name: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeResponse:
        """
        Create Volume

        Create a persistent volume for your team. The volume is usually `ready` immediately; if the
        response says `creating`, poll `GET /v1/volumes/{volume_id}` until it is. Each team can
        have up to 10 volumes.

        Args:
          name: Volume name, unique within your team. Letters, numbers, `_` and `-`, up to 64
          characters.
        """
        return await self._post(
            "/v1/volumes",
            body=strip_not_given({"name": name}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeResponse,
        )

    async def list_volumes(
        self,
        *,
        include_deleted: Literal["true", "false"] | NotGiven = not_given,
        state: Literal["creating", "ready", "deleting", "deleted", "error"] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeListResponse:
        """
        List Volumes

        List the volumes of your team.

        Args:
          include_deleted: Include deleted volumes. Defaults to `false`.
          state: Only return volumes in this state
        """
        return await self._get(
            "/v1/volumes",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"include_deleted": include_deleted, "state": state}),
            ),
            cast_to=models.VolumeListResponse,
        )

    async def get_volume_by_name(
        self,
        name: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeResponse:
        """
        Get Volume By Name

        Get a volume by its name.
        """
        if not name:
            raise ValueError(f"Expected a non-empty value for `name` but received {name!r}")
        return await self._get(
            path_template("/v1/volumes/by-name/{name}", name=name),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeResponse,
        )

    async def get_volume(
        self,
        volume_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeResponse:
        """
        Get Volume

        Get a volume by its ID. Deleted volumes return `404`; use `GET
        /v1/volumes?include_deleted=true` to see them.
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._get(
            path_template("/v1/volumes/{volume_id}", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeResponse,
        )

    async def delete_volume(
        self,
        volume_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumesDeleteVolumeResponse:
        """
        Delete Volume

        Delete a volume and every file in it. Refused while a running session has the volume
        mounted; end those sessions first.
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._delete(
            path_template("/v1/volumes/{volume_id}", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumesDeleteVolumeResponse,
        )

    async def list_files(
        self,
        volume_id: str,
        *,
        path: str | NotGiven = not_given,
        recursive: Literal["true", "false"] | NotGiven = not_given,
        cursor: str | NotGiven = not_given,
        limit: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeFileListResponse:
        """
        List Files

        List the contents of a folder in the volume (one level, like `ls`), or the whole tree with
        `recursive=true`. Files written by a running session appear here about a minute after the
        session stops writing to them.

        Args:
          path: Folder to list, relative to the volume root. Omit for the root.
          recursive: List every file under `path` instead of one level
          cursor: `next_cursor` from the previous page
          limit: Page size, 1 to 1000
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._get(
            path_template("/v1/volumes/{volume_id}/files", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"path": path, "recursive": recursive, "cursor": cursor, "limit": limit}),
            ),
            cast_to=models.VolumeFileListResponse,
        )

    async def upload_file(
        self,
        volume_id: str,
        *,
        file: FileTypes,
        path: str | NotGiven = not_given,
        overwrite: Literal["true", "false"] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeFileInfoResponse:
        """
        Upload File

        Upload a file into the volume in one multipart request. For files larger than 10 MB use
        `POST /v1/volumes/{volume_id}/files/upload-url` instead.

        Args:
          file: The file to upload
          path: Destination path relative to the volume root, e.g. `downloads/report.pdf`. Defaults
          to the uploaded file's name at the root.
          overwrite: Replace an existing file at `path`. Defaults to `false`.
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        body = strip_not_given({"file": file, "path": path, "overwrite": overwrite})
        files = extract_files(cast(Mapping[str, object], body), paths=[["file"]])
        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}
        return await self._post(
            path_template("/v1/volumes/{volume_id}/files", volume_id=volume_id),
            body=body,
            files=files,
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeFileInfoResponse,
        )

    async def delete_files(
        self,
        volume_id: str,
        *,
        path: str | NotGiven = not_given,
        prefix: str | NotGiven = not_given,
        recursive: Literal["true", "false"] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumesDeleteFilesResponse:
        """
        Delete Files

        Delete one file (`path`) or everything under a folder (`prefix` with `recursive=true`).

        Args:
          path: File to delete, relative to the volume root
          prefix: Folder to delete recursively; requires `recursive=true`
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._delete(
            path_template("/v1/volumes/{volume_id}/files", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"path": path, "prefix": prefix, "recursive": recursive}),
            ),
            cast_to=models.VolumesDeleteFilesResponse,
        )

    async def create_upload_url(
        self,
        volume_id: str,
        *,
        path: str,
        content_type: str | NotGiven = not_given,
        size: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeUploadUrlResponse:
        """
        Create Upload URL

        Get a pre-signed URL to upload a file of any size (up to 5 GB) directly to storage. `PUT`
        the file body to `signed_url` and send the returned `headers` unchanged.

        Args:
          path: Destination path relative to the volume root
          content_type: MIME type of the file. Defaults to `application/octet-stream`.
          size: Size in bytes, if known
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._post(
            path_template("/v1/volumes/{volume_id}/files/upload-url", volume_id=volume_id),
            body=strip_not_given({"path": path, "content_type": content_type, "size": size}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumeUploadUrlResponse,
        )

    async def get_file_info(
        self,
        volume_id: str,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeFileInfoResponse:
        """
        Get File Info

        Size, type and modification time of one file.

        Args:
          path: File path relative to the volume root
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._get(
            path_template("/v1/volumes/{volume_id}/files/stat", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"path": path}),
            ),
            cast_to=models.VolumeFileInfoResponse,
        )

    async def get_download_url(
        self,
        volume_id: str,
        *,
        path: str,
        redirect: Literal["true", "false"] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumeDownloadUrlResponse:
        """
        Download File

        Get a pre-signed URL for a file. Pass `redirect=true` to be redirected to the file instead
        of receiving the URL.

        Args:
          path: File path relative to the volume root
          redirect: Respond with a `302` to the file instead of JSON
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._get(
            path_template("/v1/volumes/{volume_id}/files/download", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"path": path, "redirect": redirect}),
            ),
            cast_to=models.VolumeDownloadUrlResponse,
        )

    async def list_paths(
        self,
        volume_id: str,
        *,
        prefix: str | NotGiven = not_given,
        cursor: str | NotGiven = not_given,
        limit: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumePathListResponse:
        """
        List All Paths

        Flat list of every path in the volume, optionally under a prefix. Folders appear with a
        trailing slash (for example `downloads/`).

        Args:
          prefix: Only paths under this folder
          limit: Page size, 1 to 1000
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._get(
            path_template("/v1/volumes/{volume_id}/paths", volume_id=volume_id),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=strip_not_given({"prefix": prefix, "cursor": cursor, "limit": limit}),
            ),
            cast_to=models.VolumePathListResponse,
        )

    async def create_directory(
        self,
        volume_id: str,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> models.VolumesCreateDirectoryResponse:
        """
        Create Directory

        Create an empty folder in the volume. Folders are also created implicitly when a file is
        uploaded to a path inside them.
        """
        if not volume_id:
            raise ValueError(f"Expected a non-empty value for `volume_id` but received {volume_id!r}")
        return await self._post(
            path_template("/v1/volumes/{volume_id}/directories", volume_id=volume_id),
            body=strip_not_given({"path": path}),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=models.VolumesCreateDirectoryResponse,
        )
