#!/usr/bin/env python3
# yaml-driven spec/manifest handling is inherently untyped
# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false
"""Generate the SDK resource layer from spec/openapi.yaml + spec/sdk-manifest.yaml.

This is the Python analog of the TypeScript SDK's @hey-api generation step
(no mature Python equivalent exists yet, so this repo owns a small emitter).
It writes, in the vendored runtime's style:

  - src/anchorbrowser/resources/<class>.py  — one file per manifest class with
    Sync + Async resource classes, one method per operation
  - src/anchorbrowser/resources/_mixins.py  — client mixins registering every
    generated resource as a cached property
  - src/anchorbrowser/resources/__init__.py — re-exports

Naming comes from spec/sdk-manifest.yaml (shared with the TypeScript SDK):
manifest `class: Sessions` -> `client.sessions`, manifest
`method: createSession` -> `client.sessions.create_session`. Operations
missing a manifest entry get a deterministic auto-derived name and a warning
— add a manifest entry to override.

Hand-written files are never touched: resources/browser.py and
resources/agent_helpers.py (the Playwright/agent-task helpers), lib/.

Response/request model types come from src/anchorbrowser/types/models.py and
types/params.py, generated by datamodel-code-generator (see scripts/generate).
"""

from __future__ import annotations

import re
import sys
import keyword
import argparse
from typing import Any
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO / "spec" / "openapi.yaml"
MANIFEST_PATH = REPO / "spec" / "sdk-manifest.yaml"
RESOURCES_DIR = REPO / "src" / "anchorbrowser" / "resources"

HTTP_METHODS = {"get", "post", "put", "patch", "delete"}
# hand-written files the generator must never write or delete
PRESERVE = {"browser.py", "agent_helpers.py"}

HEADER = "# Generated by scripts/generate from spec/openapi.yaml + spec/sdk-manifest.yaml — do not edit.\n"


# kwargs reserved by every generated method's signature
RESERVED_PARAM_NAMES = {"extra_headers", "extra_query", "extra_body", "timeout", "self"}


def snake(name: str) -> str:
    """camelCase / PascalCase / kebab-case -> snake_case; keyword- and reserved-safe."""
    s = re.sub(r"[-\s]+", "_", name)
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", s)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    s = s.replace("__", "_").lower()
    if keyword.iskeyword(s) or s in RESERVED_PARAM_NAMES:
        s += "_"
    return s


def pascal(name: str) -> str:
    return "".join(part.capitalize() if not part[:1].isupper() else part for part in re.split(r"[_\-\s]+", name))


class Ctx:
    def __init__(self, spec_path: Path) -> None:
        self.spec: dict[str, Any] = yaml.safe_load(spec_path.read_text())
        self.manifest: dict[str, Any] = yaml.safe_load(MANIFEST_PATH.read_text())
        self.schemas: dict[str, Any] = self.spec.get("components", {}).get("schemas", {})
        self.warnings: list[str] = []

    def resolve(self, schema: dict[str, Any] | None) -> dict[str, Any]:
        if schema and "$ref" in schema:
            name = str(schema["$ref"]).split("/")[-1]
            resolved: dict[str, Any] = self.schemas.get(name, {})
            return resolved
        return schema or {}

    def ref_name(self, schema: dict[str, Any] | None) -> str | None:
        if schema and "$ref" in schema:
            return str(schema["$ref"]).split("/")[-1]
        return None


def py_type(ctx: Ctx, schema: dict[str, Any] | None, *, params_ns: set[str]) -> str:
    """Shallow schema -> annotation. $ref objects use the params TypedDicts."""
    if not schema:
        return "object"
    ref = ctx.ref_name(schema)
    if ref:
        resolved = ctx.resolve(schema)
        if resolved.get("type") == "object" or "properties" in resolved or "oneOf" in resolved:
            params_ns.add(ref)
            return f"params.{ref}"
        return py_type(ctx, resolved, params_ns=params_ns)
    t = schema.get("type")
    if "oneOf" in schema or "anyOf" in schema:
        subs = schema.get("oneOf") or schema.get("anyOf") or []
        inner = sorted({py_type(ctx, s, params_ns=params_ns) for s in subs})
        return f"Union[{', '.join(inner)}]" if len(inner) > 1 else inner[0]
    if t == "string":
        enum = schema.get("enum")
        if enum and all(isinstance(v, str) for v in enum):
            vals = ", ".join(f'"{v}"' for v in enum)
            return f"Literal[{vals}]"
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"Iterable[{py_type(ctx, schema.get('items'), params_ns=params_ns)}]"
    if t == "object" or "properties" in schema:
        return "Dict[str, object]"
    return "object"


def first_2xx(op: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    for status in ("200", "201", "202", "204"):
        if status in op.get("responses", {}):
            return status, op["responses"][status]
    return "", {}


def doc_wrap(text: str, indent: str) -> list[str]:
    out: list[str] = []
    for para in text.strip().splitlines():
        para = para.rstrip()
        while len(para) > 100 - len(indent):
            cut = para.rfind(" ", 0, 100 - len(indent))
            if cut <= 0:
                break
            out.append(indent + para[:cut])
            para = para[cut + 1 :]
        out.append(indent + para if para else "")
    return out


class Param:
    def __init__(self, py_name: str, wire_name: str, annotation: str, required: bool, description: str) -> None:
        self.py_name = py_name
        self.wire_name = wire_name
        self.annotation = annotation
        self.required = required
        self.description = description


class Operation:
    def __init__(self, ctx: Ctx, path: str, http_method: str, op: dict[str, Any], py_method: str) -> None:
        self.path = path
        self.http_method = http_method
        self.py_method = py_method
        self.summary = op.get("summary", "")
        self.description = op.get("description", "")
        self.models_ns: set[str] = set()
        self.params_ns: set[str] = set()

        raw_params = [ctx.resolve(p) if "$ref" in p else p for p in op.get("parameters", [])]
        self.path_params = [
            Param(snake(p["name"]), p["name"], "str", True, p.get("description", ""))
            for p in raw_params
            if p.get("in") == "path"
        ]
        self.query_params = [
            Param(
                snake(p["name"]),
                p["name"],
                py_type(ctx, p.get("schema"), params_ns=self.params_ns),
                bool(p.get("required")),
                p.get("description", ""),
            )
            for p in raw_params
            if p.get("in") == "query"
        ]

        # request body
        self.body_params: list[Param] = []
        self.file_params: list[Param] = []
        self.is_multipart = False
        body = op.get("requestBody")
        if body:
            body = ctx.resolve(body) if "$ref" in body else body
            content = body.get("content", {})
            media = None
            if "application/json" in content:
                media = content["application/json"]
            elif "multipart/form-data" in content:
                media = content["multipart/form-data"]
                self.is_multipart = True
            if media is not None:
                schema = ctx.resolve(media.get("schema"))
                if "allOf" in schema:
                    # flatten allOf compositions (e.g. CoordinatesRequestSchema + extras)
                    # so every part's properties become method kwargs
                    merged_props: dict[str, Any] = {}
                    merged_required: list[str] = []
                    for part in schema["allOf"]:
                        resolved_part = ctx.resolve(part)
                        merged_props.update(resolved_part.get("properties") or {})
                        merged_required.extend(resolved_part.get("required") or [])
                    merged: dict[str, Any] = {"type": "object", "properties": merged_props, "required": merged_required}
                    schema = merged
                required = set(schema.get("required", []))
                for prop, prop_schema in (schema.get("properties") or {}).items():
                    resolved_prop = ctx.resolve(prop_schema)
                    desc = prop_schema.get("description") or resolved_prop.get("description", "")
                    if self.is_multipart and resolved_prop.get("format") == "binary":
                        self.file_params.append(Param(snake(prop), prop, "FileTypes", prop in required, desc))
                    else:
                        ann = py_type(ctx, prop_schema, params_ns=self.params_ns)
                        self.body_params.append(Param(snake(prop), prop, ann, prop in required, desc))

        # response
        _status, resp = first_2xx(op)
        self.cast_to = "object"
        self.return_ann = "object"
        self.accept: str | None = None
        content = (resp or {}).get("content", {})
        if not content:
            self.cast_to = "NoneType"
            self.return_ann = "None"
        elif "application/json" in content:
            ref = ctx.ref_name(content["application/json"].get("schema"))
            if ref:
                self.models_ns.add(ref)
                self.cast_to = f"models.{ref}"
                self.return_ann = f"models.{ref}"
        else:
            ctype = next(iter(content))
            if ctype.startswith("text/"):
                self.cast_to = "str"
                self.return_ann = "str"
            else:
                self.cast_to = "__BINARY__"
                self.return_ann = "__BINARY__"
            self.accept = ctype


def emit_method(op: Operation, *, is_async: bool) -> list[str]:
    a = "async " if is_async else ""
    aw = "await " if is_async else ""
    binary_cls = "AsyncBinaryAPIResponse" if is_async else "BinaryAPIResponse"
    cast_to = op.cast_to.replace("__BINARY__", binary_cls)
    return_ann = op.return_ann.replace("__BINARY__", binary_cls)

    lines: list[str] = []
    sig: list[str] = [f"    {a}def {op.py_method}("]
    sig.append("        self,")
    for p in op.path_params:
        sig.append(f"        {p.py_name}: str,")
    optional_parts: list[str] = []
    required_kw: list[str] = []
    for p in op.file_params + op.body_params + op.query_params:
        if p.required:
            required_kw.append(f"        {p.py_name}: {p.annotation},")
        else:
            optional_parts.append(f"        {p.py_name}: {p.annotation} | NotGiven = not_given,")
    if required_kw or optional_parts:
        sig.append("        *,")
        sig.extend(required_kw)
        sig.extend(optional_parts)
    else:
        sig.append("        *,")
    sig.append("        extra_headers: Headers | None = None,")
    sig.append("        extra_query: Query | None = None,")
    sig.append("        extra_body: Body | None = None,")
    sig.append("        timeout: float | httpx.Timeout | None | NotGiven = not_given,")
    sig.append(f"    ) -> {return_ann}:")
    lines.extend(sig)

    # docstring
    doc: list[str] = ['        """']
    text = op.summary or op.py_method
    if op.description and op.description.strip() != op.summary.strip():
        text = (op.summary + "\n\n" if op.summary else "") + op.description
    doc.extend(doc_wrap(text, "        "))
    arg_docs = [(p.py_name, p.description) for p in op.path_params + op.file_params + op.body_params + op.query_params if p.description]
    if arg_docs:
        doc.append("")
        doc.append("        Args:")
        for name, desc in arg_docs:
            doc.extend(doc_wrap(f"{name}: {desc}", "          "))
    doc.append('        """')
    lines.extend(doc)

    for p in op.path_params:
        lines.append(f"        if not {p.py_name}:")
        lines.append(
            f'            raise ValueError(f"Expected a non-empty value for `{p.py_name}` but received {{{p.py_name}!r}}")'
        )

    if "{" in op.path:
        kwargs = ", ".join(f"{p.wire_name}={p.py_name}" for p in op.path_params)
        path_expr = f'path_template("{op.path}", {kwargs})'
    else:
        path_expr = f'"{op.path}"'

    body_expr = None
    files_expr = None
    if op.file_params or op.body_params:
        entries = ", ".join(f'"{p.wire_name}": {p.py_name}' for p in op.body_params)
        if op.is_multipart:
            fentries = ", ".join(f'"{p.wire_name}": {p.py_name}' for p in op.file_params)
            lines.append(f"        body = strip_not_given({{{fentries}{', ' if entries else ''}{entries}}})")
            paths = ", ".join(f'["{p.wire_name}"]' for p in op.file_params)
            lines.append(f"        files = extract_files(cast(Mapping[str, object], body), paths=[{paths}])")
            lines.append(
                '        extra_headers = {"Content-Type": "multipart/form-data", **(extra_headers or {})}'
            )
            body_expr = "body"
            files_expr = "files"
        else:
            body_expr = f"strip_not_given({{{entries}}})"

    if op.accept:
        lines.append(f'        extra_headers = {{"Accept": "{op.accept}", **(extra_headers or {{}})}}')

    query_expr = None
    if op.query_params:
        qentries = ", ".join(f'"{p.wire_name}": {p.py_name}' for p in op.query_params)
        query_expr = f"strip_not_given({{{qentries}}})"

    call: list[str] = [f"        return {aw}self._{op.http_method}("]
    call.append(f"            {path_expr},")
    if body_expr:
        call.append(f"            body={body_expr},")
    if files_expr:
        call.append(f"            files={files_expr},")
    opts = "extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout"
    if query_expr:
        call.append("            options=make_request_options(")
        call.append(f"                {opts}, query={query_expr}")
        call.append("            ),")
    else:
        call.append(f"            options=make_request_options({opts}),")
    call.append(f"            cast_to={cast_to},")
    call.append("        )")
    lines.extend(call)
    lines.append("")
    return lines


def emit_resource_file(class_name: str, ops: list[Operation]) -> str:
    models_ns: set[str] = set()
    params_ns: set[str] = set()
    uses_binary = uses_files = uses_path_template = uses_none = False
    for op in ops:
        models_ns |= op.models_ns
        params_ns |= op.params_ns
        if op.cast_to == "__BINARY__":
            uses_binary = True
        if op.is_multipart:
            uses_files = True
        if "{" in op.path:
            uses_path_template = True
        if op.cast_to == "NoneType":
            uses_none = True

    lines: list[str] = [HEADER, "from __future__ import annotations", ""]
    typing_names: set[str] = set()
    for op in ops:
        for p in op.body_params + op.query_params:
            for tok in ("Literal", "Union", "Iterable", "Dict"):
                if re.search(rf"\b{tok}\[", p.annotation):
                    typing_names.add(tok)
    if uses_files:
        typing_names |= {"Mapping", "cast"}
    if typing_names:
        lines.append(f"from typing import {', '.join(sorted(typing_names))}")
        lines.append("")
    lines.append("import httpx")
    lines.append("")
    utils = ["strip_not_given"]
    if uses_path_template:
        utils.append("path_template")
    if uses_files:
        utils.append("extract_files")
    types_imports = ["Body", "Query", "Headers", "NotGiven", "not_given"]
    if uses_files:
        types_imports.append("FileTypes")
    lines.append(f"from .._types import {', '.join(types_imports)}")
    lines.append(f"from .._utils import {', '.join(sorted(set(utils)))}")
    lines.append("from .._resource import SyncAPIResource, AsyncAPIResource")
    lines.append("from .._base_client import make_request_options")
    if uses_binary:
        lines.append("from .._response import BinaryAPIResponse, AsyncBinaryAPIResponse")
    if uses_none:
        lines.append("from .._models import NoneType")
    if models_ns:
        lines.append("from ..types import models")
    if params_ns:
        lines.append("from ..types import params")
    lines.append("")
    lines.append("")
    lines.append(f'__all__ = ["{class_name}Resource", "Async{class_name}Resource"]')
    lines.append("")

    for is_async, prefix in ((False, ""), (True, "Async")):
        base = "AsyncAPIResource" if is_async else "SyncAPIResource"
        lines.append("")
        lines.append(f"class {prefix}{class_name}Resource({base}):")
        for op in ops:
            lines.extend(emit_method(op, is_async=is_async))
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--spec",
        type=Path,
        default=SPEC_PATH,
        help="OpenAPI spec to generate from (normally the scripts/preprocess_spec.py output)",
    )
    args = ap.parse_args()

    ctx = Ctx(args.spec)
    naming: dict[str, Any] = ctx.manifest.get("naming", {})

    by_class: dict[str, list[Operation]] = {}
    for path, path_item in (ctx.spec.get("paths") or {}).items():
        for http_method, op in path_item.items():
            if http_method not in HTTP_METHODS:
                continue
            key = f"{http_method} {path}"
            entry = naming.get(key)
            if entry:
                class_name, method_name = entry["class"], entry["method"]
            else:
                class_name = pascal((op.get("tags") or ["Api"])[0])
                parts = [seg if not seg.startswith("{") else "by_" + seg[1:-1] for seg in path.split("/") if seg]
                method_name = http_method + "_" + "_".join(parts)
                ctx.warnings.append(f"{key} -> {class_name}.{snake(method_name)} (auto-derived; add to sdk-manifest.yaml)")
            by_class.setdefault(class_name, []).append(Operation(ctx, path, http_method, op, snake(method_name)))

    RESOURCES_DIR.mkdir(parents=True, exist_ok=True)
    # remove previously generated files (never the preserved hand-written ones)
    for f in RESOURCES_DIR.glob("*.py"):
        if f.name in PRESERVE:
            continue
        f.unlink()
    for sub in [d for d in RESOURCES_DIR.iterdir() if d.is_dir()]:
        import shutil

        shutil.rmtree(sub)

    class_files: list[tuple[str, str]] = []  # (ClassName, module_name)
    for class_name in sorted(by_class):
        module = snake(class_name)
        (RESOURCES_DIR / f"{module}.py").write_text(emit_resource_file(class_name, by_class[class_name]))
        class_files.append((class_name, module))

    # mixins
    m: list[str] = [HEADER, "from __future__ import annotations", "", "from .._compat import cached_property", ""]
    for cls, module in class_files:
        m.append(f"from .{module} import {cls}Resource, Async{cls}Resource")
    m.append("")
    m.append("")
    for prefix in ("", "Async"):
        m.append(f"class {prefix or 'Sync'}ResourcesMixin:")
        for cls, _module in class_files:
            attr = snake(cls)
            m.append("    @cached_property")
            m.append(f"    def {attr}(self) -> {prefix}{cls}Resource:")
            m.append(f"        return {prefix}{cls}Resource(self)  # type: ignore[arg-type]")
            m.append("")
        m.append("")
    (RESOURCES_DIR / "_mixins.py").write_text("\n".join(m) + "\n")

    # __init__
    init: list[str] = [HEADER]
    for cls, module in class_files:
        init.append(f"from .{module} import {cls}Resource as {cls}Resource, Async{cls}Resource as Async{cls}Resource")
    init.append("from .browser import BrowserResource as BrowserResource, AsyncBrowserResource as AsyncBrowserResource")
    init.append(
        "from .agent_helpers import AgentHelpersResource as AgentHelpersResource, AsyncAgentHelpersResource as AsyncAgentHelpersResource"
    )
    (RESOURCES_DIR / "__init__.py").write_text("\n".join(init) + "\n")

    total = sum(len(v) for v in by_class.values())
    print(f"generate_resources: {len(class_files)} resource classes, {total} operations")
    if ctx.warnings:
        print(f"generate_resources: {len(ctx.warnings)} operations without manifest naming (auto-derived):")
        for w in ctx.warnings:
            print("  -", w)
    return 0


if __name__ == "__main__":
    sys.exit(main())
